### PR TITLE
cranelift: Use GPR newtypes extensively in x64 lowering

### LINKED ISSUE #3685: Cranelift: provide `Gpr` and `Xmm` newtype wrappers around `Reg` and use them extensively in ISLE lowering
We've talked a bit

* about leveraging types better during lowering to make it easier to statically catch bugs (and help verification efforts) and
* differentiating between plain ol' moves and register-class-converting moves.

I think adding newtype wrappers around `Reg` for general purpose registers vs XMM registers, etc... would help both these things a lot. Basically every register class should have its own newtype wrapper.

I'm spending too much time debugging dynamic errors where I'm accidentally implicitly moving between register classes (either via mov mitosis or otherwise) and it would be way easier to fix this kind of thing if it was a compile time type error that specified exactly where in the sources I'm doing the wrong thing.

### PR DESCRIPTION
**Pull request by fitzgen**
We already defined the `Gpr` newtype and used it in a few places, and we already
defined the `Xmm` newtype and used it extensively. This finishes the transition
to using the newtypes extensively in lowering by making use of `Gpr` in more
places.

Fixes #3685

### CODE REVIEW

File: cranelift/codegen/src/isa/x64/inst/mod.rs [hunk 1]
```diff
@@ -174,10 +174,10 @@ impl Inst {
         Inst::Div {
             size,
             signed,
-            divisor,
-            dividend: regs::rax(),
-            dst_quotient: Writable::from_reg(regs::rax()),
-            dst_remainder: Writable::from_reg(regs::rdx()),
+            divisor: GprMem::new(divisor).unwrap(),
+            dividend: Gpr::new(regs::rax()).unwrap(),
```
Comment (cfallin) [inline cranelift/codegen/src/isa/x64/inst/mod.rs:178]: Would it make sense to make `regs::rax()` and friends return a `Gpr` directly, and likewise `regs::xmm0()` and friends return an `Xmm` directly? This callsite gets simpler but others maybe gain a `.to_reg()`, so it's not necessarily any less verbose, but it is a bit more typesafe.

**Review by cfallin — APPROVED** [review]
This looks to have been quite tedious -- thanks for this refactor, it will definitely save us from bugs in the future!

One suggestion below but I'm not strongly attached to it, happy to go either way.

File: cranelift/codegen/src/isa/x64/inst/mod.rs (hunk 1 above)
Comment (fitzgen) [reply cranelift/codegen/src/isa/x64/inst/mod.rs:178]: I've avoided pushing the newtypes beyond the ISLE-glue boundary thus far. I think it would make sense to have one more PR (maybe I'll get to it while waiting on reviews for my components PRs) where we push the newtypes to all the `Inst::add`/etc methods and I think pushing that to `regs::rax`/etc in that same PR would make sense.

But I kinda don't want to do all that right now.

Does that sound good?

Comment (cfallin) [reply cranelift/codegen/src/isa/x64/inst/mod.rs:178]: Yep, that's reasonable, any incremental increase in typed-ness is good but no need to block on any part of it!
