### PR TITLE
Remove subtask reparenting

### LINKED ISSUE #12544: Panic juggling subtasks in wasip3
This input:

```wasm
(component

  (component $a
    (core module $m
      (func (export "a") (result i32) i32.const 1) ;; CALLBACK_CODE_YIELD
      (func (export "cb") (param i32 i32 i32) (result i32) i32.const 1) ;; CALLBACK_CODE_YIELD
    )
    (core instance $i (instantiate $m))
    (func (export "f") async
      (canon lift (core func $i "a") async (callback (func $i "cb"))))
  )

  (component $b
    (import "f" (func $f async))
    (core module $m
      (import "" "f" (func $f (result i32)))
      (import "" "cancel" (func $cancel (param i32) (result i32)))
      (global $subtask (mut i32) (i32.const 0))
      (func (export "a")
        (global.set $subtask
          (i32.shr_u
            (call $f)
            (i32.const 4))))
      (func (export "b")
        (drop (call $cancel (global.get $subtask))))
    )
    (core func $f (canon lower (func $f) async))
    (core func $cancel (canon subtask.cancel))
    (core instance $i (instantiate $m
      (with "" (instance
        (export "f" (func $f))
        (export "cancel" (func $cancel))
      ))
    ))
    (func (export "a") async (canon lift (core func $i "a")))
    (func (export "b") async (canon lift (core func $i "b")))
  )

  (instance $a (instantiate $a))
  (instance $b (instantiate $b (with "f" (func $a "f"))))
  (export "a" (func $b "a"))
  (export "b" (func $b "b"))
)

(assert_return (invoke "a"))
(assert_return (invoke "b"))
```

fails with:

```
$ cargo run wast foo.wast -Wcomponent-model-async
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/wasmtime wast foo.wast -Wcomponent-model-async`

thread 'main' (2592575) panicked at crates/wasmtime/src/runtime/component/concurrent.rs:3461:17:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit updates the implementation of component-model-async primitives to remove the manual subtask reparenting process. This is required to fix #12544 at a semantic level because a subtask isn't ever actually reparented, even if its parent exits. The first part of this change is to remove the `GuestTask::subtasks` field and all relevant manipulations of it.

This field, however, powered the `TaskExit` abstraction returned from `call_concurrent`. This commit then subsequently deletes `TaskExit` and all related infrastructure as it's no longer directly applicable as-is. The rest of this change is then updating tests/bindings/etc to account for these two changes.

The main semantic changes related to tests are:

* `wasmtime run`, with and without `--invoke`, no longer waits for all subtasks. This instead only waits for the main task returning before exiting. Whether or not this is the correct behavior is under discussion in WebAssembly/component-model#608

* `wasmtime serve` has been updated to keep the store alive at least until the response body has been fully transmitted. This is also part of WebAssembly/component-model#608.

* Some `component-async-tests`-related tests were updated to either avoid blocking the store as it wasn't needed or yield enough times to ensure that the test passes.

Closes #12544

### CODE REVIEW

**Comment by alexcrichton** [comment]
This is a draft while https://github.com/WebAssembly/component-model/issues/608 is being discussed to figure out the desired behavior here

**Comment by alexcrichton** [comment]
With https://github.com/WebAssembly/component-model/issues/608 closed now the conclusion is that this, as-is, implements the desired semantics of "things aggresively zapped". Given that I think this sould be ready to go, so r? @dicej

File: src/commands/run.rs [hunk 1]
```diff
@@ -671,8 +671,8 @@ impl RunCommand {
                 result = Some(
                     store
                         .run_concurrent(async |store| {
-                            let (result, task) = command.wasi_cli_run().call_run(store).await?;
-                            task.block(store).await;
+                            let result = command.wasi_cli_run().call_run(store).await?;
+                            // TODO: wait on store
```
Comment (dicej) [inline src/commands/run.rs]: Is this still the plan of record, i.e. to wait on the store?

Comment (alexcrichton) [reply src/commands/run.rs]: Oops no, forgot to remove this
