### PR TITLE
Codegen  fix atomic_cas with samll types on riscv64

### LINKED ISSUE #5901: Cranelift: Wrong result for `atomic_cas.i8` on RISC-V
👋 Hey,

Fuzzgen found this overnight

### `.clif` Test Case

```
test interpret
test run
target riscv64gc

function %a(i8) -> i8 sext system_v {
    ss2 = explicit_slot 2

block0(v0: i8):
    v2 = iconst.i16 0x00ff
    v3 = stack_addr.i64 ss2
    store v2, v3

    v4 = stack_addr.i64 ss2+1
    v5 = atomic_cas v4, v0, v0
    return v5
}

; run: %a(0) == 0
```

### Steps to Reproduce

* `clif-util test ./the-above.clif`

### Expected Results

The test to pass

### Actual Results

```
     Running `/home/afonso/git/qemu/qemu-7.2.0/build/qemu-riscv64 -cpu any,zba=true,zbb=true,zbc=true,zbs=true,zbkb=true,zbkc=true,zbkx=true,zknd=true,zkne=true,zknh=true,zksed=true,zksh=true,zkr=true -L /usr/riscv64-linux-gnu -E LD_LIBRARY_PATH=/usr/riscv64-linux-gnu/lib /home/afonso/git/wasmtime/target/riscv64gc-unknown-linux-gnu/debug/clif-util test ./lmao.clif`
 ERROR cranelift_filetests::concurrent > FAIL: run
FAIL ./lmao.clif: run

Caused by:
    Failed test: run: %a(0) == 0, actual: -1
1 tests
Error: 1 failure
```

### Versions and Environment

Cranelift version or commit: main

Operating system: Linux

Architecture: riscv64

### Extra Info

CC: @yuyang-ok

### PR DESCRIPTION
**Pull request by yuyang-ok**
This   fix #5901.
When dealing with samll types,We should `extract` value to `dst` register instead of `t0` register.

### CODE REVIEW

**Comment by yuyang-ok** [comment]
The test failure indicate a `s930x` has a wrong resule too.
I think target `interpreter` and `x86_64` can pass.

**Comment by afonso360** [comment]
Oh that's right, this test is not endianness independent! If you change the `store` to `store little` and the `atomic_cas` to `atomic_cas little` it should start passing on all arches!

<details>
<summary>New Testcase</summary>

```
test interpret
test run
target aarch64
target s390x
target x86_64
target riscv64

function %a(i8) -> i8 sext system_v {
    ss2 = explicit_slot 2

block0(v0: i8):
    v2 = iconst.i16 0x00ff
    v3 = stack_addr.i64 ss2
    store little v2, v3

    v4 = stack_addr.i64 ss2+1
    v5 = atomic_cas little v4, v0, v0
    return v5
}

; run: %a(0) == 0
```

</details>

File: cranelift/codegen/src/isa/riscv64/inst/emit.rs [hunk 1]
```diff
@@ -1275,11 +1275,10 @@ impl MachInstEmit for Inst {
...
-                let origin_value = if ty.bits() < 32 {
-                    AtomicOP::extract(t0, offset, dst.to_reg(), ty)
+                if ty.bits() < 32 {
+                    AtomicOP::extract(dst, offset, dst.to_reg(), ty)
                         .iter()
                         .for_each(|i| i.emit(&[], sink, emit_info, state));
-                    t0.to_reg()
                 } else if ty.bits() == 32 {
                     Inst::Extend {
                         rd: t0,
```
Comment (afonso360) [inline cranelift/codegen/src/isa/riscv64/inst/emit.rs:1284]: Isn't this case now wrong since we are extending into `t0` instead of `dst`?

**Review by afonso360 — COMMENTED** [review]
I think this is correct, as far as I can tell. (Modulo the one comment)

Can you enable the [`atomic-cas-little.clif`](https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/filetests/filetests/runtests/atomic-cas-little.clif) and [`atomic-cas-subword-little.clif`](https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/filetests/filetests/runtests/atomic-cas-subword-little.clif) tests for riscv64?

File: cranelift/codegen/src/isa/riscv64/inst/emit.rs (hunk 1 above)
Comment (yuyang-ok) [reply cranelift/codegen/src/isa/riscv64/inst/emit.rs:1284]: Yes.

**Comment by yuyang-ok** [comment]
@afonso360 Sure.

**Comment by yuyang-ok** [comment]
@afonso360  I think we are ready.

**Comment by afonso360** [comment]
I think we are still missing the fix for the 32 bit case, now that we are no longer using `t0`

**Comment by yuyang-ok** [comment]
@afonso360  Sorry.

**Comment by afonso360** [comment]
LGTM!

**Review by afonso360 — APPROVED** [review]
Oops, need to approve this.
