### PR TITLE
move `ConcurrentState` from `ComponentInstance` to `Store`

### LINKED ISSUE #11226: Support running tasks for all instances in a store concurrently
Currently, if you have a `Store` with multiple component instances, you can only run an event loop (via e.g. `Instance::run_concurrent`) for one of those instances at a time.  We'd like to remove that restriction and allow all the instances to make progress concurrently.

Note that this will require moving some or all of `ConcurrentState` out of `ComponentInstance` and into `Store`.  In fact, `ConcurrentState` originally _did_ live in `Store`; I moved it to `ComponentInstance` when I discovered that `wasmtime-wast` reuses the same store to run multiple instances, which caused issues when one of those instances trapped with unfinished tasks still pending and subsequent instances tried to resume those tasks.  If we move that state back into `Store`, we'll need to take care to avoid such cross-talk (whether due to serial or concurrent use of instances within a single store) by immediately purging any tasks and associated state belonging to a trapped instance.

This change should additionally allow us to move methods like `Instance::{stream,future}` to `Store[ContextMut]` since streams and futures would no longer be instance-specific.  That, in turn, should allow us to remove the `Access[or]::instance` methods since e.g. host functions would no longer need access to the specific instance they're being called from.

### LINKED ISSUE #11249: Generated guest export bindings are insufficient to call concurrent functions
Since https://github.com/bytecodealliance/wasmtime/pull/11238 has been merged, calling an async export requires an `Accessor`, however, the only way to get an `Accessor` is to use an `Instance`.

Users relying uniquely on generated `instantiate_async` bindings do not have access to one and so can never call the async export.

### Steps to Reproduce

- checkout #11221 
- `cargo doc -p wasmtime-wasi --features p3 --open --document-private-items`
- take a look at docs generated for `target/doc/wasmtime_wasi/p3/bindings/struct.Command.html`

Image
Image

### Expected Results

Either a way to run an export without manual instantiation or removal of these bindings

### Actual Results

"dead end" from user's perspective with seemingly no way of constructing an `Accessor` using the public API

### Versions and Environment

Wasmtime version or commit: 326795f583 (latest `main`)

Operating system: MacOS

Architecture: aarch64-darwin

### Extra Info

Without changing `wasmtime` API, there seem to be two ways to fix this issue:
- return a tuple from `instantiate_async` e.g. `(Command, Instance)` (and similar for other worlds)
- simply remove the `instantiate_async` generated functions and require users to always instantiate manually and rely on `Command::new` (and similar for other worlds)

### LINKED ISSUE #11651: `Access::instance` panics
### Test Case

Use `store` option to bindgen without `async` or simply call `instance` on `Access` returned by `Access::new`

### Steps to Reproduce

apply the following diff to #11649 
```diff
diff --git a/crates/wasi-http/src/p3/bindings.rs b/crates/wasi-http/src/p3/bindings.rs
index b7fec724c1..9f2bd8e9cf 100644
--- a/crates/wasi-http/src/p3/bindings.rs
+++ b/crates/wasi-http/src/p3/bindings.rs
@@ -11,8 +11,8 @@ mod generated {
             "wasi:http/types/[drop]response": store | trappable | tracing,
             "wasi:http/types/[method]request.consume-body": async | store | trappable | tracing,
             "wasi:http/types/[method]response.consume-body": async | store | trappable | tracing,
-            "wasi:http/types/[static]request.new": async | store | trappable | tracing,
-            "wasi:http/types/[static]response.new": async | store | trappable | tracing,
+            "wasi:http/types/[static]request.new": store | trappable | tracing,
+            "wasi:http/types/[static]response.new": store | trappable | tracing,
             default: trappable | tracing,
         },
         exports: { default: async | store },
diff --git a/crates/wasi-http/src/p3/host/types.rs b/crates/wasi-http/src/p3/host/types.rs
index 165e4e4e12..3d662da585 100644
--- a/crates/wasi-http/src/p3/host/types.rs
+++ b/crates/wasi-http/src/p3/host/types.rs
@@ -303,45 +303,43 @@ impl HostFields for WasiHttpCtxView<'_> {
 }
 
 impl HostRequestWithStore for WasiHttp {
-    async fn new<T>(
-        store: &Accessor<T, Self>,
+    fn new<T>(
+        mut store: Access<'_, T, Self>,
         headers: Resource<Headers>,
         contents: Option<StreamReader<u8>>,
         trailers: FutureReader<Result<Option<Resource<Trailers>>, ErrorCode>>,
         options: Option<Resource<RequestOptions>>,
     ) -> wasmtime::Result<(Resource<Request>, FutureReader<Result<(), ErrorCode>>)> {
+        let WasiHttpCtxView { table, .. } = store.get();
+        let headers = delete_fields(table, headers)?;
+        let options = options
+            .map(|options| delete_request_options(table, options))
+            .transpose()?;
+        let (result_tx, result_rx) = oneshot::channel();
+        let body = Body::Guest {
+            contents_rx: contents,
+            trailers_rx: trailers,
+            result_tx,
+        };
+        let req = Request {
+            method: http::Method::GET,
+            scheme: None,
+            authority: None,
+            path_with_query: None,
+            headers: headers.into(),
+            options: options.map(Into::into),
+            body,
+        };
+        let req = table.push(req).context("failed to push request to table")?;
         let instance = store.instance();
-        store.with(|mut store| {
-            let (result_tx, result_rx) = oneshot::channel();
-            let WasiHttpCtxView { table, .. } = store.get();
-            let headers = delete_fields(table, headers)?;
-            let options = options
-                .map(|options| delete_request_options(table, options))
-                .transpose()?;
-            let body = Body::Guest {
-                contents_rx: contents,
-                trailers_rx: trailers,
-                result_tx,
-            };
-            let req = Request {
-                method: http::Method::GET,
-                scheme: None,
-                authority: None,
-                path_with_query: None,
-                headers: headers.into(),
-                options: options.map(Into::into),
-                body,
-            };
-            let req = table.push(req).context("failed to push request to table")?;
-            Ok((
-                req,
-                FutureReader::new(
-                    instance,
-                    &mut store,
-                    GuestBodyResultProducer::Receiver(result_rx),
-                ),
-            ))
-        })
+        Ok((
+            req,
+            FutureReader::new(
+                instance,
+                &mut store,
+                GuestBodyResultProducer::Receiver(result_rx),
+            ),
+        ))
     }
 
     async fn consume_body<T>(
@@ -586,39 +584,37 @@ impl HostRequestOptions for WasiHttpCtxView<'_> {
 }
 
 impl HostResponseWithStore for WasiHttp {
-    async fn new<T>(
-        store: &Accessor<T, Self>,
+    fn new<T>(
+        mut store: Access<'_, T, Self>,
         headers: Resource<Headers>,
         contents: Option<StreamReader<u8>>,
         trailers: FutureReader<Result<Option<Resource<Trailers>>, ErrorCode>>,
     ) -> wasmtime::Result<(Resource<Response>, FutureReader<Result<(), ErrorCode>>)> {
+        let WasiHttpCtxView { table, .. } = store.get();
+        let headers = delete_fields(table, headers)?;
+        let (result_tx, result_rx) = oneshot::channel();
+        let body = Body::Guest {
+            contents_rx: contents,
+            trailers_rx: trailers,
+            result_tx,
+        };
+        let res = Response {
+            status: http::StatusCode::OK,
+            headers: headers.into(),
+            body,
+        };
+        let res = table
+            .push(res)
+            .context("failed to push response to table")?;
         let instance = store.instance();
-        store.with(|mut store| {
-            let (result_tx, result_rx) = oneshot::channel();
-            let WasiHttpCtxView { table, .. } = store.get();
-            let headers = delete_fields(table, headers)?;
-            let body = Body::Guest {
-                contents_rx: contents,
-                trailers_rx: trailers,
-                result_tx,
-            };
-            let res = Response {
-                status: http::StatusCode::OK,
-                headers: headers.into(),
-                body,
-            };
-            let res = table
-                .push(res)
-                .context("failed to push response to table")?;
-            Ok((
-                res,
-                FutureReader::new(
-                    instance,
-                    &mut store,
-                    GuestBodyResultProducer::Receiver(result_rx),
-                ),
-            ))
-        })
+        Ok((
+            res,
+            FutureReader::new(
+                instance,
+                &mut store,
+                GuestBodyResultProducer::Receiver(result_rx),
+            ),
+        ))
     }
 
     async fn consume_body<T>(
```

### Expected Results

Success

### Actual Results

```
thread 'p3::p3_http_outbound_request_unsupported_scheme' panicked at /Users/rvolosatovs/src/github.com/bytecodealliance/wasmtime/crates/wasmtime/src/runtime/component/concurrent.rs:255:23:
called `Option::unwrap()` on a `None` value
```

### Extra Info

This was introduced in #11628

cc @alexcrichton

### PR DESCRIPTION
**Pull request by dicej**
This has a few benefits:

- No need to specify an instance when creating or piping from a stream or future.
- No need to track the instance in an `Accessor`.
- You may now execute tasks for multiple instances in a single event loop.

The main drawback is that, if one of several instances within a single store traps, it effectively means all instances have trapped, and the store can't be used to create new instances.  The way to avoid that is to use separate stores for instances which must be isolated from others.

As a result of this change, a lot of code had to move from e.g. `impl Instance` to e.g. `impl StoreOpaque`, so the diff is pretty huge, but the changes themselves are almost entirely non-functional.

Fixes #11226
Fixes #11249
Fixes #11651

### CODE REVIEW

File: crates/wasmtime/src/runtime/component/store.rs [hunk 1]
```diff
@@ -9,7 +9,7 @@ use wasmtime_environ::PrimaryMap;
 
 #[derive(Default)]
 pub struct ComponentStoreData {
-    instances: PrimaryMap<ComponentInstanceId, Option<OwnedComponentInstance>>,
+    pub(crate) instances: PrimaryMap<ComponentInstanceId, Option<OwnedComponentInstance>>,
```
Comment (alexcrichton) [inline crates/wasmtime/src/runtime/component/store.rs]: I'm wary of making this public to the whole crate as it generally makes it harder to maintain abstraction boundaries. Would it be possible to encapsulate whatever's   needed within this file instead?

File: crates/wasmtime/src/runtime/component/func/options.rs [hunk 2]
```diff
@@ -497,19 +502,40 @@ impl<'a> LiftContext<'a> {
...
+                memory,
+                options,
+                types: component.types(),
+                instance,
+                instance_handle,
+                calls,
+                host_table,
+                host_resource_data,
+            }
         }
```
Comment (alexcrichton) [inline crates/wasmtime/src/runtime/component/func/options.rs]: Would it makes sense to have a `concurrent_disabled.rs` which has ZST for `ConcurrentState` with no methods? That would avoid this `#[cfg]` for example and help encapsulate "all the conditional stuff is in this file" too

**Review by alexcrichton — APPROVED** [review]
