### PR TITLE
Remove FPR32; fixes #1303

### LINKED ISSUE #1303: Trampoline error for function with 17 float arguments
Given this input:

```wat
(module
  (func (export "foo")
    (param f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32)
  )
)
```

the current wasmtime CLI will fail with:

```
$ cargo run -- --disable-cache call.wat --invoke foo 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3                                                                                                                                                                           Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/wasmtime --disable-cache call.wat --invoke foo 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3`
warning: using `--invoke` with a function that takes arguments is experimental and may break in the future
Error: failed to run main module `call.wat`

Caused by:
    0: failed to invoke `foo`
    1: trampoline error: Compile(Codegen("function u0:0(i64 vmctx [%rdi], i64 [%rsi], i64 [%rdx], i64 [%rcx]) system_v {\n    ss0 = outgoing_arg 4, offset 0\n    ss1 = outgoing_arg 4, offset 8\n    ss2 = outgoing_arg 4, offset 16\n    ss3 = outgoing_arg 4, offset 24\n    ss4 = outgoing_arg 4, offset 32\n    ss5 = outgoing_arg 4, offset 40\n    ss6 = outgoing_arg 4, offset 48\n    ss7 = outgoing_arg 4, offset 56\n    ss8 = outgoing_arg 4, offset 64\n    sig0 = (i64 vmctx [%rdi], i64 [%rsi], f32 [%xmm0], f32 [%xmm1], f32 [%xmm2], f32 [%xmm3], f32 [%xmm4], f32 [%xmm5], f32 [%xmm6], f32 [%xmm7], f32 [0], f32 [8], f32 [16], f32 [24], f32 [32], f32 [40], f32 [48], f32 [56], f32 [64]) system_v\n\n
         block0(v0: i64 [%rdi], v1: i64 [%rsi], v2: i64 [%rdx], v3: i64 [%rcx]):\n[RexMp2fld#610,%xmm0]               v4 = load.f32 notrap aligned v3\n[RexMp2fldDisp8#610,%xmm1]          v5 = load.f32 notrap aligned v3+16\n[RexMp2fldDisp8#610,%xmm2]          v6 = load.f32 notrap aligned v3+32\n[RexMp2fldDisp8#610,%xmm3]          v7 = load.f32 notrap aligned v3+48\n[RexMp2fldDisp8#610,%xmm4]          v8 = load.f32 notrap aligned v3+64\n[RexMp2fldDisp8#610,%xmm5]          v9 = load.f32 notrap aligned v3+80\n[RexMp2fldDisp8#610,%xmm6]          v10 = load.f32 notrap aligned v3+96\n[RexMp2fldDisp8#610,%xmm7]          v11 = load.f32 notrap aligned v3+112\n[RexMp2fldDisp32#610,%xmm8]         v12 = load.f32 notrap aligned v3+128\n[RexMp2fldDisp32#610,%xmm9]         v13 = load.f32 notrap aligned v3+144\n[RexMp2fldDisp32#610,%xmm10]        v14 = load.f32 notrap aligned v3+160\n[RexMp2fldDisp32#610,%xmm11]        v15 = load.f32 notrap aligned v3+176\n[RexMp2fldDisp32#610,%xmm12]        v16 = load.f32 notrap aligned v3+192\n[RexMp2fldDisp32#610,%xmm13]        v17 = load.f32 notrap aligned v3+208\n[RexMp2fldDisp32#610,%xmm14]        v18 = load.f32 notrap aligned v3+224\n[RexMp2fldDisp32#610,%xmm15]        v19 = load.f32 notrap aligned v3+240\n[RexOp1rmov#8089]                   regmove v3, %rcx -> %rax\n[RexOp2frmov#428]                   regmove v19, %xmm15 -> %xmm16\n[RexMp2fldDisp32#610,%xmm15]        v20 = load.f32 notrap aligned v3+256\n[RexMp2fspillSib32#611,ss0]         v21 = spill v12\n[RexMp2fspillSib32#611,ss1]         v22 = spill v13\n[RexMp2fspillSib32#611,ss2]         v23 = spill v14\n[RexMp2fspillSib32#611,ss3]         v24 = spill v15\n[RexMp2fspillSib32#611,ss4]         v25 = spill v16\n[RexMp2fspillSib32#611,ss5]         v26 = spill v17\n[RexMp2fspillSib32#611,ss6]         v27 = spill v18\n[RexOp2frmov#428]                   regmove v19, %xmm16 -> %xmm8\n;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n; error: inst30: RexOp2frmov#428 constraints not satisfied in: regmove.f32 v19, %xmm16 -> %xmm8\nfunction u0:0(i64 vmctx [%rdi], i64 [%rsi], i64 [%rdx], i64 [%rcx]) system_v {\n    ss0 = outgoing_arg 4, offset 0\n    ss1 = outgoing_arg 4, offset 8\n    ss2 = outgoing_arg 4, offset 16\n    ss3 = outgoing_arg 4, offset 24\n    ss4 = outgoing_arg 4, offset 32\n    ss5 = outgoing_arg 4, offset 40\n    ss6 = outgoing_arg 4, offset 48\n    ss7 = outgoing_arg 4, offset 56\n    ss8 = outgoing_arg 4, offset 64\n    sig0 = (i64 vmctx [%rdi], i64 [%rsi], f32 [%xmm0], f32 [%xmm1], f32 [%xmm2], f32 [%xmm3], f32 [%xmm4], f32 [%xmm5], f32 [%xmm6], f32 [%xmm7], f32 [0], f32 [8], f32 [16], f32 [24], f32 [32], f32 [40], f32 [48], f32 [56], f32 [64]) system_v\n\n                                block0(v0: i64 [%rdi], v1: i64 [%rsi], v2: i64 [%rdx], v3: i64 [%rcx]):\n[RexMp2fld#610,%xmm0]               v4 = load.f32 notrap aligned v3\n[RexMp2fldDisp8#610,%xmm1]          v5 = load.f32 notrap aligned v3+16\n[RexMp2fldDisp8#610,%xmm2]          v6 = load.f32 notrap aligned v3+32\n[RexMp2fldDisp8#610,%xmm3]          v7 = load.f32 notrap aligned v3+48\n[RexMp2fldDisp8#610,%xmm4]          v8 = load.f32 notrap aligned v3+64\n[RexMp2fldDisp8#610,%xmm5]          v9 = load.f32 notrap aligned v3+80\n[RexMp2fldDisp8#610,%xmm6]          v10 = load.f32 notrap aligned v3+96\n[RexMp2fldDisp8#610,%xmm7]          v11 = load.f32 notrap aligned v3+112\n[RexMp2fldDisp32#610,%xmm8]         v12 = load.f32 notrap aligned v3+128\n[RexMp2fldDisp32#610,%xmm9]         v13 = load.f32 notrap aligned v3+144\n[RexMp2fldDisp32#610,%xmm10]        v14 = load.f32 notrap aligned v3+160\n[RexMp2fldDisp32#610,%xmm11]        v15 = load.f32 notrap aligned v3+176\n[RexMp2fldDisp32#610,%xmm12]        v16 = load.f32 notrap aligned v3+192\n[RexMp2fldDisp32#610,%xmm13]        v17 = load.f32 notrap aligned v3+208\n[RexMp2fldDisp32#610,%xmm14]        v18 = load.f32 notrap aligned v3+224\n[RexMp2fldDisp32#610,%xmm15]        v19 = load.f32 notrap aligned v3+240\n[RexOp1rmov#8089]                   regmove v3, %rcx -> %rax\n[RexOp2frmov#428]                   regmove v19, %xmm15 -> %xmm16\n[RexMp2fldDisp32#610,%xmm15]        v20 = load.f32 notrap aligned v3+256\n[RexMp2fspillSib32#611,ss0]         v21 = spill v12\n[RexMp2fspillSib32#611,ss1]         v22 = spill v13\n[RexMp2fspillSib32#611,ss2]         v23 = spill v14\n[RexMp2fspillSib32#611,ss3]         v24 = spill v15\n[RexMp2fspillSib32#611,ss4]         v25 = spill v16\n[RexMp2fspillSib32#611,ss5]         v26 = spill v17\n[RexMp2fspillSib32#611,ss6]         v27 = spill v18\n[RexOp2frmov#428]                   regmove v19, %xmm16 -> %xmm8\n[RexMp2fspillSib32#611,ss7]         v28 = spill v19\n[RexMp2fspillSib32#611,ss8]         v29 = spill v20\n[RexOp1call_r#20ff]                 call_indirect sig0, v2(v0, v1, v4, v5, v6, v7, v8, v9, v10, v11, v21, v22, v23, v24, v25, v26, v27, v28, v29)\n[Op1ret#c3]                         return\n}\n\n\n[RexMp2fspillSib32#611,ss7]         v28 = spill v19\n[RexMp2fspillSib32#611,ss8]         v29 = spill v20\n[RexOp1call_r#20ff]                 call_indirect sig0, v2(v0, v1, v4, v5, v6, v7, v8, v9, v10, v11, v21, v22, v23, v24, v25, v26, v27, v28, v29)\n[Op1ret#c3]                         return\n}\n\n; 1 verifier error detected (see above). Compilation aborted.\n"))
```

Cleaned up a bit this yields:

<details>

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/wasmtime --disable-cache call.wat --invoke foo 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3`
warning: using `--invoke` with a function that takes arguments is experimental and may break in the future
Error: failed to run main module `call.wat`

Caused by:
    0: failed to invoke `foo`
    1: trampoline error: WebAssembly failed to compile
       
       Caused by:
           Compilation error: function u0:0(i64 vmctx [%rdi], i64 [%rsi], i64 [%rdx], i64 [%rcx]) system_v {
               ss0 = outgoing_arg 4, offset 0
               ss1 = outgoing_arg 4, offset 8
               ss2 = outgoing_arg 4, offset 16
               ss3 = outgoing_arg 4, offset 24
               ss4 = outgoing_arg 4, offset 32
               ss5 = outgoing_arg 4, offset 40
               ss6 = outgoing_arg 4, offset 48
               ss7 = outgoing_arg 4, offset 56
               ss8 = outgoing_arg 4, offset 64
               sig0 = (i64 vmctx [%rdi], i64 [%rsi], f32 [%xmm0], f32 [%xmm1], f32 [%xmm2], f32 [%xmm3], f32 [%xmm4], f32 [%xmm5], f32 [%xmm6], f32 [%xmm7], f32 [0], f32 [8], f32 [16], f32 [24], f32 [32], f32 [40], f32 [48], f32 [56], f32 [64]) system_v
           
                                           block0(v0: i64 [%rdi], v1: i64 [%rsi], v2: i64 [%rdx], v3: i64 [%rcx]):
           [RexMp2fld#610,%xmm0]               v4 = load.f32 notrap aligned v3
           [RexMp2fldDisp8#610,%xmm1]          v5 = load.f32 notrap aligned v3+16
           [RexMp2fldDisp8#610,%xmm2]          v6 = load.f32 notrap aligned v3+32
           [RexMp2fldDisp8#610,%xmm3]          v7 = load.f32 notrap aligned v3+48
           [RexMp2fldDisp8#610,%xmm4]          v8 = load.f32 notrap aligned v3+64
           [RexMp2fldDisp8#610,%xmm5]          v9 = load.f32 notrap aligned v3+80
           [RexMp2fldDisp8#610,%xmm6]          v10 = load.f32 notrap aligned v3+96
           [RexMp2fldDisp8#610,%xmm7]          v11 = load.f32 notrap aligned v3+112
           [RexMp2fldDisp32#610,%xmm8]         v12 = load.f32 notrap aligned v3+128
           [RexMp2fldDisp32#610,%xmm9]         v13 = load.f32 notrap aligned v3+144
           [RexMp2fldDisp32#610,%xmm10]        v14 = load.f32 notrap aligned v3+160
           [RexMp2fldDisp32#610,%xmm11]        v15 = load.f32 notrap aligned v3+176
           [RexMp2fldDisp32#610,%xmm12]        v16 = load.f32 notrap aligned v3+192
           [RexMp2fldDisp32#610,%xmm13]        v17 = load.f32 notrap aligned v3+208
           [RexMp2fldDisp32#610,%xmm14]        v18 = load.f32 notrap aligned v3+224
           [RexMp2fldDisp32#610,%xmm15]        v19 = load.f32 notrap aligned v3+240
           [RexOp1rmov#8089]                   regmove v3, %rcx -> %rax
           [RexOp2frmov#428]                   regmove v19, %xmm15 -> %xmm16
           [RexMp2fldDisp32#610,%xmm15]        v20 = load.f32 notrap aligned v3+256
           [RexMp2fspillSib32#611,ss0]         v21 = spill v12
           [RexMp2fspillSib32#611,ss1]         v22 = spill v13
           [RexMp2fspillSib32#611,ss2]         v23 = spill v14
           [RexMp2fspillSib32#611,ss3]         v24 = spill v15
           [RexMp2fspillSib32#611,ss4]         v25 = spill v16
           [RexMp2fspillSib32#611,ss5]         v26 = spill v17
           [RexMp2fspillSib32#611,ss6]         v27 = spill v18
           [RexOp2frmov#428]                   regmove v19, %xmm16 -> %xmm8
           ;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           ; error: inst30: RexOp2frmov#428 constraints not satisfied in: regmove.f32 v19, %xmm16 -> %xmm8
           function u0:0(i64 vmctx [%rdi], i64 [%rsi], i64 [%rdx], i64 [%rcx]) system_v {
               ss0 = outgoing_arg 4, offset 0
               ss1 = outgoing_arg 4, offset 8
               ss2 = outgoing_arg 4, offset 16
               ss3 = outgoing_arg 4, offset 24
               ss4 = outgoing_arg 4, offset 32
               ss5 = outgoing_arg 4, offset 40
               ss6 = outgoing_arg 4, offset 48
               ss7 = outgoing_arg 4, offset 56
               ss8 = outgoing_arg 4, offset 64
               sig0 = (i64 vmctx [%rdi], i64 [%rsi], f32 [%xmm0], f32 [%xmm1], f32 [%xmm2], f32 [%xmm3], f32 [%xmm4], f32 [%xmm5], f32 [%xmm6], f32 [%xmm7], f32 [0], f32 [8], f32 [16], f32 [24], f32 [32], f32 [40], f32 [48], f32 [56], f32 [64]) system_v
           
                                           block0(v0: i64 [%rdi], v1: i64 [%rsi], v2: i64 [%rdx], v3: i64 [%rcx]):
           [RexMp2fld#610,%xmm0]               v4 = load.f32 notrap aligned v3
           [RexMp2fldDisp8#610,%xmm1]          v5 = load.f32 notrap aligned v3+16
           [RexMp2fldDisp8#610,%xmm2]          v6 = load.f32 notrap aligned v3+32
           [RexMp2fldDisp8#610,%xmm3]          v7 = load.f32 notrap aligned v3+48
           [RexMp2fldDisp8#610,%xmm4]          v8 = load.f32 notrap aligned v3+64
           [RexMp2fldDisp8#610,%xmm5]          v9 = load.f32 notrap aligned v3+80
           [RexMp2fldDisp8#610,%xmm6]          v10 = load.f32 notrap aligned v3+96
           [RexMp2fldDisp8#610,%xmm7]          v11 = load.f32 notrap aligned v3+112
           [RexMp2fldDisp32#610,%xmm8]         v12 = load.f32 notrap aligned v3+128
           [RexMp2fldDisp32#610,%xmm9]         v13 = load.f32 notrap aligned v3+144
           [RexMp2fldDisp32#610,%xmm10]        v14 = load.f32 notrap aligned v3+160
           [RexMp2fldDisp32#610,%xmm11]        v15 = load.f32 notrap aligned v3+176
           [RexMp2fldDisp32#610,%xmm12]        v16 = load.f32 notrap aligned v3+192
           [RexMp2fldDisp32#610,%xmm13]        v17 = load.f32 notrap aligned v3+208
           [RexMp2fldDisp32#610,%xmm14]        v18 = load.f32 notrap aligned v3+224
           [RexMp2fldDisp32#610,%xmm15]        v19 = load.f32 notrap aligned v3+240
           [RexOp1rmov#8089]                   regmove v3, %rcx -> %rax
           [RexOp2frmov#428]                   regmove v19, %xmm15 -> %xmm16
           [RexMp2fldDisp32#610,%xmm15]        v20 = load.f32 notrap aligned v3+256
           [RexMp2fspillSib32#611,ss0]         v21 = spill v12
           [RexMp2fspillSib32#611,ss1]         v22 = spill v13
           [RexMp2fspillSib32#611,ss2]         v23 = spill v14
           [RexMp2fspillSib32#611,ss3]         v24 = spill v15
           [RexMp2fspillSib32#611,ss4]         v25 = spill v16
           [RexMp2fspillSib32#611,ss5]         v26 = spill v17
           [RexMp2fspillSib32#611,ss6]         v27 = spill v18
           [RexOp2frmov#428]                   regmove v19, %xmm16 -> %xmm8
           [RexMp2fspillSib32#611,ss7]         v28 = spill v19
           [RexMp2fspillSib32#611,ss8]         v29 = spill v20
           [RexOp1call_r#20ff]                 call_indirect sig0, v2(v0, v1, v4, v5, v6, v7, v8, v9, v10, v11, v21, v22, v23, v24, v25, v26, v27, v28, v29)
           [Op1ret#c3]                         return
           }
           
           
           [RexMp2fspillSib32#611,ss7]         v28 = spill v19
           [RexMp2fspillSib32#611,ss8]         v29 = spill v20
           [RexOp1call_r#20ff]                 call_indirect sig0, v2(v0, v1, v4, v5, v6, v7, v8, v9, v10, v11, v21, v22, v23, v24, v25, v26, v27, v28, v29)
           [Op1ret#c3]                         return
           }
           
           ; 1 verifier error detected (see above). Compilation aborted.
```

</details>

It looks like register allocation or something like that may be dying with so many floats?

### PR DESCRIPTION
**Pull request by abrown**
Until #1306 is resolved (some spilling/regalloc issue with larger FPR register banks), this removes FPR32 support. Only Wasm's `i64x2.mul` was using this register class and that instruction is predicated on AVX512 support; for the time being, that instruction will have to make do with the 16 FPR registers.

### CODE REVIEW

File: cranelift/codegen/meta/src/isa/x86/registers.rs [hunk 1]
```diff
@@ -4,7 +4,7 @@ pub(crate) fn define() -> IsaRegs {
     let mut regs = IsaRegsBuilder::new();
 
     let builder = RegBankBuilder::new("FloatRegs", "xmm")
-        .units(32)
+        .units(16)
```
Comment (bjorn3) [inline cranelift/codegen/meta/src/isa/x86/registers.rs]: FIXME set back to 32 when FPR32 is re-added

**Comment by abrown** [comment]
Yeah, I know! I'll keep looking at #1306 but I wanted to avoid having a bug in master for too long.

File: cranelift/codegen/meta/src/isa/x86/registers.rs (hunk 1 above)
Comment (abrown) [reply cranelift/codegen/meta/src/isa/x86/registers.rs]: I don't think I need to remind myself where to expand the register bank...

**Comment by abrown** [comment]
@alexcrichton, any idea what https://github.com/bytecodealliance/wasmtime/pull/1318/checks?check_run_id=506812657#step:9:4117 means? `thread '<unnamed>' panicked at 'trampoline compilation should not produce external symbol relocs', crates/jit/src/compiler.rs:434:9`

**Comment by alexcrichton** [comment]
Oh dear that sounds like another bug! I haven't run into that, but I can try to dig in.

**Comment by abrown** [comment]
Good thing we have fuzzing...

**Comment by alexcrichton** [comment]
Hm ok, so it looks like that condition may still be necessary. It looks like the trampoline is so big it needs the probestack libcall as a relocation, but we assert trampolines don't need relocations. Mind adding the smaller 17-f32-argument test in and leaving that condition in? That way we should still assert this bug at least is fixed and I can get to the other when I get a chance.

**Comment by abrown** [comment]
Sure, I guess we should open another bug for that specific issue and change the FIXME text to point to that?

**Comment by alexcrichton** [comment]
Sounds good to me!

File: tests/misc_testsuite/export-large-signature.wast [hunk 2]
```diff
@@ -0,0 +1,5 @@
+(module
+  (func (export "many_params")
+    (param f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32)
+  )
+)
```
Comment (abrown) [inline tests/misc_testsuite/export-large-signature.wast]: @alexcrichton, I shouldn't need to assert anything here, right? Wasmtime will still attempt to compile this inside [`module(...)`](https://github.com/bytecodealliance/wasmtime/pull/1318)?

Comment (alexcrichton) [reply tests/misc_testsuite/export-large-signature.wast]: I believe so yeah, but it might be good to double-check by running the tests before this PR as well to make sure this test fails.

**Comment by abrown** [comment]
I think this is failing for the same reason as #1319, some `cc` link error.

**Comment by iximeow** [comment]
Where do you see a `cc` error? I'm seeing
```
git checkout --progress --force ea9bfb97b4eb6b5dca08bc3de09a83de59245601
##[error]fatal: reference is not a tree: ea9bfb97b4eb6b5dca08bc3de09a83de59245601
Removed matchers: 'checkout-git'
##[error]Git checkout failed with exit code: 128
##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.165.2/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
```
in all the logs, which make me wonder if GitHub is feeling okay? How would that commit be missing? But a `cc` error earlier on might result in the repo disappearing?

**Comment by abrown** [comment]
No, you're right... this is different. Hm...

**Comment by abrown** [comment]
Well, I guess the same thing happened on #1319; first I saw a `cc` error and after re-running all of the actions now I see a Git failure...

**Comment by iximeow** [comment]
FWIW I have since seen The `cc` Error: https://github.com/bytecodealliance/wasmtime/runs/507019811 - my intuition is that our build might hit a disk space limit where `cc` fails on writing out artifacts? I'm a bit sensitive to that specific cause from dealing with it locally.
