### PR TITLE
cranelift: Restrict `br_table` to `i32` indices

### LINKED ISSUE #4498: Cranelift: `br_table.i128` not implemented on x86
👋  Hey,

Fuzzgen found this when I added i128 support.

### `.clif` Test Case

```
function %br(f32, i128) -> i32 system_v {
    jt0 = jump_table [block1, block1, block1]

block0(v0: f32, v1: i128):
    br_table v1, block1, jt0
block1:
    v2 = iconst.i32 0
    return v2
}
```

### Steps to Reproduce

* Run `cargo run -- compile -D --set enable_llvm_abi_extensions  --target x86_64 .\the-above.clif`

### Expected Results

The code to compile

### Actual Results

``` 
     Running `C:\Users\Afonso\CLionProjects\wasmtime\target\debug\clif-util.exe compile -D --set enable_llvm_abi_extensions --target x86_64 .\test.clif`
thread 'main' panicked at 'BrTable unimplemented for I128', cranelift\codegen\src\isa\x64\lower.rs:3248:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `C:\Users\Afonso\CLionProjects\wasmtime\target\debug\clif-util.exe compile -D --set enable_llvm_abi_extensions --target x86_64 .\test.clif` (exit code: 101) 
```

### Versions and Environment

Cranelift version or commit: `main`
Operating system: Windows
Architecture: x86_64

cc @abrown @jlb6740

### PR DESCRIPTION
**Pull request by afonso360**
👋 Hey,

In #4498 it was proposed that we should only accept `i32` indices to `br_table`. The rationale for this is that larger types lead the users to a false sense of flexibility (since we don't support jump tables larger than u32's), and narrower types are not well tested paths that would be safer if we removed them.

Fixes #4498
CC: @jameysharp @bjorn3 @cfallin

### CODE REVIEW

File: cranelift/frontend/src/switch.rs [hunk 1]
```diff
@@ -264,21 +264,28 @@ impl Switch {
...
+                        bx.ins()
+                            .icmp_imm(IntCC::UnsignedGreaterThan, discr, u32::MAX as i64);
+                    bx.ins().brnz(bigger_than_u32, otherwise, &[]);
+                    bx.ins().jump(new_block, &[]);
+                    bx.seal_block(new_block);
+                    bx.switch_to_block(new_block);
+
+                    // Cast to i32, as br_table is not implemented for i64/i128
+                    let discr = if bits > 64 {
+                        bx.ins().isplit(discr).0
```
Comment (bjorn3) [inline cranelift/frontend/src/switch.rs:281]: I believe `ireduce` can directly go from i128 to i32.

**Review by jameysharp — APPROVED** [review]
This looks great, and a net reduction of about 100 lines is always nice to see too.

Since I merged #4507, some of the changes to tests conflict with changes on `main`. Could you rebase this?

**Review by cfallin — APPROVED** [review]
Looks good to me too, thanks!
