### PR TITLE
Wasm GC: Fix is-null-or-i31ref checks

### LINKED ISSUE #10171: Incorrect `ref.test` result
```WebAssembly
(module
    (type $appNode 
        (struct (field $left anyref)
                (field $right anyref)))
    
    (type $comb (struct (field $asciiTag i32)))

    (func $prob1 (export "prob1") (param $p (ref null $appNode)) (result i32)
        (local.get $p)
        (struct.get $appNode $left)
        (ref.cast (ref null $appNode))
        (struct.get $appNode $right)
        (ref.test (ref null $comb))
    )

    (func $prob2 (export "prob2") (param $p (ref null $appNode)) (result i32)
        (local.get $p)
        (struct.get $appNode $left)
        (ref.cast (ref null $appNode))
        (struct.get $appNode $left)
        (ref.test (ref null $comb))
    )

    (func $main (export "main") (result i32)
        (struct.new $appNode (struct.new $appNode (struct.new $comb (i32.const 67))
                                                  (struct.new $comb (i32.const 73)))
                             (ref.i31 (i32.const 2)))
        (call $prob2)                             
    )
)
```
Hey Wasmtime team! `call`ing `$prob1` returns 1 but `$prob2` returns 0. Why is that? Shouldn't it be reading the `(struct.new $comb (i32.const 67))` which indeed is a `comb`? I've tried reading the GC spec but haven't been able to figure out why the runtime behaves this way.

### PR DESCRIPTION
**Pull request by fitzgen**
In the case where we need to check for either null or i31refs, we were attempting to fold the two checks together with a bitwise-and and a bitmask, but that was incorrect and buggy. We need to actually do the two separate checks and bitwise-or them together.

Fixes #10171

### CODE REVIEW

File: crates/environ/src/gc.rs [hunk 1]
```diff
@@ -25,10 +25,6 @@ use core::alloc::Layout;
 /// Discriminant to check whether GC reference is an `i31ref` or not.
 pub const I31_DISCRIMINANT: u64 = 1;
```
Comment (alexcrichton) [inline crates/environ/src/gc.rs:26]: Curiosity: why is this typed `u64`? This discriminant is technically only for 32-bit values right?

**Review by alexcrichton — APPROVED** [review]

File: crates/environ/src/gc.rs (hunk 1 above)
Comment (fitzgen) [reply crates/environ/src/gc.rs:26]: I think it was useful at some point but might not be useful anymore, I’d have to look at uses again

Comment (fitzgen-f5) [reply crates/environ/src/gc.rs:26]: Looks like there's no issue changing it to a u32, so I'll do that in a follow up
