### PR TITLE
Don't check for null in `call_indirect` and `call_ref`

### LINKED ISSUE #5291: Remove null-check in generated code for `call_indirect` (and `call_ref` soon)
Currently when translating the `call_indirect` instruction Wasmtime will [insert a null-check](https://github.com/bytecodealliance/wasmtime/blob/56daa8a199ab9a79b6404c5a9cd551497594f31b/crates/cranelift/src/func_environ.rs#L1551-L1554) to ensure that we're not calling a null function pointer. Because our representation of a null function pointer is literally a null pointer, however, I think we can actually skip this check entirely due to the [next instruction](https://github.com/bytecodealliance/wasmtime/blob/56daa8a199ab9a79b6404c5a9cd551497594f31b/crates/cranelift/src/func_environ.rs#L1556-L1563) being guaranteed to segfault if it's actually a null pointer.

I don't think this is necessarily as easy as simply removing the null pointer check, however, since I think the `load` needs to at least somehow be annotated with the proper trap code and probably "this can segfault", which I'm not precisely sure how to do. This could be a nice way to clean up the generated code for `call_indirect` slightly thought which is already somewhat large I believe.

### PR DESCRIPTION
**Pull request by alexcrichton**
This PR is an implementation of #5291 to slightly optimize the lowering of `call_indirect` and `call_ref` in Wasmtime. Explicitly checks for null function pointers are no longer present and instead we let a segfault happen when loading from a null function pointer. This segfault is caught and the relevant instruction is annotated with the appropriate trap code.

This support first starts by refactoring the `MemFlags` API to no longer purely be flags but instead be a mixture of flags and "flag regions". The `vmctx`/`heap`/`table` alias regions are bundled into two bits now and the various trap-related bits are now bundled into four bits. This enables putting arbitrary trap codes in a `MemFlags` so long as they aren't `TrapCode::User(_)`.

Closes #5291

### CODE REVIEW

File: cranelift/codegen/src/ir/memflags.rs [hunk 1]
```diff
@@ -75,6 +69,8 @@ pub enum Endianness {
 #[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
 #[cfg_attr(feature = "enable-serde", derive(Serialize, Deserialize))]
 pub struct MemFlags {
+    // Initialized to all zeros to have all flags have their default value.
+    // This is the interpreted through various methods below.
```
Comment (cfallin) [inline cranelift/codegen/src/ir/memflags.rs:73]: s/the interpreted/interpreted/

**Review by cfallin — APPROVED** [review]
LGTM, nice!

File: cranelift/codegen/src/ir/memflags.rs [hunk 2]
```diff
@@ -326,32 +300,106 @@ impl MemFlags {
...
-        if self.notrap() {
-            None
-        } else if self.tabletrap() {
-            Some(TrapCode::TableOutOfBounds)
-        } else {
-            Some(TrapCode::HeapOutOfBounds)
+        match (self.bits & MASK_TRAP_CODE) >> TRAP_CODE_OFFSET {
+            0b0000 => Some(TrapCode::HeapOutOfBounds), // default mode
+            0b0001 => Some(TrapCode::StackOverflow),
+            0b0010 => Some(TrapCode::HeapOutOfBounds),
```
Comment (jameysharp) [inline cranelift/codegen/src/ir/memflags.rs:313]: I'm inclined to think that we don't need to track whether `heap_oob` was set explicitly or just used as a default, so my instinct is to use just one encoding for it. I could easily be talked into the approach you've taken here, but I think it at least needs a bit more of a comment explaining why it appears twice here, and why the zero case doesn't appear in `with_trap_code` below.

**Review by jameysharp — COMMENTED** [review]
I would kind of prefer to land the `MemFlags` changes separately from the "don't explicitly check for null function pointers" changes, if that's not too much trouble to split up. The commit history here is almost right for doing that with a quick rebase but I think only part of the "Trim the MemFlags API" commit applies.

I'm interested in whether you or Chris or anyone else have opinions on the other comments I've left below too.

**Comment by alexcrichton** [comment]
> prefer to land the MemFlags changes separately

[Certainly!](https://github.com/bytecodealliance/wasmtime/pull/8162)

File: crates/cranelift/src/func_environ.rs [hunk 3]
```diff
@@ -1215,19 +1217,9 @@ impl<'a, 'func, 'module_env> Call<'a, 'func, 'module_env> {
...
         args: &[ir::Value],
     ) -> WasmResult<ir::Inst> {
-        // Check for whether the callee is null, and trap if so.
-        //
-        // FIXME: the wasm type system tracks enough information to know whether
-        // `callee` is a null reference or not. In some situations it can be
-        // statically known here that `callee` cannot be null in which case this
-        // null check can be elided. This requires feeding type information from
-        // wasmparser's validator into this function, however, which is not
-        // easily done at this time.
```
[the remark this answers is not in the document]
Comment (alexcrichton) [reply crates/cranelift/src/func_environ.rs:1225]: Good point, I'll be sure to add this back in when rebasing

File: cranelift/codegen/src/ir/memflags.rs (hunk 2 above)
Comment (alexcrichton) [reply cranelift/codegen/src/ir/memflags.rs:313]: Nah I think that makes the most sense in retrospect too, no need to be needlessly complicated.

File: crates/wasmtime/src/runtime/store.rs [hunk 4]
```diff
@@ -1595,10 +1595,19 @@ impl StoreOpaque {
...
-        if addr == 0 {
+        // There are a few instances where a "close to zero" pointer is loaded
+        // and we expect that to happen:
+        //
+        // * Explicitly bounds-checked memories with spectre-guards enabled will
+        //   cause out-of-bounds accesses to get routed to address 0, so allow
+        //   wasm instructions to fault on the null address.
+        // * `call_indirect` when invoking a null function pointer may load data
+        //   from the a `VMFuncRef` whose address is null, meaning any field of
+        //   `VMFuncRef` could be the address of the fault.
```
Comment (fitzgen) [inline crates/wasmtime/src/runtime/store.rs:1606]: We should have a test somewhere, maybe here, that `mem::size_of<VMFuncRef>() < PAGE_SIZE`, since we should only rely on the presence of a single null guard page.

**Comment by alexcrichton** [comment]
Updated and rebased!
