### PR TITLE
mpk: reenable MPK support with vendor string check

### LINKED ISSUE #7445: mpk: some GitHub CI runners have MPK enabled but fail to run MPK code
GitHub CI runners are showing some strange behavior: on certain runners (unknown which ones), the CPUID bits claim that MPK is supported, but running any MPK code (e.g., `RDPKRU`) causes a `SIGILL` crash. #7446 disables MPK until this is resolved.

Some instances of this failure:
- https://github.com/bytecodealliance/wasmtime/actions/runs/6721387888/job/18267026371#step:15:3283
- https://github.com/bytecodealliance/wasmtime/actions/runs/6714337681/job/18247418366?pr=7335#step:15:3280

### PR DESCRIPTION
**Pull request by abrown**
In #7446 I disabled MPK support temporarily due to failures in CI runs. Looking into this further in #7445, I discovered that it is due to how `has_cpuid_bit_set` works on different x86 machines: Intel's `CPUID` instruction reports support for MPK in a certain leaf bit, AMD does it some other (unknown?) way. The CI problem boiled down to occasional runs on AMD machines that would fail with `SIGILL` because the AMD machine reported that it had MPK support when it really did not. This change fixes the issue by first checking if the CPU vendor string is `GenuineIntel` before inspecting the MPK `CPUID` leaf bit.

Closes #7445.

### CODE REVIEW

File: crates/runtime/src/mpk/pkru.rs [hunk 1]
```diff
@@ -53,16 +53,24 @@ pub fn write(pkru: u32) {
...
+}
+
+/// Check the `CPUID` vendor string for `GenuineIntel`; see the Intel Software
+/// Development Manual, vol 2a, `CPUID` description.
+pub fn is_intel_cpu() -> bool {
+    // To read the CPU vendor string, we pass 0 in EAX and read 12 ASCII bytes
+    // from EBX, EDX, and ECX (in that order).
+    let result = unsafe { std::arch::x86_64::__cpuid(0) };
+    // Then we check if the string matches "GenuineIntel".
+    result.ebx == 0x756e6547 /* "Genu" */
```
Comment (alexcrichton) [inline crates/runtime/src/mpk/pkru.rs:71]: If you want to be super fancy this can be replaced with `u32::from_le_bytes(*b"Genu")`

**Review by alexcrichton — APPROVED** [review]

File: crates/runtime/src/mpk/pkru.rs (hunk 1 above)
Comment (abrown) [reply crates/runtime/src/mpk/pkru.rs:71]: I like it... self-documenting code.
