### PR TITLE
x64: Ensure that constants are always 16 bytes for XmmMem

### LINKED ISSUE #4761: cranelift-fuzzgen fuzzbug: "Segv on unknown address in cranelift_filetests::function_runner::CompiledFunction::call::ha6b9162cd2e"
https://oss-fuzz.com/testcase-detail/4896860279537664

```
ERROR: AddressSanitizer: SEGV on unknown address (pc 0x6250000014d5 bp 0x7fff30133db0 sp 0x7fff30133ad0 T0)
--
  | ==743==The signal is caused by a READ memory access.
  | ==743==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
  | SCARINESS: 20 (wild-addr-read)
  | #0 0x6250000014d5  (<unknown module>)
  | #1 0x62500000175d  (<unknown module>)
  | #0 0x5579a6d0c6c4 in cranelift_filetests::function_runner::CompiledFunction::call::ha6b9162cd2e21784 wasmtime/cranelift/filetests/src/function_runner.rs:183:9
```

input:

```
IFWoAAAAAE0AAABSSUl9LCB7eAx6ZcYNR9T0RvCdMjI0MjaWMgAAAAA7ACypAH19f319fX0AAAA7
JAABqQB9fX19fX19fX0IAAAAAAAAAQAAwyvDw8PDAADJ/zw8PEHDw8MAAGUBb/PGANpGAAAAAAAj
OwAsqW9vb29vb28AfX19fX19fQAAADskAAGpAH19fX19fX19fQ7/////////CAAAAAAAAAEAAMMr
w8PDwwAAyf88PDxBw8PDAABlAW/zxgDaRgAAAAAAAAAAAAAAAACTgoL/////////MAAAAAAAAAUA
AAAACIKCgoKCgkEAgoKCgoJNAAAAgoKCgoKCgoKCgoKCwoKCgoKCgoKSioIEAAcAgoKCgoKCgoKC
goKCgoKCGIKC//8wAAAAAAAABQAAAAAIgoKCgoKCQQCCgoKCgk0AAACCgoKCgoKCgoKCgoLCeoKC
eYKCgpKKggQAAACCgoKCgoKCgoKCgoKCgoIYgoKCgoKCgoKCgoKCFACCgjOCgoKCgoL/////goKC
goKCgoKCgoKCgoJBAUFB
```

cc @afonso360

### PR DESCRIPTION
**Pull request by elliottt**
Ensure that constants generated for the memory case of XmmMem values are always 16 bytes, ensuring that we don't accidantally perform an unaligned load.

Fixes #4761

### CODE REVIEW

File: cranelift/codegen/src/isa/x64/lower/isle.rs [hunk 1]
```diff
@@ -133,6 +133,62 @@ impl Context for IsleContext<'_, '_, MInst, Flags, IsaFlags, 6> {
...
 
+    fn put_in_xmm_mem_imm(&mut self, val: Value) -> XmmMemImm {
+        let inputs = self.lower_ctx.get_value_as_source_or_const(val);
+
+        if let Some(c) = inputs.constant {
+            if let Some(imm) = to_simm32(c as i64) {
+                return XmmMemImm::new(imm.to_reg_mem_imm()).unwrap();
+            }
+
+            // A load from the constant pool is better than a rematerialization into a register,
```
Comment (cfallin) [inline cranelift/codegen/src/isa/x64/lower/isle.rs:144]: Can we delegate to `put_in_xmm_mem` at this point to share logic (then lift the `XmmMem` back to `XmmMemImm`)?

File: cranelift/codegen/src/machinst/isle.rs [hunk 2]
```diff
@@ -804,6 +804,18 @@ macro_rules! isle_prelude_methods {
             self.lower_ctx.use_constant(data)
         }
 
+        #[inline]
+        fn emit_u128_le_const(&mut self, lower: u64, upper: u64) -> VCodeConstant {
```
Comment (cfallin) [inline cranelift/codegen/src/machinst/isle.rs:808]: We can probably use a `u128` here to avoid the awkward iter-chaining below? Then we can do a zero-extend cast when calling this rather than giving `0` as `upper`.

**Review by cfallin — APPROVED** [review]
Thanks!

File: cranelift/codegen/src/machinst/isle.rs [hunk 3]
```diff
@@ -804,6 +804,18 @@ macro_rules! isle_prelude_methods {
...
+            let bytes = lower
+                .to_le_bytes()
+                .iter()
+                .chain(upper.to_le_bytes().iter())
+                .cloned()
```
Comment (jameysharp) [inline cranelift/codegen/src/machinst/isle.rs:813]: Absolutely unimportant nit: I like to use `copied` instead of `cloned` when I'm expecting it to be cheap, so the compiler can tell me if I've tried to do it to a type that isn't `Copy`.

File: cranelift/filetests/filetests/runtests/x64-xmm-mem-align-bug.clif [hunk 4]
```diff
@@ -0,0 +1,17 @@
+test run
+set enable_llvm_abi_extensions
+target x86_64
```
Comment (jameysharp) [inline cranelift/filetests/filetests/runtests/x64-xmm-mem-align-bug.clif:3]: Should we just run this on all architectures as well as the interpreter? The bug was x64-specific but the test should work everywhere and it would be nice to know if it didn't.

File: cranelift/codegen/src/isa/x64/lower/isle.rs [hunk 5]
```diff
@@ -133,6 +133,62 @@ impl Context for IsleContext<'_, '_, MInst, Flags, IsaFlags, 6> {
...
+            // because it reduces register pressure.
+            //
+            // NOTE: this is where behavior differs from `put_in_reg_mem`, as we always force
```
Comment (jameysharp) [inline cranelift/codegen/src/isa/x64/lower/isle.rs:147]: Should this comment say "put_in_reg_mem_imm"?

Comment (elliottt) [reply cranelift/codegen/src/isa/x64/lower/isle.rs]: Fixed this by delegating to a different function here :)

File: cranelift/codegen/src/machinst/isle.rs [hunk 6]
```diff
@@ -806,7 +806,7 @@ macro_rules! isle_prelude_methods {
 
         #[inline]
         fn emit_u128_le_const(&mut self, value: u128) -> VCodeConstant {
-            let data = VCodeConstantData::Generated(value.to_le_bytes().iter().cloned().collect());
+            let data = VCodeConstantData::Generated(value.to_le_bytes().iter().copied().collect());
```
Comment (jameysharp) [inline cranelift/codegen/src/machinst/isle.rs:809]: Oh, after Chris' suggestion, now you can simplify this to `value.to_le_bytes().into()`, I think.

Comment (jameysharp) [reply cranelift/codegen/src/machinst/isle.rs:809]: I guess `ConstantData` doesn't have a `From` implementation for arrays, but `.as_slice().into()` ought to work at least.

File: cranelift/codegen/src/isa/x64/lower/isle.rs (hunk 5 above)
Comment (jameysharp) [reply cranelift/codegen/src/isa/x64/lower/isle.rs]: Yeah, delegating to a different function worked out very nicely!

File: cranelift/codegen/src/machinst/isle.rs (hunk 6 above)
Comment (elliottt) [reply cranelift/codegen/src/machinst/isle.rs:809]: Looks like we're stuck with my verbose monstrosity:
```
809 |             let data = VCodeConstantData::Generated(value.to_le_bytes().iter().into());
    |                                                                                ^^^^ the trait `From<core::slice::Iter<'_, u8>>` is not implemented for `ConstantData`
```

Comment (jameysharp) [reply cranelift/codegen/src/machinst/isle.rs:809]: The problem there is the `.iter()`.

Comment (elliottt) [reply cranelift/codegen/src/machinst/isle.rs:809]: Yeah, I get a similar error without it. I had been experimenting :)
```
809 |             let data = VCodeConstantData::Generated(value.to_le_bytes().into());
    |                                                                         ^^^^ the trait `From<[u8; 16]>` is not implemented for `ConstantData`
```

Comment (jameysharp) [reply cranelift/codegen/src/machinst/isle.rs:809]: I'd figured out that just `.into()` wouldn't work after I posted my first comment. Did you try my second suggestion, of `.as_slice().into()`?

**Review by cfallin — APPROVED** [review]

File: cranelift/codegen/src/machinst/isle.rs (hunk 6 above)
Comment (jameysharp) [reply cranelift/codegen/src/machinst/isle.rs]: Hooray! It'd probably be nice if `ConstantData` actually had a `From<[T; n]>` implementation too, but I didn't want to suggest doing that in this PR. :sweat_smile:

File: cranelift/filetests/filetests/runtests/x64-xmm-mem-align-bug.clif (hunk 4 above)
Comment (afonso360) [reply cranelift/filetests/filetests/runtests/x64-xmm-mem-align-bug.clif:3]: As a further suggestion, we can also remove the `set enable_llvm_abi_extensions` since we no longer have `i128`'s in this new minimized test case.
