### PR TITLE
Correct the files' directory index when downgrading DWARF5 -> 4

### LINKED ISSUE #1988: DWARF-5 line section directories wrongly translated
For a DWARF-5 equipped `.wasm` file, translated to `.o` (via `wasmtime wasm2obj -g`) the containing directories are mixed up:
- from
```
.debug_line contents:
debug_line[0x00000000]
Line table prologue:
    total_length: 0x000288fa
         version: 5
...
include_directories[  0] = "."
include_directories[  1] = "<moc-asset>"
include_directories[  2] = "tests/debug/testsuite"
file_names[  0]:
           name: "fib-wasm.mo"
      dir_index: 2
file_names[  1]:
```
- to:
```
.debug_line contents:
debug_line[0x00000000]
Line table prologue:
    total_length: 0x0000e747
         version: 4
...
include_directories[  1] = "."
include_directories[  2] = "<moc-asset>"
include_directories[  3] = "tests/debug/testsuite"
file_names[  1]:
           name: "fib-wasm.mo"
      dir_index: 2
```
Since the latter is one-based, the index must be incremented.

(I'm working on a PR.)

### PR DESCRIPTION
**Pull request by ggreif**
Fixes #1988.

### CODE REVIEW

File: crates/debug/src/transform/line_program.rs [hunk 1]
```diff
@@ -121,8 +121,11 @@ where
             dirs.push(dir_id);
         }
         let mut files = Vec::new();
+	// since we are outputting DWARF-4, perform base change
```
Comment (bjorn3) [inline crates/debug/src/transform/line_program.rs:124]:
```suggestion
        // since we are outputting DWARF-4, perform base change
```

File: crates/debug/src/transform/line_program.rs [hunk 2]
```diff
@@ -121,8 +121,11 @@ where
...
+        let directory_index_correction = if header.version() >= 5 { 1 } else { 0 };
         for file_entry in header.file_names() {
-            let dir_id = dirs[file_entry.directory_index() as usize];
+	    let dir_index = file_entry.directory_index() + directory_index_correction;
```
Comment (bjorn3) [inline crates/debug/src/transform/line_program.rs:127]:
```suggestion
            let dir_index = file_entry.directory_index() + directory_index_correction;
```

**Comment by ggreif** [comment]
Eliminated tabs.

File: crates/debug/src/transform/line_program.rs [hunk 3]
```diff
@@ -121,8 +121,11 @@ where
             dirs.push(dir_id);
         }
         let mut files = Vec::new();
+        // since we are outputting DWARF-4, perform base change
+        let directory_index_correction = if header.version() >= 5 { 1 } else { 0 };
```
Comment (yurydelendik) [inline crates/debug/src/transform/line_program.rs:125]: Based on the comment above, the `directory_index_base` is a better name.

nit: can you also make the comment as a sentence: capitalize the "S" and add the period?

Comment (ggreif) [reply crates/debug/src/transform/line_program.rs:125]: I was hesitant naming it `_base`, because we have two index bases here. Output has base `1` and input can have base `0` or `1`.

File: crates/debug/src/transform/line_program.rs [hunk 4]
```diff
@@ -121,8 +121,11 @@ where
             dirs.push(dir_id);
         }
         let mut files = Vec::new();
+        // since we are outputting DWARF-4, perform base change
```
Comment (ggreif) [inline crates/debug/src/transform/line_program.rs:124]:
```suggestion
        // Since we are outputting DWARF-4, perform base change.
```

**Comment by yurydelendik** [comment]
Thank you for the patch.
