### PR TITLE
Fix validating wasm stores of boolean vector results

### LINKED ISSUE #3099: Cranelift verifier errors on v128.store codegen with b8x16 input
Given this input:

```wasm
(module
  (memory 0)
  (func (param v128 i32)
    local.get 1
    local.get 0
    local.get 0
    i8x16.eq
    v128.store)
)
```

wasmtime yields:

```
$ wasmtime bar.wat --enable-simd --enable-cranelift-debug-verifier
Error: failed to run main module `bar.wat`

Caused by:
    0: WebAssembly failed to compile
    1: Compilation error: function u0:0(i64 vmctx, i64, i8x16, i32) fast {
           gv0 = vmctx
           gv1 = load.i64 notrap aligned readonly gv0
           gv2 = load.i64 notrap aligned gv1
           gv3 = vmctx
           gv4 = load.i64 notrap aligned readonly gv3+36
           heap0 = static gv4, min 0, bound 0x0001_0000_0000, offset_guard 0x8000_0000, index_type i32
           stack_limit = gv2

                                       block0(v0: i64, v1: i64, v2: i8x16, v3: i32):
       @0024                               v4 = icmp eq v2, v2
       @0026                               v5 = heap_addr.i64 heap0, v3, 1
       @0026                               store little v4, v5
       ;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       ; error: inst2 (store.b8x16 little v4, v5): has an invalid controlling type b8x16

       @002a                               jump block1

                                       block1:
       @002a                               return
       }

       ; 1 verifier error detected (see above). Compilation aborted.
```

### PR DESCRIPTION
**Pull request by alexcrichton**
Previously cranelift's wasm code generator would emit a raw `store`
instruction for all wasm types, regardless of what the cranelift operand
type was. Cranelift's `store` instruction, however, isn't valid for
boolean vector types. This commit fixes this issue by inserting a
bitcast specifically for the store instruction if a boolean vector type
is being stored, continuing to avoid the bitcast for all other vector types.

Closes #3099

### CODE REVIEW

**Review by abrown — APPROVED** [review]
Nice! You beat me to it...

File: cranelift/wasm/src/code_translator.rs [hunk 1]
```diff
@@ -2407,8 +2407,16 @@ fn translate_store<FE: FuncEnvironment + ?Sized>(
...
-    let val = state.pop1();
-    let val_ty = builder.func.dfg.value_type(val);
+    let mut val = state.pop1();
+    let mut val_ty = builder.func.dfg.value_type(val);
+
+    // Boolean-vector types don't validate with a `store` instruction, so
+    // bitcast them to a vector type which is compatible with the store
+    // instruction.
+    if val_ty.is_vector() && val_ty.lane_type().is_bool() {
+        val = builder.ins().raw_bitcast(I8X16, val);
```
Comment (bjorn3) [inline cranelift/wasm/src/code_translator.rs:2417]: Should we instead define that boolean vectors can be stored using `store` directly and are stored as all-zero or all-one lanes?

Comment (abrown) [reply cranelift/wasm/src/code_translator.rs:2417]: That is a good approach but I don't mind what @alexcrichton tried here because:
 - vector translation already involves a lot of bitcasting so this doesn't make the problem worse; if we want to solve the bitcasting we should just solve all of and close #1147
 - changing `load` and `store` to allow boolean vectors but not boolean scalars seems like it might cause errors somewhere; this fix would immediately fix a fuzz bug
 - I wouldn't mind settling the general issue about `load`s and `store`s with booleans once for all: I've seen mention recently of setting a memory representation for boolean scalars... If we settle it once for all (do we have an issue for this?) and document it then it might make sense to avoid the bitcast (if that's what is decided).

Comment (cfallin) [reply cranelift/wasm/src/code_translator.rs:2417]: I just created #3205 for this. Agreed that for now, the immediate fuzzbug fix is fine.

**Comment by alexcrichton** [comment]
@abrown oh I don't want to step on any toes, I was mostly just curious myself to see how involved this might be (turns out not much)

File: cranelift/wasm/src/code_translator.rs (hunk 1 above)
Comment (alexcrichton) [reply cranelift/wasm/src/code_translator.rs:2417]: Ok I'm gonna go ahead and merge this fix for now and defer to #3205 for future updates.
