### PR TITLE
Cranelift: disallow marking entry block 'cold'.

### LINKED ISSUE #4656: Cranelift: Misscompilation when entry block is cold
👋 Hey,

The clif fuzzer found this in #4654.

### `.clif` Test Case

```
test interpret
test run
set enable_llvm_abi_extensions=true
target x86_64
target aarch64
target s390x

function %a(i8, i16, i8) -> b1 {
block0(v0: i8, v1: i16, v2: i8) cold:
    v3 = bconst.b1 false
    v12 -> v3
    v4 = bconst.b1 false
    v5 = bconst.b1 false
    v6 = iconst.i8 0
    v7 = iconst.i128 0
    v8 = iconst.i64 0
    v9 = iconst.i32 0
    v10 = iconst.i16 0
    v11 = iconst.i8 0
    br_icmp eq v1, v1, block1
    jump block1

block1:
    return v12
}
; run: %a(-83, 1536, 0) == false
; run: %a(0, 0, 0) == false
```

### Steps to Reproduce

* `clif-util test ./the-above.clif`

### Expected Results

All tests should return `false`.

### Actual Results

The run tests return `true` for the first input:

```
     Running `C:\Users\Afonso\CLionProjects\wasmtime\target\debug\clif-util.exe test .\lmao.clif`
 ERROR cranelift_filetests::concurrent > FAIL: run
FAIL .\lmao.clif: run

Caused by:
    Failed test: run: %a(-83, 1536, 0) == false, actual: true
1 tests
Error: 1 failure
```

### Versions and Environment

Cranelift version or commit: `main`
Operating system: Windows (or Linux since the fuzzer found this)
Architecture: `x86_64`

### Extra info

Disassembly of generated code:
```
cargo run -- compile --target x86_64 -D .\lmao.clif

Disassembly of 25 bytes:
   0:   31 c0                   xor     eax, eax
   2:   48 89 ec                mov     rsp, rbp
   5:   5d                      pop     rbp
   6:   c3                      ret
   7:   55                      push    rbp
   8:   48 89 e5                mov     rbp, rsp
   b:   66 39 d2                cmp     dx, dx
   e:   0f 84 ec ff ff ff       je      0
  14:   e9 e7 ff ff ff          jmp     0
```

cc: @cfallin
cc: @mchesser (not sure if you are interested in this issue or not! Feel free to ignore if not)

### PR DESCRIPTION
**Pull request by cfallin**
This is a nonsensical constraint: the entry block must come first in the
compiled code's layout, so it cannot also be sunk to the end of the
function.

This PR modifies the CLIF verifier to disallow this situation entirely.
It also adds an assert during final block-order computation to catch the
problem (and avoid a silent miscompile) even if the verifier is
disabled.

Fixes #4656.

### CODE REVIEW

File: cranelift/codegen/src/machinst/blockorder.rs [hunk 1]
```diff
@@ -376,19 +381,20 @@ impl BlockLoweringOrder {
...
-                this: block,
-                succs: range,
-                cur_succ: range.1,
-            });
-        }
+
+        // Add the entry block.
+        //
+        // FIXME(cfallin): we might be able to use OrigAndEdge. Find a
+        // way to not special-case the entry block here.
```
Comment (elliottt) [inline cranelift/codegen/src/machinst/blockorder.rs:388]: Is it worth extracting an issue for this?

**Review by elliottt — APPROVED** [review]
Seems reasonable to me!

File: cranelift/codegen/src/machinst/blockorder.rs (hunk 1 above)
Comment (cfallin) [reply cranelift/codegen/src/machinst/blockorder.rs:388]: This was pre-existing (I un-indented the block containing this comment) but IMHO it's a pretty tiny micro-optimization thought, probably not worth lifting out into an issue. Happy to just remove the comment if you'd prefer :-)

**Comment by bjorn3** [comment]
> This is a nonsensical constraint: the entry block must come first in the
> compiled code's layout, so it cannot also be sunk to the end of the
> function.

If you want to mark all blocks calling a cold function as cold, you did have to special case the entry block if the entry block isn't allowed to be cold. cg_clif just barely avoids this issue as the first codegened MIR basic block corresponds to the second Cranelift basic block as the entry block only handles storing arguments in the right location.

File: cranelift/codegen/src/machinst/blockorder.rs (hunk 1 above)
Comment (elliottt) [reply cranelift/codegen/src/machinst/blockorder.rs:388]: Seems pretty reasonable to leave it, then :+1:

**Comment by cfallin** [comment]
That's a fair point, but it still seems like a reasonable thing for a producer to have to ensure, IMHO; the only way it could be valid would be if the entire function body is marked cold, and that doesn't make sense (cold compared to what?).
