### PR TITLE
[fuzz] Fix order of arguments passed in to `wasm-spec-interpreter`

### LINKED ISSUE #4671: fuzz: different results for `shr_s`
### Test Case

```wat
(module
  (type (;0;) (func (param i32 i32) (result i32)))
  (func (;0;) (type 0) (param i32 i32) (result i32)
    local.get 0
    local.get 1
    i32.shr_s
  )
  (export "test" (func 0))
)
```

Also see attached files (annoyingly renamed with `.txt` appended due to GitHub upload restrictions):
- [crash-3be2c01861adcd71b08427e6ad1251de6fb3159b.txt](https://github.com/bytecodealliance/wasmtime/files/9299908/crash-3be2c01861adcd71b08427e6ad1251de6fb3159b.txt)
- [testcase169.wat.txt](https://github.com/bytecodealliance/wasmtime/files/9299909/testcase169.wat.txt)
- [testcase169.wasm.txt](https://github.com/bytecodealliance/wasmtime/files/9299910/testcase169.wasm.txt)

### Steps to Reproduce

On the `abrown:meta-diff` branch:

```console
$ RUST_LOG=wasmtime_fuzzing=debug cargo +nightly fuzz run differential-new fuzz/artifacts/differential-new/crash-3be2c01861adcd71b08427e6ad1251de6fb3159b
```

### Expected Results

Execution to match for both the Wasmtime and `wasm-spec-interpreter` run.

### Actual Results

The results of the shift do not match:

```
[2022-08-10T12:14:39Z DEBUG wasmtime_fuzzing::oracles] Evaluating: test([I32(1795123818), I32(-2147483648)])
[2022-08-10T12:14:39Z DEBUG wasmtime_fuzzing::oracles]  -> results on spec: [I32(-2097152)]
[2022-08-10T12:14:39Z DEBUG wasmtime_fuzzing::oracles]  -> results on wasmtime: [I32(1795123818)]
```

### Versions and Environment

Wasmtime version or commit: `abrown:meta-diff` branch

Operating system: Fedora 35

Architecture: x86-64

### Other

I am reporting this to clean up any fuzz bugs found before trying to merge #4515. In talking to @alexcrichton, the first reaction seemed to be that this is a bug in the spec interpreter OCaml bindings (after all, Wasmtime passes all spec tests for this kind of simple operation as does the spec interpreter, I assume). @conrad-watt, any thoughts on this?

### PR DESCRIPTION
**Pull request by abrown**
In #4671, the meta-differential fuzz target was finding errors when
running certain Wasm modules (specifically `shr_s` in that case).
@conrad-watt diagnosed the issue as a missing reversal in the operands
passed to the spec interpreter. This change fixes #4671 and adds an
additional unit test to keep it fixed.

### CODE REVIEW

File: crates/fuzzing/wasm-spec-interpreter/ocaml/interpret.ml [hunk 1]
```diff
@@ -55,7 +55,7 @@ let extract_exported_func export = match export with
 (** Interpret the first exported function and return the result. Use provided
 parameters if they exist, otherwise use default (zeroed) values. *)
 let interpret_exn module_bytes opt_params =
-  let opt_params_ = Option.map (List.map convert_to_wasm) opt_params in
+  let opt_params_ = Option.map (List.rev_map convert_to_wasm) opt_params in
```
Comment (bjorn3) [inline crates/fuzzing/wasm-spec-interpreter/ocaml/interpret.ml:58]: Is this a bug in the official wasm interpreter?

Comment (conrad-watt) [reply crates/fuzzing/wasm-spec-interpreter/ocaml/interpret.ml:58]: Internally, the interpreter represents the value stack as a list in reverse order, so that popping from the stack is equivalent to taking the head of the list.

My tweaked version of the interpreter exposes an entrypoint function that assumes this reversal has already happened, hence the confusion. When I cut a new version of my interpreter, I can investigate if it makes sense to push the reversal down further, but an advantage of doing it this way is that the `rev` and `map` operations can be carried out simultaneously, which is more efficient.

**Review by conrad-watt — APPROVED** [review]
LGTM!

**Review by alexcrichton — APPROVED** [review]
