### PR TITLE
Wasmtime: disable unwind_info unless needed

### LINKED ISSUE #4350: Can't fully disable wasm backtraces
- In wasmtime 0.38.1, disabling stack tracing results in a `setting "unwind_info" is configured to Bool(false) which is not supported` due to https://github.com/bytecodealliance/wasmtime/blob/9e2adfb34531610d691f74dd3f559bc5b800eb02/crates/wasmtime/src/engine.rs#L325.
- On master, backtraces can be disabled, but cranelift's "unwind_info" isn't set to false (it just isn't set). This is making one of our tests 1000x slower (0.12 seconds to 120 seconds).

I can fix this with:

```patch
diff --git a/crates/wasmtime/src/config.rs b/crates/wasmtime/src/config.rs
index b41ae9396..256009a0a 100644
--- a/crates/wasmtime/src/config.rs
+++ b/crates/wasmtime/src/config.rs
@@ -1423,6 +1423,10 @@ impl Config {
             {
                 bail!("compiler option 'unwind_info' must be enabled when either 'backtraces' or 'reference types' are enabled");
             }
+        } else {
+            unsafe {
+                self.cranelift_flag_set("unwind_info", "false");
+            }
         }
         if self.features.reference_types {
             if !self
diff --git a/crates/wasmtime/src/engine.rs b/crates/wasmtime/src/engine.rs
index 9dd637e71..83514d72c 100644
--- a/crates/wasmtime/src/engine.rs
+++ b/crates/wasmtime/src/engine.rs
@@ -345,7 +345,7 @@ impl Engine {
             // can affect the way the generated code performs or behaves at
             // runtime.
             "avoid_div_traps" => *value == FlagValue::Bool(true),
-            "unwind_info" => *value == FlagValue::Bool(true),
+            "unwind_info" => true,
             "libcall_call_conv" => *value == FlagValue::Enum("isa_default".into()),
 
             // Features wasmtime doesn't use should all be disabled, since
```

But I'm wondering if:

1. The other settings (reference types, simd) need to be explicitly set as well.
2. There's a bad default somewhere. Should `unwind_info` be disabled by default in cranelift?

### PR DESCRIPTION
**Pull request by Stebalien**
Disable the "unwind_info" cranelift feature unless backtraces (or reference types) are enabled. Maintaining unwind info in deeply recursive modules can get expensive.

fixes #4350

### CODE REVIEW

**Review by pchickey — APPROVED** [review]

File: crates/wasmtime/src/engine.rs [hunk 1]
```diff
@@ -381,6 +380,7 @@ impl Engine {
             | "enable_verifier"
             | "regalloc_checker"
             | "is_pic"
+            | "unwind_info"
```
Comment (Stebalien) [inline crates/wasmtime/src/engine.rs:383]: Note: this is inconsistent with "enable_safepoints", which checks that we don't ahve the `reference_types` feature enabled. But so is "enable_simd", so I'm not sure which way to go.

**Comment by alexcrichton** [comment]
Also, I'm a bit confused how this is coming up, this example program works for me:

```rust
use anyhow::Result;
use wasmtime::*;

fn main() -> Result<()> {
    let mut config = Config::new();
    config.wasm_backtrace(false);
    let engine = Engine::new(&config).unwrap();
    let m1 = Module::new(&engine, "(module (func unreachable))")?;

    let bytes = m1.serialize()?;
    let m2 = unsafe { Module::deserialize(&engine, &bytes)? };

    let mut store = Store::new(&engine, ());
    Instance::new(&mut store, &m1, &[])?;
    Instance::new(&mut store, &m2, &[])?;
    Ok(())
}
```

so I'm also curious what configuration you're using to trigger the error coming out.

**Comment by Stebalien** [comment]
> Would you be up for adding a test which disables backtraces? I thought we had something along those lines but it sounds like your configuration is different which our current test suite isn't covering.

There's a test:

https://github.com/bytecodealliance/wasmtime/blob/2034c8aa453d7114ef8acbe201bd4acec9117974/tests/all/traps.rs#L73-L97

But it doesn't test that unwind info isn't generated. I've just added a targeted one to make sure it's disabled at the compiler level, but there may be a better way.

**Comment by Stebalien** [comment]
> Also, I'm a bit confused how this is coming up, this example program works for me:

It does work, however:

1. In 0.38, unwind info won't be disabled unless you also disable reference types. If you disable reference types as well, that won't work.
2. In 0.39 (dev), that will "work" simply because unwind info won't be disabled no matter what you do.

The test I added should catch this.

**Comment by Stebalien** [comment]
> Otherwise though I think that the unwind_info flag still needs verification as you mentioned along the lines of safepoints.

I was pointing out an inconsistency. It looks like that function is _primarily_ for validating that the config matches the current system, not for validating that the config matches the flags. That function isn't currently checking, e.g., enable_simd, enable_float, enable_verifier, etc. either. The enable_safepoints check is actually the exception.

The config is checked against the compiler flags in https://github.com/bytecodealliance/wasmtime/blob/61312a9bf4b6a5d0922f77901f9b3f025de324ef/crates/wasmtime/src/config.rs#L1410

**Comment by Stebalien** [comment]
Ah, because this is checking the _compiled_ module. Got it, thanks. That also explains why we don't care about enable_simd, enable_float, etc. (although the fact that the engine will happily deserialize a module that doesn't _quite_ match the engine's config is non-obvious).

I've pushed a fix, but I think there's still _technically_ a bug. We're checking that we have unwind_info _if_ the flag is present, but we're not making sure the flag is actually present. I'm not sure if we really care, but I figured I'd mention it.

---

Meta: would you like me to squash?

**Comment by Stebalien** [comment]
@alexcrichton and @pchickey, thanks for guiding me through this!
