### PR TITLE
Unconditionally enable sse3, ssse3, and sse4.1 when fuzzing

### LINKED ISSUE #3809: Minimum x86_64 feature support required for SIMD proposal
With https://github.com/bytecodealliance/wasmtime/pull/3800 on oss-fuzz last night it quickly found a few "bugs" in the cranelift backend for x86_64, primarily around SIMD support. This led me to raise a question, however, as to whether or not we want to consider these issues bugs. The crashes all have the same pattern where we're forcibly disabling processor features and testing whether wasm still works.

Currently in Wasmtime it appears that at least for some instructions the SSE 4.1 extensions are required. If those are not present then two crashes found so far are:

* `Cannot emit inst 'pmovsxdq 0(%r19J), %r0V' for target; failed to match ISA requirements: [SSE41]`
* [this panic](https://github.com/bytecodealliance/wasmtime/blob/db9e3ce9d94adcbf380cafd1cf4506cfc7752064/cranelift/codegen/src/isa/x64/lower.rs#L3842) presumably with instructions like `f32x4.floor`

With this in mind I'm wondering if it makes sense to consider these bugs or not? There's nothing wrong with the SSE 4.1 codegen this is only a problem for when that feature isn't available we're unable to generate code. Is this something we want to consider as  a bug? Or alternatively we can also simply declare that running Wasmtime with the SIMD wasm feature enabled requires SSE 4.1 on x86_64 and we can provide a more first-class error in Wasmtime when a module is attempted to be used without SSE 4.1

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit unconditionally enables some x86_64 instructions when
fuzzing because the cranelift backend is known to not work if these
features are disabled. From discussion on the wasm simd proposal the
assumed general baseline for running simd code is SSE4.1 anyway.

At this time I haven't added any sort of checks in Wasmtime itself.
Wasmtime by default uses the native architecture and when explicitly
enabling features this still needs to be explicitly specified.

Closes #3809

### CODE REVIEW

**Review by cfallin — APPROVED** [review]
r+ for immediate fuzzing fix, and then hopefully we can do something along the lines of either #3810 or a cleaner failure if someone tries instantiating an `Engine` with SIMD support but not these features.

File: crates/fuzzing/src/generators.rs [hunk 1]
```diff
@@ -699,9 +699,16 @@ impl<'a> Arbitrary<'a> for CodegenSettings {
             if u.ratio(1, 10)? {
                 let flags = target_features! {
                     test: is_x86_feature_detected,
-                    std:"sse3" => clif:"has_sse3",
-                    std:"ssse3" => clif:"has_ssse3",
-                    std:"sse4.1" => clif:"has_sse41",
+
+                    // These features are considered to be baseline required by
+                    // Wasmtime. Currently SIMD some simd code generation will
```
Comment (abrown) [inline crates/fuzzing/src/generators.rs:704]:
```suggestion
                    // Wasmtime. Currently some SIMD code generation will
```

**Review by abrown — APPROVED** [review]
