### PR TITLE
WASI preview 2 output-streams: new backpressure and flushing design

### LINKED ISSUE #6811: Wasi Preview 2 Async Race Condition
Moving streams to async has introduced a race condition. The `AsyncWriteStream` often gets dropped before the [receiver inside the spawned task](https://github.com/bytecodealliance/wasmtime/blob/bb3734bd724683cce8aa20de0cad9f9086e07b50/crates/wasi/src/preview2/pipe.rs#L237) has time to receive a message.

This makes sense as there's nothing to tie the spawned task's completion to the `Store` that contains the `AsyncWriteStream`. It's very easy to drop the `Store` before any handlers are allowed to run to completition.

### Test Case

Take the following "hello world" case:

```rust
use wasmtime::{
    component::{Component, Linker},
    Config, Engine, Store,
};
use wasmtime_wasi::preview2::{Table, WasiCtx, WasiCtxBuilder, WasiView};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let mut config = Config::new();
    config.wasm_component_model(true).async_support(true);
    let engine = Engine::new(&config)?;
    let component = Component::from_file(&engine, "example.wasm")?;
    let mut table = Table::new();
    let ctx = WasiCtxBuilder::new().inherit_stdio().build(&mut table)?;
    let mut store = Store::new(&engine, Data { table, ctx });
    let mut linker = Linker::new(&engine);
    wasmtime_wasi::preview2::command::add_to_linker(&mut linker)?;
    let instance = linker.instantiate_async(&mut store, &component).await?;
    let run = instance.get_typed_func::<(), ()>(&mut store, "hello")?;
    run.call_async(&mut store, ()).await?;
    Ok(())
}

struct Data {
    table: Table,
    ctx: WasiCtx,
}

impl WasiView for Data {
    fn table(&self) -> &wasmtime_wasi::preview2::Table {
        &self.table
    }

    fn table_mut(&mut self) -> &mut wasmtime_wasi::preview2::Table {
        &mut self.table
    }

    fn ctx(&self) -> &wasmtime_wasi::preview2::WasiCtx {
        &self.ctx
    }

    fn ctx_mut(&mut self) -> &mut wasmtime_wasi::preview2::WasiCtx {
        &mut self.ctx
    }
}
```

The `example.wasm` file is just a simple wasm component that has one export `hello` which just uses Rust's `println!` to print "Hello, World!" to stdout. 

This technically works, but only by coincidence. If we see when the "Hello, World" gets flushed to stdout, it happens *after* the [spawned task](https://github.com/bytecodealliance/wasmtime/blob/bb3734bd724683cce8aa20de0cad9f9086e07b50/crates/wasi/src/preview2/pipe.rs#L113-L129) that is handling IO is [aborted in the Drop handler](https://github.com/bytecodealliance/wasmtime/blob/bb3734bd724683cce8aa20de0cad9f9086e07b50/crates/wasi/src/preview2/pipe.rs#L297). 

### Steps to Reproduce

You can reproduce those by running the above example with a local checkout of `wasmtime`. Simply add a logging statement to the [drop handler of `AsyncWriteStream`](https://github.com/bytecodealliance/wasmtime/blob/bb3734bd724683cce8aa20de0cad9f9086e07b50/crates/wasi/src/preview2/pipe.rs#L295-L299) and you'll see that the drop (and thus the cancellation of the spawned task) happens *before* the output to stdout. 

I've found this to be reliably reproducible in a user visible way if the wasm binary prints more than 1 line of text to stdout. The first line usually gets successfully flushed, but the second does not. Adding something to slow down the execution of the runtime can eliminates the bug (e.g., adding `tokio::time::sleep(std::time::Duration::from_millis(1)).await;` after the function call, gets rid of the race condition). 

I first caught this bug first when upgrading [Spin](https://github.com/fermyon/spin) to the latest version of `wasmtime`. The exported function would complete and the containing `Store` would be dropped before the underlying `AsyncWriteStream`'s spawned task had a chance to receive the bytes to be written to the inner `AsyncWrite` type. Only every ~10th invocation would see the spawned task actually process the bytes before the `AsyncWriteStream`'s drop handler canceled the task.

### Expected Results

I would expect that there would be some mechanism for ensuring that ongoing async writes complete before the `Store` is dropped.

### Versions and Environment

This is the case on the [latest version of `wasmtime`](https://github.com/bytecodealliance/wasmtime/commit/bb3734bd724683cce8aa20de0cad9f9086e07b50) as of this writing.

### PR DESCRIPTION
**Pull request by pchickey**
Backpressure design is being revised to take into account that any call with a `list<bytes>` argument is going to consume the resources of the callee, so the callee has to explicitly permit how much that is allowed to consume.

Flushing is a way to request & observe the completion of a write. Since the write itself is non-blocking it cant report that it failed if that happens after the call is over. the explicit flush call allows the caller to wait for a write (or sequence of writes) to produce an error, or guarantee that it succeeded.

Fixes #6811

This PR changes the wit interfaces, therefore we are leaving it as a draft until after WasmCon & Componentize the World (Sept 6-8) so that wasmtime's `main` reflects a consistent set of interfaces for demos and hacking at those events.

We plan to merge this PR to main on Monday, Sept 11. We will then backport it as a cherry-pick to the 13.0 release branch so that these changes get included in the wasmtime 13 release as well.

### CODE REVIEW

File: crates/wasi/src/preview2/pipe.rs [hunk 1]
```diff
@@ -210,84 +222,190 @@ impl HostInputStream for AsyncReadStream {
...
-impl AsyncWriteStream {
-    /// Create a [`AsyncWriteStream`]. In order to use the [`HostOutputStream`] impl
-    /// provided by this struct, the argument must impl [`tokio::io::AsyncWrite`].
-    pub fn new<T: tokio::io::AsyncWrite + Send + Sync + Unpin + 'static>(mut writer: T) -> Self {
-        let (sender, mut receiver) = tokio::sync::mpsc::channel::<Bytes>(1);
-        let (result_sender, result_receiver) = tokio::sync::mpsc::channel(1);
+#[derive(Debug)]
+struct WorkerState {
+    alive: bool,
+    items: std::collections::VecDeque<WriteMessage>,
```
Comment (alexcrichton) [inline crates/wasi/src/preview2/pipe.rs:240]: This part about all the queueing makes me a bit uneasy. I'd naively expect at-most-one thing here contractually and then we'd add vectors/etc as optimizations in the future maybe.

I think this stems though from the contract of flush/write? I'm personally of the opinion that we should change the WASI layer to only allow at most one operation at a time if we can, meaning that each stream has a single pollable which indicates the status of the pending operation, if any. I know @pchickey you were thinking we should allow concurrent flush/write, though.

Maybe we should jump on a call for a chat about this?

File: crates/wasi-preview1-component-adapter/src/lib.rs [hunk 2]
```diff
@@ -2127,6 +2123,54 @@ impl From<filesystem::DescriptorType> for wasi::Filetype {
...
+                    streams::WriteReadiness::Ready(n) => n,
+                };
+                let len = (n as usize).min(bytes.len());
+                match streams::write(output_stream, &bytes[..len]) {
+                    Some(streams::WriteReadiness::Closed) => Err(ERRNO_IO),
+                    _ => Ok(len),
+                }
+            }
+        }
+    }
```
[the remark this answers is not in the document]
Comment (alexcrichton) [reply crates/wasi-preview1-component-adapter/src/lib.rs:2171]: For reproducing this I've done:

```
$ cargo build -p wasi-preview1-component-adapter --target wasm32-wasi --features command --no-default-features
$ cat foo.rs
fn main() {
    println!("wat");
}
$ rustc foo.rs --target wasm32-wasi
$ wasm-tools component new ./foo.wasm -o foo.component.wasm --adapt ./target/wasm32-wasi/debug/wasi_snapshot_preview1.wasm
$ cargo run --features component-model -- --wasm-features component-model ./foo.component.wasm
```

and no output comes out

[the remark this answers is not in the document]
Comment (pchickey) [reply crates/wasi-preview1-component-adapter/src/lib.rs]: Yes, that was the intent. Fixed in 8a91dd

File: crates/wasi/src/preview2/tcp.rs [hunk 3]
```diff
@@ -46,15 +45,80 @@ pub(crate) enum HostTcpState {
...
+
+const SOCKET_READY_SIZE: usize = 1024 * 1024 * 1024;
+
+#[async_trait::async_trait]
+impl HostOutputStream for HostTcpSocketInner {
+    fn write(&mut self, mut bytes: bytes::Bytes) -> anyhow::Result<Option<WriteReadiness>> {
+        while !bytes.is_empty() {
+            let n = self.stream.try_write(&bytes)?;
+            let _ = bytes.split_to(n);
+        }
```
[the remark this answers is not in the document]
Comment (elliottt) [reply crates/wasi/src/preview2/tcp.rs]: This should be resolved after merging in #6928.

File: crates/wasi/src/preview2/tcp.rs [hunk 4]
```diff
@@ -46,15 +45,80 @@ pub(crate) enum HostTcpState {
...
+impl HostInputStream for HostTcpSocketInner {
+    fn read(&mut self, size: usize) -> Result<(bytes::Bytes, StreamState), anyhow::Error> {
+        if size == 0 {
+            return Ok((bytes::Bytes::new(), StreamState::Open));
+        }
+
+        let mut buf = bytes::BytesMut::with_capacity(size);
+        let n = self.stream.try_read_buf(&mut buf)?;
+
+        // TODO: how do we detect a closed stream?
```
[the remark this answers is not in the document]
Comment (elliottt) [reply crates/wasi/src/preview2/tcp.rs]: Works for me!

File: crates/wasi/src/preview2/tcp.rs [hunk 5]
```diff
@@ -46,15 +45,80 @@ pub(crate) enum HostTcpState {
...
+    fn flush(&mut self) -> anyhow::Result<Option<FlushResult>> {
+        Ok(Some(FlushResult::Done))
+    }
+
+    async fn write_ready(&mut self) -> anyhow::Result<WriteReadiness> {
+        self.stream.writable().await?;
+        Ok(WriteReadiness::Ready(SOCKET_READY_SIZE))
+    }
+
+    async fn flush_ready(&mut self) -> anyhow::Result<FlushResult> {
```
[the remark this answers is not in the document]
Comment (elliottt) [reply crates/wasi/src/preview2/tcp.rs]: This method no longer exists, but that would have good!

File: crates/wasi/src/preview2/pipe.rs [hunk 6]
```diff
@@ -210,84 +222,190 @@ impl HostInputStream for AsyncReadStream {
...
-                                    let _ = result_sender.send(Err(e)).await;
-                                    break 'outer;
-                                }
+#[derive(Clone)]
+struct Worker {
+    state: Arc<Mutex<WorkerState>>,
+    new_work: Arc<tokio::sync::Notify>,
+    write_ready_changed: Arc<tokio::sync::Notify>,
+    flush_result_changed: Arc<tokio::sync::Notify>,
+}
```
[the remark this answers is not in the document]
Comment (elliottt) [reply crates/wasi/src/preview2/pipe.rs]: Great point!

File: crates/wasi/src/preview2/filesystem.rs [hunk 7]
```diff
@@ -180,35 +177,103 @@ pub(crate) enum FileOutputMode {
...
+        }
+        // Wait for outstanding task:
+        std::pin::Pin::new(&mut self.task).await;
+
+        // Mark task as finished, and handle output:
+        match std::pin::Pin::new(&mut self.task)
+            .take_output()
+            .expect("just awaited for MaybeDone completion")
+            .context("join of FileOutputStream worker task")
+            .map_err(OutputStreamError::Trap)?
```
Comment (alexcrichton) [inline crates/wasi/src/preview2/filesystem.rs:270]: This feels a little odd to me in the sense that the trap/context make sense if this is going to be a trap/complete failure but this is also being wrapped up in `LastOperationFailed` below additionally. My guess, having not read further yet, is that there's error handling of `OutputStreamError` which makes this not always a trap. This looks like, given the wrapper on this line though, that it's always a trap?

I'll dig in more when seeing the error handling.

Comment (alexcrichton) [reply crates/wasi/src/preview2/filesystem.rs:270]: Oh actually I think I'm totally wrong. I think this is handling the `Result` layer of the spawned task which is propagating panics.

In that case, could `unwrap` or `expect` be used here instead of `context`/`map_err`?

File: crates/wasi/src/preview2/host/io.rs [hunk 8]
```diff
@@ -256,85 +207,129 @@ impl<T: WasiView> streams::Host for T {
...
+
+        if bytes.len() > 4096 {
+            return Err(streams::Error::trap(anyhow::anyhow!(
+                "Buffer too large for blocking-write-and-flush (expected at most 4096)"
+            )));
+        }
+
+        let mut bytes = bytes::Bytes::from(bytes);
+        while !bytes.is_empty() {
+            let permit = HostOutputStream::write_ready(s).await?;
```
Comment (alexcrichton) [inline crates/wasi/src/preview2/host/io.rs:298]: Syntax-wise, is it possible to write this as `s.write_read().await?`?

File: crates/wasi/src/preview2/pipe.rs [hunk 9]
```diff
@@ -74,42 +78,55 @@ impl MemoryOutputPipe {
...
         Ok(())
     }
+    async fn write_ready(&mut self) -> Result<usize, OutputStreamError> {
+        let consumed = self.buffer.lock().unwrap().len();
+        if consumed < self.capacity {
+            Ok(self.capacity - consumed)
+        } else {
+            Ok(0)
+        }
+    }
```
Comment (alexcrichton) [inline crates/wasi/src/preview2/pipe.rs:103]: Question on this, is the intention that the host will consume output from a `MemoryOutputBuffer` incrementally, freeing up space in the pipe? Or is the intention that everything is collected and then the pipe is completely done and no more data can ever be put in?

File: crates/wasi/src/preview2/stdio.rs [hunk 10]
```diff
@@ -22,7 +21,7 @@ pub use self::worker_thread_stdin::{stdin, Stdin};
 pub struct Stdout(AsyncWriteStream);
 
 pub fn stdout() -> Stdout {
-    Stdout(AsyncWriteStream::new(tokio::io::stdout()))
+    Stdout(AsyncWriteStream::new(2048, tokio::io::stdout()))
```
Comment (alexcrichton) [inline crates/wasi/src/preview2/stdio.rs:24]: Could 2048 be a documented constant here? That seems a little small to have as a budget, but we can always change it later.

File: crates/wasi/src/preview2/stream.rs [hunk 11]
```diff
@@ -77,91 +77,78 @@ pub trait HostInputStream: Send + Sync {
...
+            OutputStreamError::Trap(e) => write!(f, "trap: {e}"),
+        }
+    }
+}
+impl std::error::Error for OutputStreamError {
+    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
+        match self {
+            OutputStreamError::Closed => None,
+            OutputStreamError::LastOperationFailed(e) | OutputStreamError::Trap(e) => {
+                Some(e.as_ref())
```
Comment (alexcrichton) [inline crates/wasi/src/preview2/stream.rs:100]: Could this use `e.source()`? Otherwise errors will get double-printed because the error is printed in `Display` above and would additionally be printed when the `source` is printed here

File: crates/wasi/src/preview2/tcp.rs [hunk 12]
```diff
@@ -46,113 +45,206 @@ pub(crate) enum HostTcpState {
...
+    }
+
+    /// Write `bytes` in a background task, remembering the task handle for use in a future call to
+    /// `write_ready`
+    fn background_write(&mut self, mut bytes: bytes::Bytes) {
+        assert!(self.write_handle.is_none());
+
+        let stream = self.stream.clone();
+        self.write_handle.replace(
+            tokio::spawn(async move {
```
Comment (alexcrichton) [inline crates/wasi/src/preview2/tcp.rs:138]: Should this use `preview2::spawn` to handle the sync case too?

File: crates/wasi/src/preview2/tcp.rs [hunk 13]
```diff
@@ -46,113 +45,206 @@ pub(crate) enum HostTcpState {
...
+                // Note: we are not using the AsyncWrite impl here, and instead using the TcpStream
+                // primitive try_write, which goes directly to attempt a write with mio. This has
+                // two advantages: 1. this operation takes a &TcpStream instead of a &mut TcpStream
+                // required to AsyncWrite, and 2. it eliminates any buffering in tokio we may need
+                // to flush.
+                while !bytes.is_empty() {
+                    stream.writable().await?;
+                    let n = stream.try_write(&bytes)?;
```
Comment (alexcrichton) [inline crates/wasi/src/preview2/tcp.rs:146]: Could the error be handled here to detect EWOULDLBOCK? I'm worried about spurious writable notifications from above causing the write here to immediately return "WOULDBLOCK", but being able to handle that

File: crates/wasi/src/preview2/tcp.rs [hunk 14]
```diff
@@ -46,113 +45,206 @@ pub(crate) enum HostTcpState {
...
-impl HostOutputStream for Arc<HostTcpSocketInner> {
-    fn write(&mut self, buf: Bytes) -> anyhow::Result<(usize, StreamState)> {
-        if buf.is_empty() {
-            return Ok((0, StreamState::Open));
+    async fn write_ready(&mut self) -> Result<usize, OutputStreamError> {
+        if self.write_handle.is_some() {
+            self.write_handle
+                .as_mut()
+                .unwrap()
+                .await
```
Comment (alexcrichton) [inline crates/wasi/src/preview2/tcp.rs:193]: Could this be:

```rust
if let Some(handle) = &mut self.write_handle {
    handle.await...
}
```

File: crates/wasi/src/preview2/tcp.rs [hunk 15]
```diff
@@ -46,113 +45,206 @@ pub(crate) enum HostTcpState {
...
+                .map_err(|e| OutputStreamError::Trap(e.into()))?
```
Comment (alexcrichton) [inline crates/wasi/src/preview2/tcp.rs:194]: Like way up a above IMO this should be `.unwrap` or `.expect` to propagate a panic rather than hiding it under a trap

File: crates/wasi/src/preview2/filesystem.rs (hunk 7 above)
Comment (pchickey) [reply crates/wasi/src/preview2/filesystem.rs:270]: yes, this should be an expect instead of a trap.

File: crates/wasi/src/preview2/pipe.rs (hunk 9 above)
Comment (pchickey) [reply crates/wasi/src/preview2/pipe.rs:103]: The intention is that writes get collected up to the stated capacity, then no more are accepted.

We could return Err(OutputStreamError::Closed) once capacity is reached, but I wasn't really sure.

We basically only use this type to collect output in tests.

File: crates/wasi/src/preview2/host/io.rs (hunk 8 above)
Comment (pchickey) [reply crates/wasi/src/preview2/host/io.rs]: fxied

File: crates/wasi/src/preview2/stream.rs (hunk 11 above)
Comment (pchickey) [reply crates/wasi/src/preview2/stream.rs:100]: Thanks, I frequently get that one wrong

File: crates/wasi/src/preview2/tcp.rs (hunk 12 above)
Comment (pchickey) [reply crates/wasi/src/preview2/tcp.rs]: done

File: crates/wasi/src/preview2/tcp.rs (hunk 13 above)
Comment (pchickey) [reply crates/wasi/src/preview2/tcp.rs]: thanks, done

File: crates/wasi/src/preview2/tcp.rs (hunk 15 above)
Comment (pchickey) [reply crates/wasi/src/preview2/tcp.rs]: i changed AbortOnDropJoinHandle's Future impl to always unwrap the task panics

File: crates/wasi/src/preview2/stdio.rs (hunk 10 above)
Comment (pchickey) [reply crates/wasi/src/preview2/stdio.rs]: I upped it to 4096 because thats what we let blocking-write-and-flush accept
