### PR TITLE
Use the `psm` crate to figure out the current stack pointer

### LINKED ISSUE #2344: Wasm native stack limit protections don't always work with ASan
Recently we've received a number of fuzz bugs all about stack overflows in native code. Each fuzz bug has a module which contains an infinitely recursive set of functions when instantiated/called, and the stack overflow happens in the native code of Wasmtime, and the exact native code changes depending on what the module is doing. This situation is supposed to be mitigated by limiting the amount of stack space wasm is allowed to take. After some investigation, however, this limiting isn't happening. 

When ASan is run with `ASAN_OPTIONS="detect_stack_use_after_return=1"` then it allocates a "shadow stack" for each function frame. This means that [our guess of what the stack pointer is](https://github.com/bytecodealliance/wasmtime/blob/44cbdecea03c360ea82e6482f0cf6c614effef21/crates/runtime/src/traphandlers.rs#L504) is actually pointing into the shadow stack area instead of the real native stack. This means that we install a stack limit very far away from the actual stack  itself, rendering the stack limit useless since stack overflow is hit long before we get to the shadow stack.

To be clear I don't think this is necessarily a but in Wasmtime, this only comes up with fuzzing under AddressSanitizer. That being said that fuzz mode is very important and we don't want to lose that! I think there's a few possible fixes we could do in this situation:

1. Disable fuzzing with `detect_stack_use_after_return`. From what I can tell I think this is for having better error reports, and it may not be that critical for Wasmtime, especially with how rare use-after-return is in Rust. That being said I would prefer to take this route as a last resort.
2. Fix our "educated guess" about what the stack pointer is. This would probably involve us compiling an asm stub which only says `mov %rsp, %rax; ret` or something like that. This I think should work since it won't be instrumented by ASan and point into the shadow stack. It's a bummer to maintain custom assembly, however.
3. Refactor how we account for native stack space in wasm modules. Right now this is a `usize` where if `%rsp` is ever beneath it we trap. Instead we could change it to a `usize` of "you have this many bytes left" where each function subtracts and traps on overflow. Additionally, interrupts, which use this same flag, would simply set the remaining bytes to a negative number so the next comparison traps.

I would personally lean towards the third option since I think it also reflects more accurately how much stack space wasm can use. It means we don't ever need the stack pointer itself in native code and interleaving small wasm stacks with larger native stacks will actually work, where it doesn't work today since wasm isn't allowed to go beyond the maximum stack size of the first wasm module on the stack.

I'm curious what others think though!

### PR DESCRIPTION
**Pull request by alexcrichton**
Currently the runtime needs to acquire the current stack pointer so it
can set a limit for where if the wasm stack goes below that point it
will abort the wasm code. Acquiring the stack pointer is done in a
brittle way right now which involves looking at the address of what we
hope is an on-stack structure. This turns out to not work at all with
ASan as well.

Instead this commit switches to the `psm` crate which is used by the
Rust compiler team for stack manipulation, namely a coarse version of
segmented stacks to avoid stack overflow in the compiler. We don't need
most of the implementation of `psm`, just the `stack_pointer` function,
but it shouldn't be a burden to bring in!

Closes #2344

### CODE REVIEW

File: crates/runtime/src/traphandlers.rs [hunk 1]
```diff
@@ -501,7 +501,7 @@ impl<'a> CallThreadState<'a> {
     fn update_stack_limit(&self, max_wasm_stack: usize) -> Result<impl Drop + '_, Trap> {
         // Make an "educated guess" to figure out where the wasm sp value should
         // start trapping if it drops below.
```
Comment (tschneidereit) [inline crates/runtime/src/traphandlers.rs:503]: Since I just looked at this: "educated guess" makes me a little bit nervous, given the importance of this :) Can you talk a bit about the implications of this, both in terms of security and, if any, resource use limits?

If no implications for either exists, then I think it'd at least be good to update the comment and explain why this is all fine.

Comment (alexcrichton) [reply crates/runtime/src/traphandlers.rs]: Ah good point! I've updated the comment. Now that we're using something like `psm` it's more official and less educated. Otherwise this just refers to the imprecision about accounting for wasm stacks. If you ask for wasm to have a megabyte of stack, we may end up giving it a megabyte plus or minus a few hundred bytes.

Comment (tschneidereit) [reply crates/runtime/src/traphandlers.rs]: Great comment, thank you!

**Review by tschneidereit — APPROVED** [review]
I know too little about the `psm` crate to approve the actual code change, so this is just an r+ of the comment :)

**Review by yurydelendik — APPROVED** [review]
