### PR TITLE
Two fixes for the `-g` (debug info) option

### LINKED ISSUE #3999: Assertion in debugger mode (left < right)
### Test Case

https://user-images.githubusercontent.com/5621716/161971426-a7599e7d-886f-4101-b379-8f5c20a38a8e.mov

( couldn't upload .wasm file so I'd changed extension to .mov, it is actually .wasm file)

### Steps to Reproduce

RUST_BACKTRACE=1 gdb --args wasmtime run -g preinitialized.wasm

### Expected Results

debug break

### Actual Results

crash:

thread 'main' panicked at 'assertion failed: `(left < right)`
  left: `9699`,
 right: `7415`', crates/cranelift/src/debug/transform/expression.rs:690:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: wasmtime_cranelift::debug::transform::expression::ValueLabelRangesBuilder::process_label
   3: wasmtime_cranelift::debug::transform::expression::CompiledExpression::build_with_locals
   4: wasmtime_cranelift::debug::transform::simulate::generate_simulated_dwarf
   5: wasmtime_cranelift::debug::transform::transform_dwarf
   6: wasmtime_cranelift::debug::write_debuginfo::emit_dwarf
   7: <wasmtime_cranelift::compiler::Compiler as wasmtime_environ::compilation::Compiler>::emit_obj
   8: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  10: <rayon::iter::fold::FoldFolder<C,ID,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
  11: rayon::iter::plumbing::bridge_producer_consumer::helper
  12: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
  13: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed
  14: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
  15: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter
  16: wasmtime::module::Module::build_artifacts
  17: core::ops::function::FnOnce::call_once
  18: wasmtime_cache::ModuleCacheEntry::get_data_raw
  19: wasmtime::module::Module::from_binary
  20: wasmtime::module::Module::from_file
  21: wasmtime_cli::commands::run::RunCommand::load_module
  22: wasmtime_cli::commands::run::RunCommand::load_main_module
  23: wasmtime_cli::commands::run::RunCommand::execute
  24: wasmtime::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

### Versions and Environment

Wasmtime version or commit: wasmtime 0.35.2

Operating system: ubuntu 20.04

Architecture: x86_64

### PR DESCRIPTION
**Pull request by SingleAccretion**
Two changes:
1) Fix a small bug where a constant DWARF "block" wasn't handled in transformation.
2) Fix up instruction offsets after code emission to account for branch removal.

See also the commit messages for a bit more detail.

With these two changes, I am able to step through the code generated by the [compiler](https://github.com/dotnet/runtimelab/tree/feature/NativeAOT-LLVM) we are working on.

Fixes #3999.

### CODE REVIEW

File: cranelift/codegen/src/machinst/vcode.rs [hunk 1]
```diff
@@ -1097,6 +1097,7 @@ impl<I: VCodeInst> VCode<I> {
             }
         }
 
+        self.monotonize_inst_offsets(&mut inst_offsets[..], func_body_len);
         let value_labels_ranges =
             self.compute_value_labels_ranges(regalloc, &inst_offsets[..], func_body_len);
```
Comment (SingleAccretion) [inline cranelift/codegen/src/machinst/vcode.rs:1102]: It is interesting to note that `optimize_branches` is invoked after this code one last time and can nominally modify the current buffer pointer, make `func_body_len` stale, etc. At the same time, for it to remove a branch, that branch needs to point past the end of the function, which doesn't seem possible?

**Review by fitzgen — COMMENTED** [review]
Looks good to me!

Would it be possible to construct a somewhat minimal test case where the branch lowering messes up the offsets and we need to monotize them and add it to our debugging tests? Eg https://github.com/bytecodealliance/wasmtime/blob/main/tests/all/debug/lldb.rs#L62

File: cranelift/codegen/src/machinst/vcode.rs [hunk 2]
```diff
@@ -1115,6 +1116,43 @@ impl<I: VCodeInst> VCode<I> {
...
+                    inst_index,
+                    inst_offset,
+                    next_offset
+                );
+                inst_offsets[inst_index] = next_offset;
+                continue;
+            }
+
+            // Not all instructions get their offsets recorded.
+            if inst_offset != 0 {
```
Comment (cfallin) [inline cranelift/codegen/src/machinst/vcode.rs:1150]: This does seem to leave an interesting corner case: if the very first instruction is a jump and is chomped (say because it's a jump to the fallthrough location, i.e. the next block), we artificially skip.

However I think it's OK for the following very subtle reason: we can only chomp back to an empty buffer (and hence have an offset of `0` on the non-first instruction) if we have one jump instruction (and nothing else) in the first block; MachBuffer will never chomp e.g. a cond+uncond pair to nothing. In the single-jump-inst case, that inst also has an offset of `0` so it's still monotonic.

Could we leave a comment to this effect?

**Comment by SingleAccretion** [comment]
> Would it be possible to construct a somewhat minimal test case where the branch lowering messes up the offsets and we need to monotize them and add it to our debugging tests?

Should definitely be possible; will do.

File: cranelift/codegen/src/machinst/vcode.rs (hunk 2 above)
Comment (SingleAccretion) [reply cranelift/codegen/src/machinst/vcode.rs:1150]: That is a great point you bring up.

> if we have one jump instruction (and nothing else) in the first block; MachBuffer will never chomp e.g. a cond+uncond pair to nothing. In the single-jump-inst case, that inst also has an offset of 0 so it's still monotonic.

Am I right to understand that this is because of the VCode construction? I considered:
```
Block0:
  jmp Block1
  jmp Block1
Block1:

; Which _can_ be simplified down to nothing.
```
I was writing the comment as follows, does that match your expectation?
```
// Not all instructions get their offsets recorded. As for the case where
// the offset is legitimately zero (first instruction), we are guaranteed
// that no more than one prior jump (which would also have been at a zero
// offset) could have been removed because the first block will not have
// multiple jumps.
```

Comment (cfallin) [reply cranelift/codegen/src/machinst/vcode.rs:1150]: I would replace the last bit with "... because either the first block will not have multiple branches, or else it would not have been completely elided."

This is related to your example: no block will have two unconditional branches; we emit only one "terminator" VCode instruction per block, and those are either one uncond, or a two-target form that is cond+uncond (or switch or ret, both of which are indirect).

(Additional subtlety just to allay any confusion: some pseudoinsts *do* emit branch insts internally, but those are completely invisible to the MachBuffer (i.e., not reported).)

Comment (SingleAccretion) [reply cranelift/codegen/src/machinst/vcode.rs:1150]: I've thought about this some more, and became less convinced it's a correct assumption. Consider:
```
Block0:
  jmp Block2
Block1:
  jmp Block2
Block2:
```
(This can be fixed in a more obvious matter by using not-zero for the distinguished "invalid offset" value)

Comment (cfallin) [reply cranelift/codegen/src/machinst/vcode.rs:1150]: Ah! Yes, indeed, that's the far more sensible solution. (One might be tempted to make it a `Vec<Option<CodeOffset>>` but for memory-efficiency let's define a sentinel value e.g. `const NO_INST_OFFSET: CodeOffset = u32::MAX` maybe?)

File: tests/all/debug/lldb.rs [hunk 3]
```diff
@@ -169,3 +174,31 @@ check: resuming
     )?;
     Ok(())
 }
+
+#[test]
+#[ignore]
+#[cfg(all(
+    any(target_os = "linux", target_os = "macos"),
```
[the remark this answers is not in the document]
Comment (fitzgen) [reply tests/all/debug/lldb.rs:181]: Yeah it is a bit funky, but these tests are only force-enabled in some CI configurations.

**Review by cfallin — APPROVED** [review]
Latest changes LGTM to me -- thanks very much for this!
