### PR TITLE
s390x: Move the value out of the casloop_val_reg with mov_preg

### LINKED ISSUE #5425: Cranelift: s390x: regalloc checker error UnknownValueInAllocation
### Steps to Reproduce

* Try compiling the rust standard library for s390x using the upcoming 0.91 Cranelift release.

I can create a minimal reproducing example later if requested.

### Expected Results

It compiles fine.

### Actual Results

```
thread '<unnamed>' panicked at 'register allocation checker: CheckerErrors { errors: [UnknownValueInAllocation { inst: Inst(58), op: Use: v0i fixed(p0i), alloc: p0i }, UnknownValueInAllocation { inst: Inst(58), op: Use: v0i fixed(p0i), alloc: p0i }, IncorrectValuesInAllocation { inst: Inst(60), op: Use: v187i reg, alloc: p2i, actual: {} }] }', /home/runner/.cargo/git/checkouts/wasmtime-41807828cb3a7a7e/63a3951/cranelift/codegen/src/machinst/compile.rs:88:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/37d7de337903a558dbeb1e82c844fe915ab8ff25/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/37d7de337903a558dbeb1e82c844fe915ab8ff25/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/37d7de337903a558dbeb1e82c844fe915ab8ff25/library/core/src/result.rs:1791:5
   3: cranelift_codegen::machinst::compile::compile
   4: <cranelift_codegen::isa::s390x::S390xBackend as cranelift_codegen::isa::TargetIsa>::compile_function
   5: cranelift_codegen::context::Context::compile_stencil
   6: cranelift_codegen::context::Context::compile
   7: cranelift_codegen::context::Context::compile_and_emit
   8: <cranelift_object::backend::ObjectModule as cranelift_module::module::Module>::define_function
   9: rustc_codegen_cranelift::base::compile_fn
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Versions and Environment

Cranelift version or commit: https://github.com/bytecodealliance/wasmtime/commit/63a39511b65a2c8ad3d77b580236532dffc98b62 (upcoming 0.91 Cranelift release / 4.0 Wasmtime release)

Operating system: Linux

Architecture: cross-compiling to s390x

### Extra Info

cc @uweigand

### PR DESCRIPTION
**Pull request by elliottt**
The `casloop_emit` function in the s390x backend was using the fixed non-allocatable register `%r0` directly with move instructions, which produced a panic in the regalloc2 checker (#5425). This PR changes the `casloop_result` function to use `mov_preg` instead of `copy_reg` to fetch the result, as it's not viewed by regalloc2 as a move.

Fixes #5425

### CODE REVIEW

File: cranelift/codegen/src/machinst/vcode.rs [hunk 1]
```diff
@@ -568,13 +568,21 @@ impl<I: VCodeInst> VCodeBuilder<I> {
...
-                let src = Operand::reg_use(Self::resolve_vreg_alias_impl(vreg_aliases, src.into()));
-                let dst = Operand::reg_def(Self::resolve_vreg_alias_impl(
-                    vreg_aliases,
-                    dst.to_reg().into(),
-                ));
-                // Note that regalloc2 requires these in (src, dst) order.
-                self.vcode.is_move.insert(InsnIndex::new(i), (src, dst));
+                // As we only use real registers with reg_fixed_def/reg_fixed_use constraints, the
+                // only situation where we would find a real register here is if it came from a
+                // reg_fixed_nonallocatable constraint. Don't add the alias at this point, as that
```
Comment (cfallin) [inline cranelift/codegen/src/machinst/vcode.rs:573]: s/alias/move/ -- "aliases" are what are used to make one vreg resolve to another (so that result vregs can be rewritten to the temp vregs returned by the toplevel lowering entry point), and imply a "timeless" equivalence, while "moves" are specific copy operations that occur in program flow. (Likewise the title of this PR/commit should change)

**Review by cfallin — APPROVED** [review]
LGTM, with nit below. Thanks for tracking this down!

I also think we should have an assert in RA2 to catch this case and explicitly disallow it; but that can happen off the critical path here.

**Comment by elliottt** [comment]
Looks like this isn't quite solved yet: the s390x tests that are failing are due to not recording an entry in the `is_move` map of the vcode table for the move that puts the result of the `atomic_rmw` instruction into `%r2` before returning.

Attempting a local fix by recording `Operand::fixed_nonallocatable` constraints in `is_move` when appropriate instead of avoiding adding an entry at all hits a bug in regalloc2 where we're assuming that a fixed constraint returned by `is_move` must always be a pinned vreg, and not a fixed-nonallocatable register.

File: cranelift/codegen/src/machinst/vcode.rs [hunk 2]
```diff
@@ -910,7 +918,7 @@ impl<I: VCodeInst> VCode<I> {
                             }
                         }
 
-                        if self.insts[iix.index()].is_move().is_some() {
+                        if self.is_move.contains_key(&iix) {
```
Comment (elliottt) [inline cranelift/codegen/src/machinst/vcode.rs:921]: Reusing the cached decision about what instruction is a move meant that we keep the move instructions that involve fixed non-allocatable registers in the final assembly.

File: cranelift/filetests/filetests/isa/s390x/atomic_rmw.clif [hunk 3]
```diff
@@ -573,7 +573,7 @@ block0(v0: i64, v1: i64, v2: i32):
 ; block0:
 ;   l %r0, 0(%r3)
 ;   0: clr %r4, %r0 ; jgnh 1f ; cs %r0, %r4, 0(%r3) ; jglh 0b ; 1:
-;   lgr %r2, %r0
+;   lr %r2, %r0
```
Comment (elliottt) [inline cranelift/filetests/filetests/isa/s390x/atomic_rmw.clif:576]: @uweigand would you mind checking these move changes? They all seemed reasonable to me, as the result of each function is `i32`.

**Comment by elliottt** [comment]
The last problem here was that moves weren't making it into the final output. The problem was that in the `VCode::emit` function we were skipping all instructions that satisfied `MachInst::is_move`, which includes the moves that we didn't report to regalloc2. The solution was to reuse the `VCode::is_move` map rather than calling `MachInst::is_move`, as presence in that map corresponds directly to whether or not we told regalloc2 about the move.

**Review by cfallin — CHANGES_REQUESTED** [review]
Actually, reading your latest update: I think that what is actually needed here is for `MachInst::is_move()` to return a correct result with respect to real/virtual registers. Otherwise we have an inconsistency that may cause issues elsewhere (and are not addressed by papering over one callsite to `MachInst::is_move` with alternative logic).

**Comment by elliottt** [comment]
@uweigand I've reworked this a bit more to avoid the changes to VCode. The problem was that there was a move using a fixed non-allocatable register produced by the s390x backend in the `casloop_emit` function. I've reworked this to use `MovPReg`, which is designed to handle fixed non-allocatable sources, but this does introduce some additional indirection for the result.

**Comment by elliottt** [comment]
> Actually, reading your latest update: I think that what is actually needed here is for `MachInst::is_move()` to return a correct result with respect to real/virtual registers. Otherwise we have an inconsistency that may cause issues elsewhere (and are not addressed by papering over one callsite to `MachInst::is_move` with alternative logic).

The changes to `VCode` and `MachInst` ended up being a red-herring: the real problem as we discussed in a DM was that there were move instructions emitted that were using fixed non-allocatable registers at all. Switching to `MInst.MovPreg` instead in the s390x backend was the best fix.

**Review by cfallin — APPROVED** [review]
LGTM, thanks!

Just one nit before merging if you don't mind: could we add an assert in `collect_operands` (or somewhere else appropriate) where we invoke `is_move()` to check that the src and dest of any program move is a virtual register?

File: cranelift/codegen/src/isa/s390x/inst.isle [hunk 4]
```diff
@@ -3424,17 +3427,17 @@
             ;; Emit initial load followed by compare-and-swap loop.
             (_ Unit (emit_load (ty_ext32 ty) (casloop_val_reg) aligned_mem))
             (_ Unit (emit_loop ib (intcc_as_cond (IntCC.NotEqual)))))
-        result))
+        (preg_gpr_0)))
```
Comment (uweigand) [inline cranelift/codegen/src/isa/s390x/inst.isle:3430]: This a bit iffy, in that it's not guaranteed (at least, that wasn't the intention) that `result` *must* be GPR 0 here.  I think in practice it (nearly?) always is, but it still would be better to at least verify.

File: cranelift/codegen/src/isa/s390x/inst.isle [hunk 5]
```diff
@@ -3424,17 +3427,17 @@
...
 ;; copied out of the hard register.  In the little-endian case, we need to
 ;; byte-swap since the compare-and-swap instruction is always big-endian.
-(decl casloop_result (Type MemFlags Reg) Reg)
+(decl casloop_result (Type MemFlags PReg) Reg)
 (rule 1 (casloop_result (ty_32_or_64 ty) (bigendian) result)
-      (copy_reg ty result))
+      (mov_preg result))
 (rule (casloop_result (ty_32_or_64 ty) (littleendian) result)
-      (bswap_reg ty result))
+      (bswap_reg ty (mov_preg result)))
```
Comment (uweigand) [inline cranelift/codegen/src/isa/s390x/inst.isle:3440]: I'm confused about the exact rules when/which instructions are allowed to refer to non-allocatable fixed registers.  It seems the load before loop (loading into %r0) is OK, but the move is problematic (which I understand is because regalloc handles moves specially).

But is it OK to have a fixed register as source of the bswap instruction?  If so, we wouldn't have to incur this performance regression.  In fact, if *only* moves are the problem, maybe the fix could be as simple as having a special-cased rule for `copy_reg` that detects that the source is a fixed register and uses mov_preg instead?

**Review by uweigand — COMMENTED** [review]
Thanks for tracking this down!   A couple comments on the PR inline.

File: cranelift/codegen/src/isa/s390x/inst.isle (hunk 5 above)
Comment (elliottt) [reply cranelift/codegen/src/isa/s390x/inst.isle:3440]: That's a good point: moves are indeed the case that we need to avoid, and it should be fine for the bswap instruction to take a fixed non-allocatable input. I'll fix this up, thanks!

File: cranelift/codegen/src/isa/s390x/inst.isle (hunk 4 above)
Comment (elliottt) [reply cranelift/codegen/src/isa/s390x/inst.isle:3430]: I'll verify that it's always used with gpr 0, and add a comment explaining why we return it there if that's the case.

**Comment by elliottt** [comment]
@cfallin the assertions in `collect_operands` are failing, so I'll open a separate PR with that change and track them down there.

**Comment by bjorn3** [comment]
Will this be backported to the wasmtime-4.0.0 branch?

**Comment by elliottt** [comment]
> Will this be backported to the wasmtime-4.0.0 branch?

Just made the PR: #5442
