### PR TITLE
Partial support for no_std in cranelift_codegen

### LINKED ISSUE #1158: cranelift-codegen no longer builds with no_std
I've tracked down a few things that are preventing this from happening.

1. `packed_struct` requires std by default
2. There are a few uses of std in `cranelift-codegen` and `cranelift-codegen-shared` that can be replaced with core or alloc.
3. `thiserror` requires std, because the Error trait doesn't exist in core or alloc.

The first two are trivial to fix, and I'll create a PR with those changes in a second.

However, there are 11 uses of the `Display` and `Into<result::CodegenError>` traits that prevent me from placing `thiserror` behind a feature gate, and I'm not sure what to do about them.

<details>
<summary>Here are the 11 things that rely on those traits, as reported by rustc (click to expand)</summary>

    $ cargo build --no-default-features --features core
    Compiling cranelift-codegen v0.51.0 (/home/icydefiance/Documents/code/cranelift/cranelift-codegen)
    error[E0599]: no method named `to_string` found for type `verifier::VerifierError` in the current scope
    --> cranelift-codegen/src/print_errors.rs:218:36
        |
    218 |     writeln!(w, "; error: {}", err.to_string())?;
        |                                    ^^^^^^^^^ method not found in `verifier::VerifierError`
        | 
    ::: cranelift-codegen/src/verifier/mod.rs:138:1
        |
    138 | pub struct VerifierError {
        | ------------------------ method `to_string` not found for this
        |
        = help: items from traits can only be used if the trait is implemented and in scope
        = note: the following trait defines an item `to_string`, perhaps you need to implement it:
                candidate bytecodealliance/cranelift#1: `alloc::string::ToString`

    error[E0599]: no method named `to_string` found for type `result::CodegenError` in the current scope
    --> cranelift-codegen/src/print_errors.rs:227:13
        |
    227 |         err.to_string()
        |             ^^^^^^^^^ method not found in `result::CodegenError`
        | 
    ::: cranelift-codegen/src/result.rs:12:1
        |
    12  | pub enum CodegenError {
        | --------------------- method `to_string` not found for this
        |
        = help: items from traits can only be used if the trait is implemented and in scope
        = note: the following trait defines an item `to_string`, perhaps you need to implement it:
                candidate bytecodealliance/cranelift#1: `alloc::string::ToString`

    error[E0277]: `verifier::VerifierError` doesn't implement `core::fmt::Display`
    --> cranelift-codegen/src/verifier/mod.rs:235:33
        |
    235 |             writeln!(f, "- {}", err)?;
        |                                 ^^^ `verifier::VerifierError` cannot be formatted with the default formatter
        |
        = help: the trait `core::fmt::Display` is not implemented for `verifier::VerifierError`
        = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
        = note: required because of the requirements on the impl of `core::fmt::Display` for `&verifier::VerifierError`
        = note: required by `core::fmt::Display::fmt`

    error[E0277]: the trait bound `result::CodegenError: core::convert::From<verifier::VerifierErrors>` is not satisfied
    --> cranelift-codegen/src/context.rs:224:30
        |
    224 |             self.verify(fisa)?;
        |                              ^ the trait `core::convert::From<verifier::VerifierErrors>` is not implemented for `result::CodegenError`
        |
        = note: required by `core::convert::From::from`

    error[E0277]: the trait bound `result::CodegenError: core::convert::From<verifier::VerifierErrors>` is not satisfied
    --> cranelift-codegen/src/context.rs:244:39
        |
    244 |             self.verify_locations(isa)?;
        |                                       ^ the trait `core::convert::From<verifier::VerifierErrors>` is not implemented for `result::CodegenError`
        |
        = note: required by `core::convert::From::from`

    error[E0277]: the trait bound `result::CodegenError: core::convert::From<verifier::VerifierErrors>` is not satisfied
    --> cranelift-codegen/src/regalloc/context.rs:111:28
        |
    111 |                 return Err(errors.into());
        |                            ^^^^^^^^^^^^^ the trait `core::convert::From<verifier::VerifierErrors>` is not implemented for `result::CodegenError`
        |
        = note: required because of the requirements on the impl of `core::convert::Into<result::CodegenError>` for `verifier::VerifierErrors`

    error[E0277]: the trait bound `result::CodegenError: core::convert::From<verifier::VerifierErrors>` is not satisfied
    --> cranelift-codegen/src/regalloc/context.rs:139:28
        |
    139 |                 return Err(errors.into());
        |                            ^^^^^^^^^^^^^ the trait `core::convert::From<verifier::VerifierErrors>` is not implemented for `result::CodegenError`
        |
        = note: required because of the requirements on the impl of `core::convert::Into<result::CodegenError>` for `verifier::VerifierErrors`

    error[E0277]: the trait bound `result::CodegenError: core::convert::From<verifier::VerifierErrors>` is not satisfied
    --> cranelift-codegen/src/regalloc/context.rs:168:28
        |
    168 |                 return Err(errors.into());
        |                            ^^^^^^^^^^^^^ the trait `core::convert::From<verifier::VerifierErrors>` is not implemented for `result::CodegenError`
        |
        = note: required because of the requirements on the impl of `core::convert::Into<result::CodegenError>` for `verifier::VerifierErrors`

    error[E0277]: the trait bound `result::CodegenError: core::convert::From<verifier::VerifierErrors>` is not satisfied
    --> cranelift-codegen/src/regalloc/context.rs:196:28
        |
    196 |                 return Err(errors.into());
        |                            ^^^^^^^^^^^^^ the trait `core::convert::From<verifier::VerifierErrors>` is not implemented for `result::CodegenError`
        |
        = note: required because of the requirements on the impl of `core::convert::Into<result::CodegenError>` for `verifier::VerifierErrors`

    error[E0277]: the trait bound `result::CodegenError: core::convert::From<verifier::VerifierErrors>` is not satisfied
    --> cranelift-codegen/src/regalloc/context.rs:239:28
        |
    239 |                 return Err(errors.into());
        |                            ^^^^^^^^^^^^^ the trait `core::convert::From<verifier::VerifierErrors>` is not implemented for `result::CodegenError`
        |
        = note: required because of the requirements on the impl of `core::convert::Into<result::CodegenError>` for `verifier::VerifierErrors`

    error[E0277]: the trait bound `result::CodegenError: core::convert::From<verifier::VerifierErrors>` is not satisfied
    --> cranelift-codegen/src/regalloc/context.rs:248:17
        |
    248 |             Err(errors.into())
        |                 ^^^^^^^^^^^^^ the trait `core::convert::From<verifier::VerifierErrors>` is not implemented for `result::CodegenError`
        |
        = note: required because of the requirements on the impl of `core::convert::Into<result::CodegenError>` for `verifier::VerifierErrors`

    error: aborting due to 11 previous errors

    Some errors have detailed explanations: E0277, E0599.
    For more information about an error, try `rustc --explain E0277`.
    error: could not compile `cranelift-codegen`.

    To learn more, run the command again with --verbose.
</details>

Additional info:
* The author of `thiserror` doesn't want to add a feature-gate for just the Error trait, but it's possible to provide another implementation of Display (and presumably Into). dtolnay/thiserror#43
* There was some discussion of moving Error to alloc, and a PR was even created to do so, but it was closed because [RFC 2504](https://rust-lang.github.io/rfcs/2504-fix-error.html) will add backtrace functionality that requires std.

### PR DESCRIPTION
**Pull request by the-ssd**
Used to close #1158, allows for cranelift to be used in a no_std environment, like a kernel.

There is already #9007, which stalled.

And I am at a point I think it makes sense to ask someone what do you want to be done about FxHashMap and OnceLock. There are alternative crates that implement it, like [this one (also has a comparison chart)](https://github.com/phil-opp/once_cell_no_std).

What is left to do:
- [x] isle codegen generates code that depends on no_std, solved in the previous PR (https://github.com/bytecodealliance/wasmtime/pull/9007/files#diff-0496ab91e0634653bd3d4295c7aa90e3f06b0c5f462332db0997a22f294cbf94)
- [x] separate PRs for: cranelift_assembler_x86 (#12235), moving large parts to core and alloc (#12237), and isle (#12236)
- [x] FxHashMap
- [x] floating point issues
- [ ]  OnceLock (sort of)
- [ ] CI
- [x] libm: roundeven has a typo in it's implementation https://github.com/rust-lang/compiler-builtins/pull/1053, so a hack is used, waiting for libm to be published to crates.io

### CODE REVIEW

**Comment by the-ssd** [comment]
I found something that might be useful.

https://rust-lang.github.io/rust-clippy/master/#std_instead_of_core
https://rust-lang.github.io/rust-clippy/master/#alloc_instead_of_core
https://rust-lang.github.io/rust-clippy/master/#std_instead_of_alloc
     
[source](https://gist.github.com/tdelabro/b2d1f2a0f94ceba72b718b92f9a7ad7b)

File: cranelift/codegen/src/ir/immediates.rs [hunk 1]
```diff
@@ -682,28 +684,28 @@ macro_rules! ieee_float {
...
                 pub fn trunc(self) -> Self {
-                    Self::with_float(self.$as_float().trunc())
+                    Self::with_float(Libm::<$float_ty>::trunc(self.$as_float()))
                 }
 
                 /// Returns the nearest integer to `self`. Rounds half-way cases to the number
                 /// with an even least significant digit.
                 pub fn round_ties_even(self) -> Self {
-                    Self::with_float(self.$as_float().round_ties_even())
+                    Self::with_float(libm::generic::rint_round(self.$as_float(), libm::support::Round::Nearest).val)
```
Comment (the-ssd) [inline cranelift/codegen/src/ir/immediates.rs]: When https://github.com/rust-lang/compiler-builtins/pull/1053 is merged, feature `unstable-public-internals` can be removed, and this changed to `Libm::<$float_ty>::roundeven`

**Comment by the-ssd** [comment]
I've removed OnceLock, but MachineEnv is now recomputed each time.

**Comment by the-ssd** [comment]
`core` feature can be removed

**Comment by the-ssd** [comment]
Diff is a bit weird, it thinks there are more changes than there should be, should I squash the commits myself?

**Comment by the-ssd** [comment]
https://github.com/gimli-rs/gimli/pull/855
maybe even `unwind` can be supported on no_std.

File: Cargo.toml [hunk 2]
```diff
@@ -50,7 +50,10 @@ wasmtime-cranelift = { workspace = true, optional = true }
 wasmtime-environ = { workspace = true }
 wasmtime-explorer = { workspace = true, optional = true }
 wasmtime-wast = { workspace = true, optional = true }
-wasi-common = { workspace = true, default-features = true, features = ["exit", "tokio"], optional = true }
+wasi-common = { workspace = true, default-features = true, features = [
+  "exit",
+  "tokio",
+], optional = true }
```
Comment (alexcrichton) [inline Cargo.toml]: Mind backing out formatting-related changes in this file to make it easier to see what's actually changing?

File: cranelift/codegen/src/prelude.rs [hunk 3]
```diff
@@ -0,0 +1,2 @@
+pub use alloc::format;
+pub use alloc::vec;
```
Comment (alexcrichton) [inline cranelift/codegen/src/prelude.rs]: This is a pretty small prelude module so ideally we wouldn't need it. I think that a `#[macro_use]` on the `extern crate alloc` in this crate might remove the need for these?

File: cranelift/codegen/src/isa/x64/abi.rs [hunk 4]
```diff
@@ -873,13 +873,11 @@ impl ABIMachineSpec for X64ABIMachineSpec {
...
+    fn get_machine_env(flags: &settings::Flags, _call_conv: isa::CallConv) -> MachineEnv {
         if flags.enable_pinned_reg() {
-            static MACHINE_ENV: OnceLock<MachineEnv> = OnceLock::new();
-            MACHINE_ENV.get_or_init(|| create_reg_env_systemv(true))
+            create_reg_env_systemv(true)
         } else {
-            static MACHINE_ENV: OnceLock<MachineEnv> = OnceLock::new();
-            MACHINE_ENV.get_or_init(|| create_reg_env_systemv(false))
+            create_reg_env_systemv(false)
         }
```
Comment (alexcrichton) [inline cranelift/codegen/src/isa/x64/abi.rs:883]: Would you be ok splitting this out to a separate PR? For example landing everything else in this PR except the CI changes + this `get_machine_env` change? This is something we'll need to fix one way or another I believe since IIRC historical benchmarking showed that is needs to be not-created-every-time-on-use.

File: cranelift/codegen/Cargo.toml [hunk 5]
```diff
@@ -30,20 +30,21 @@ cranelift-entity = { workspace = true }
...
 postcard = { workspace = true, optional = true }
-gimli = { workspace = true, features = ["write", "std"], optional = true }
+gimli = { workspace = true, features = ["write"], optional = true }
 smallvec = { workspace = true }
 regalloc2 = { workspace = true, features = ["checker"] }
 souper-ir = { version = "2.1.0", optional = true }
 sha2 = { version = "0.10.2", optional = true }
 rustc-hash = { workspace = true }
 wasmtime-math = { workspace = true }
+libm = { workspace = true, features = ["unstable-public-internals"] }
```
Comment (alexcrichton) [inline cranelift/codegen/Cargo.toml]: Given the name of this feature, this doesn't seem like something we should be relying on?

Comment (the-ssd) [reply cranelift/codegen/Cargo.toml]: Yes, it's temporary, until next version of libm is released. Because of a typo a function is call roundeven for f32 and roundevem for f64. I wasn't sure how to work around it with the macro without changing inputs. PR that fixes the typo was already merged

File: cranelift/codegen/src/prelude.rs (hunk 3 above)
Comment (the-ssd) [reply cranelift/codegen/src/prelude.rs]: Oh, ok let me check

File: cranelift/codegen/src/isa/x64/abi.rs (hunk 4 above)
Comment (the-ssd) [reply cranelift/codegen/src/isa/x64/abi.rs:883]: I actually only started it becase of this https://github.com/bytecodealliance/wasmtime/pull/8489#issuecomment-2105129901. Either way moving it to a separate PR makes sense

File: cranelift/codegen/Cargo.toml (hunk 5 above)
Comment (alexcrichton) [reply cranelift/codegen/Cargo.toml]: While we're waiting for that to merge, could Cranelift be updated to avoid using the `Libm` trait? That would enable being able to land this and use it sooner

File: cranelift/codegen/src/machinst/vcode.rs [hunk 6]
```diff
@@ -1277,6 +1277,9 @@ impl<I: VCodeInst> VCode<I> {
                 let slot = alloc.as_stack().unwrap();
                 let slot_offset = self.abi.get_spillslot_offset(slot);
                 let slot_base_to_caller_sp_offset = self.abi.slot_base_to_caller_sp_offset();
+                #[cfg(not(feature = "unwind"))]
+                let caller_sp_to_cfa_offset = 0;
```
Comment (the-ssd) [inline cranelift/codegen/src/machinst/vcode.rs]: Unsure if this is correct, function always returns 0

File: cranelift/codegen/src/prelude.rs (hunk 3 above)
Comment (the-ssd) [reply cranelift/codegen/src/prelude.rs]: Done

File: cranelift/codegen/Cargo.toml (hunk 5 above)
Comment (the-ssd) [reply cranelift/codegen/Cargo.toml]: `Libm` trait is stable, and it simplifies it, because libm has separate functions for f32, and f64.
Since it is already merged, git version can be used, or round_ties_even can be left unchanged, and fixed in a later PR, when new libm version is published.

Basically `unstable-public-internals` is only needed for round_ties_even

File: cranelift/codegen/src/isa/x64/abi.rs (hunk 4 above)
Comment (the-ssd) [reply cranelift/codegen/src/isa/x64/abi.rs:883]: reverted

File: cranelift/codegen/Cargo.toml (hunk 5 above)
Comment (the-ssd) [reply cranelift/codegen/Cargo.toml]: I updated it and added a comment explaining why it wasn't changed

Comment (the-ssd) [reply cranelift/codegen/Cargo.toml]: https://github.com/rust-lang/compiler-builtins/pull/935 this is the blocker

File: Cargo.toml [hunk 7]
```diff
@@ -322,7 +322,7 @@ component-async-tests = { path = "crates/misc/component-async-tests" }
 
 # Bytecode Alliance maintained dependencies:
 # ---------------------------
-regalloc2 = "0.13.3"
+regalloc2 = { version = "0.13.3", default-features = false }
```
Comment (alexcrichton) [inline Cargo.toml]: As a heads up, I've sent https://github.com/bytecodealliance/regalloc2/pull/250 which would obsolete this, but this is fine to leave as-is in the meantime.

**Review by alexcrichton — APPROVED** [review]

File: cranelift/codegen/src/machinst/vcode.rs (hunk 6 above)
Comment (alexcrichton) [reply cranelift/codegen/src/machinst/vcode.rs]: cc @cfallin should this perhaps `continue` to skip this value? Or `panic!` since this should be unreachable? Or is 0 ok to leave in?

File: cranelift/codegen/Cargo.toml (hunk 5 above)
Comment (alexcrichton) [reply cranelift/codegen/Cargo.toml]: We unfortunately can't use git deps in Wasmtime for published crates, and we can't land dependencies on internal features, even if temporary, in case that ends up accidentally making its way to a release branch. Leaving as-is is ok for now, but it might be possible to do some macro/float trickery to avoid blocking on a compiler-builtins update for this

File: cranelift/codegen/src/machinst/vcode.rs (hunk 6 above)
Comment (cfallin) [reply cranelift/codegen/src/machinst/vcode.rs]: Yes, if we don't have `unwind` then we don't have the appropriate metadata to allow a native debugger to interpret frames anyway, so we should `continue`. I'm a bit curious how this built in a non-`unwind` build before -- or was that broken because `std` always enabled `unwind`?

Comment (the-ssd) [reply cranelift/codegen/src/machinst/vcode.rs]: It was broken

File: Cargo.toml (hunk 7 above)
Comment (cfallin) [reply Cargo.toml]: @the-ssd Updating to `version = "0.13.4"` should now pull in Alex's change.

File: cranelift/codegen/src/machinst/vcode.rs (hunk 6 above)
Comment (cfallin) [reply cranelift/codegen/src/machinst/vcode.rs]: @the-ssd OK, yep, let's do a `continue` in this case.

File: cranelift/codegen/src/isa/x64/abi.rs (hunk 4 above)
Comment (cfallin) [reply cranelift/codegen/src/isa/x64/abi.rs:883]: @the-ssd if you're willing to do a little more hacking, [jameysharp's idea here](https://github.com/bytecodealliance/wasmtime/pull/8489#issuecomment-2106379885) is probably the best way to remove the need to cache the `MachineEnv` at all (in a separate set of PRs of course). It would involve a change to RA2's API then an update to Cranelift to use statically-defined `MachineEnv`s. I have specific ideas on how to consume a `PRegSet` for the register iterator on the RA2 side if you're interested -- I'll file an issue over there.

Comment (cfallin) [reply cranelift/codegen/src/isa/x64/abi.rs:883]: I wrote up bytecodealliance/regalloc2#252 for this.

File: Cargo.toml (hunk 7 above)
Comment (the-ssd) [reply Cargo.toml]: updated

File: cranelift/codegen/Cargo.toml (hunk 5 above)
Comment (the-ssd) [reply cranelift/codegen/Cargo.toml]: I've removed that feature and instead wrote this
```rust
// TODO: when libm v0.2.16 is published line below can be used instead
// Self::with_float(Libm::<$float_ty>::roundeven(self.$as_float()))
Self::with_float(self.$as_float().round_ties_even())
```

File: cranelift/codegen/src/machinst/vcode.rs (hunk 6 above)
Comment (the-ssd) [reply cranelift/codegen/src/machinst/vcode.rs]: Can you check if I did it correctly?
It just looks a bit wrong, like there has to be a better solution

Comment (alexcrichton) [reply cranelift/codegen/src/machinst/vcode.rs]: Looks good to me!

**Comment by tgross35** [comment]
> * [x]  libm: roundeven has a typo in it's implementation [Fix a typo in `libm::Libm::roundeven` rust-lang/compiler-builtins#1053](https://github.com/rust-lang/compiler-builtins/pull/1053), so a hack is used, waiting for libm to be published to crates.io

FYI since I noticed the crosslink, this was released in https://github.com/rust-lang/compiler-builtins/releases/tag/libm-v0.2.16
