### PR TITLE
egraphs: don't let rematerialization override LICM.

### LINKED ISSUE #7283: Cranelift sinking loop-invariant code into a loop
Given this input CLIF:

```clif
function %foo(i64, i64) {
block0(v0: i64, v1: i64):
    ;; Create a loop-invariant value `v10` which is some operation which
    ;; includes a constant somewhere.
    v8 = load.f64 v0+100
    v9 = f64const 0x1.0000000000000p1
    v10 = fdiv v8, v9

    ;; jump to the loop
    v3 = iconst.i64 0
    jump block2(v3)  ; v3 = 0

block2(v11: i64):
    ;; store the loop-invariant `v10` to memory "somewhere"
    v15 = iadd v0, v11
    store.f64 v10, v15

    ;; loop breakout condition
    v17 = iadd_imm v11, 1
    v19 = icmp_imm ne v17, 100
    brif v19, block2(v17), block1

block1:
    return
}
```

this will currently optimize as:

```
$ cargo run compile -p ./foo.clif --target aarch64 --set opt_level=speed
function %foo(i64, i64) fast {
block0(v0: i64, v1: i64):
    v8 = load.f64 v0+100
    v3 = iconst.i64 0
    jump block2(v3)  ; v3 = 0

block2(v11: i64):
    v9 = f64const 0x1.0000000000000p1
    v10 = fdiv.f64 v8, v9  ; v9 = 0x1.0000000000000p1
    v15 = iadd.i64 v0, v11
    store v10, v15
    v20 = iconst.i64 1
    v17 = iadd v11, v20  ; v20 = 1
    v21 = iconst.i64 100
    v19 = icmp ne v17, v21  ; v21 = 100
    brif v19, block2(v17), block1

block1:
    return
}
```

This notably sinks the `fdiv` operation, which is loop invariant and originally outside of the loop, into the loop.

After debugging with @elliottt the reason this seems to be happening is that during elaboration to elaborate the `fdiv` instruction it first elaborates the inputs to the `fdiv` instruction. When doing so one of the inputs is an `f64const` which is rematerializable, meaning that the constant value is materialized inside of the loop. Next when elaborating `fdiv` it sees that one of its inputs is inside of the loop, so it concludes that the `fdiv` must also itself be inside of the loop. Put another way the rematerialization of the constant argument additionally forces the `fdiv` to go inside of the loop. This hypothesis was tested by [commenting out these lines](https://github.com/bytecodealliance/wasmtime/blob/5c7ed43058fd8bc3122b20debe712c9cbfecf9f2/cranelift/codegen/src/opts/remat.isle#L28-L31) which avoided putting the `fdiv` into the loop. This isn't a complete fix, however, because rematerialized integer constants would still cause integer operations to be sunk into loops erroneously.

I remember first noticing this behavior in an [older issue](https://github.com/bytecodealliance/wasmtime/issues/7085) about false dependencies where a division operation was sunk into a loop, although the performance regression in that issue was due to something else. @elliottt's and my investigation of https://github.com/bytecodealliance/wasmtime/issues/7246 however turned up that this sinking is the cause of the slowdown there. The `vdivsd` instruction is present in the loop when in the original wasm the `f64.div` was not present in the loop. The above commenting of `remat.isle` rules improves the runtime performance of that test case to be as expected.

cc @elliottt and @cfallin as y'all are likely interested in this.

### PR DESCRIPTION
**Pull request by cfallin**
This reworks the way that remat and LICM interact during aegraph elaboration. In principle, both happen during the same single-pass "code placement" algorithm: we decide where to place pure instructions (those that are eligible for movement), and remat pushes them one way while LICM pushes them the other.

The interaction is a little more subtle than simple heuristic priority, though -- it's really a decision ordering issue. A remat'd value wants to sink as deep into the loop nest as it can (to the use's block), but we don't know *where* the uses go until we process them (and make LICM-related choices), and we process uses after defs during elaboration. Or more precisely, we have some work at the use before recursively processing the def, and some work after the recursion returns; and the LICM decision happens after recursion returns, because LICM wants to know where the defs are to know how high we can hoist. (The recursion is itself unrolled into a state machine on an explicit stack so that's a little hard to see but that's what is happening in principle.)

The solution here is to make remat a separate just-in-time thing, once we have arg values. Just before we plug the final arg values into the elaborated instruction, we ask: is this a remat'd value, and if so, do we have a copy of the computation in this block yet. If not, we make one. This has to happen in two places (the main elab loop and the toplevel driver from the skeleton).

The one downside of this solution is that it doesn't handle *recursive* rematerialization by default. This means that if we, for example, decide to remat single-constant-arg adds (as we actually do in our current rules), we won't then also recursively remat the constant arg to those adds. This can be seen in the `licm.clif` test case. This doesn't seem to be a dealbreaker to me because most such cases will be able to fold the constants anyway (they happen mostly because of pointer pre-computations: a loop over structs in Wasm computes heap_base + p + offset, and naive LICM pulls a `heap_base + offset` out of the loop for every struct field accessed in the loop, with horrible register pressure resulting; that's why we have that remat rule. Most such offsets are pretty small.).

Fixes #7283.

### CODE REVIEW

File: cranelift/codegen/src/fx.rs [hunk 1]
```diff
@@ -14,7 +14,6 @@ use super::{HashMap, HashSet};
 use core::default::Default;
 use core::hash::{BuildHasherDefault, Hash, Hasher};
 use core::ops::BitXor;
-
```
Comment (elliottt) [inline cranelift/codegen/src/fx.rs:17]: Would you mind reverting this change? I like the space between the imports and type decls :)

File: cranelift/codegen/src/egraph/elaborate.rs [hunk 2]
```diff
@@ -256,6 +259,45 @@ impl<'a> Elaborator<'a> {
...
+        before: Inst,
+        arg: &mut ElaboratedValue,
+        stats: &mut Stats,
+    ) -> bool {
+        // TODO: we may want to consider recursive rematerialization
+        // as well. We could process the arguments of the
+        // rematerialized instruction up to a certain depth. This
+        // would affect, e.g., adds-with-one-constant-arg, which are
+        // currently rematerialized. Right now we don't do this, to
+        // avoid the need for another fixpoint loop here.
```
Comment (elliottt) [inline cranelift/codegen/src/egraph/elaborate.rs:279]: Would you mind making an issue and referencing it here? This would be nice to track.

File: cranelift/codegen/src/egraph/elaborate.rs [hunk 3]
```diff
@@ -278,39 +320,17 @@ impl<'a> Elaborator<'a> {
...
                     trace!("elaborate: value {} -> best {}", value, best_value);
+                    debug_assert_ne!(best_value, Value::reserved_value());
+
+                    if let Some(elab_val) = self.value_to_elaborated_value.get(&canonical_value) {
+                        // Value is available; use it.
+                        trace!("elaborate: value {} -> {:?}", value, elab_val);
+                        self.stats.elaborate_memoize_hit += 1;
+                        self.elab_result_stack.push(*elab_val);
+                        continue;
+                    }
```
Comment (elliottt) [inline cranelift/codegen/src/egraph/elaborate.rs:332]: I like how much simpler this gets as a result of moving the remat decision to when the args are being processed!

File: cranelift/codegen/src/egraph/elaborate.rs [hunk 4]
```diff
@@ -479,16 +495,39 @@ impl<'a> Elaborator<'a> {
...
+                    // location (just before `before`). Note that
+                    // `inst` may already have been placed somewhere
+                    // else, because a pure node may be elaborated at
+                    // more than one place. In this case, we need to
+                    // duplicate the instruction (and return the
+                    // `Value`s for that duplicated instance instead).
+                    //
+                    // Also clone if we rematerialized, because we
+                    // don't want to rewrite the args in the original
+                    // copy.
```
Comment (elliottt) [inline cranelift/codegen/src/egraph/elaborate.rs:528]: Do we know if there's a single consumer for the value at this point? Would it make sense in the future to only clone when args were rematerialized if there are >1 uses?

**Review by elliottt — APPROVED** [review]
This looks great to me! I had some questions, but none of it should block merging.

File: cranelift/codegen/src/fx.rs (hunk 1 above)
Comment (cfallin) [reply cranelift/codegen/src/fx.rs]: Oops, leftover from some fiddling to get `Entry` before I found another re-export; sorry about that!

File: cranelift/codegen/src/egraph/elaborate.rs (hunk 2 above)
Comment (cfallin) [reply cranelift/codegen/src/egraph/elaborate.rs]: Done! (#7313)

File: cranelift/codegen/src/egraph/elaborate.rs (hunk 3 above)
Comment (cfallin) [reply cranelift/codegen/src/egraph/elaborate.rs:332]: Indeed, it reads much better now!

File: cranelift/codegen/src/egraph/elaborate.rs (hunk 4 above)
Comment (cfallin) [reply cranelift/codegen/src/egraph/elaborate.rs:528]: Unfortunately we don't; and the lazy cloning we use for the main remat loop doesn't work, because while both rewrite args, we rewrite to clones that are not full eclass values (not in the unionfind, not in the extraction tables, etc); so we have to preserve the original. (Discovered the hard way while debugging!)
