### PR TITLE
p3-http: finish `wasi:http@0.3` implementation

### LINKED ISSUE #11631: wasip3: HTTP: content-length handling needs filling out
The `p3_http_outbound_request_content_length` has a few failing conditions and surprising behavior. This is going to be post-https://github.com/bytecodealliance/wasmtime/pull/11440 and I'm filing an issue to track this work.

### PR DESCRIPTION
**Pull request by rvolosatovs**
Follow-up to #11440, refs https://github.com/bytecodealliance/wasmtime/issues/11632

closes #11631 

This makes all the existing p3 test cases pass

### CODE REVIEW

**Comment by rvolosatovs** [comment]
@alexcrichton this is ready for review. I'll address the rest along with the spawned task tracking in yet another follow-up tomorrow (or push here if it's not merged by that time yet)

File: crates/test-programs/src/bin/p3_http_outbound_request_content_length.rs [hunk 1]
```diff
@@ -64,18 +59,15 @@ impl test_programs::p3::exports::wasi::cli::run::Guest for Component {
...
-            drop(res);
+            let _res = handle.expect("failed to send request");
+            transmit.expect("failed to transmit request");
         }
 
         println!("writing too little");
         {
             let (request, mut contents_tx, trailers_tx, transmit) = make_request();
-            let (handle, transmit, ()) = join!(
+            let (_, transmit, ()) = join!(
```
Comment (alexcrichton) [inline crates/test-programs/src/bin/p3_http_outbound_request_content_length.rs]: Could this assert that `handle` is either Ok or Err as appropriate here?

Comment (alexcrichton) [reply crates/test-programs/src/bin/p3_http_outbound_request_content_length.rs]: (same below too)
