### PR TITLE
Cranelift: rework isle-in-source-tree functionality.

### LINKED ISSUE #9625: More context on a cranelift-codegen build script error
Currently if an explicit isle directory is found when the "isle-in-source-tree" feature is not enabled, the following error message is shown by the build script for cranelift-codegen:

```
 --- stderr
  Error: directory isle_generated_code/ exists but is only used when
  `--feature isle-in-source-tree` is specified. To prevent confusion,
  this build script requires the directory to be removed when reverting
  to the usual generated code in target/. Please delete the directory and
  re-run this build.
```
as emitted by [https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/codegen/build.rs#L78C9-L87C10](https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/codegen/build.rs#L78C9-L87C10).

However this is misleading as deleting the `target/` directory (atleast on windows) does not fix the issue. The directory, for me, was located in `%HOME%\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\cranelift-codegen-0.113.1\\isle_generated_code`. Could there possibly be a better check/error message and/or the actual directory located printed out to stderr?

### PR DESCRIPTION
**Pull request by cfallin**
Per #9625 and #9588, a downstream user of Cranelift was misusing the `isle-in-source-tree` feature, enabling it indiscriminately even in published crates (wasmerio/wasmer#5202). This went against the intent of the feature, to be a way for local developers to observe the generated source. As such, it ran afoul of some safety checks for that purpose, and also polluted users' Cargo caches in a way that we cannot now fix except in future releases.

The best we can do is probably to take away features that are liable to be misused. Following discussion in today's Cranelift weekly meeting, we decided to provide this functionality under an environment variable instead. This allows folks who know what they're doing to get the same behavior, but does not expose a feature to crate users.

Fixes #9625.

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]

**Comment by cfallin** [comment]
I think the merge queue run raced with the release; cargo-vet failed because it found a version on crates.io it didn't expect. Re-running, but noting in case we see it again later -- interesting corner case!

File: cranelift/codegen/build.rs [hunk 1]
```diff
@@ -63,37 +63,24 @@ fn main() {
...
-                "Error: directory isle_generated_code/ exists but is only used when\n",
-                "`--feature isle-in-source-tree` is specified. To prevent confusion,\n",
-                "this build script requires the directory to be removed when reverting\n",
-                "to the usual generated code in target/. Please delete the directory and\n",
-                "re-run this build.\n",
-            ));
-            std::process::exit(1);
-        }
-    }
+    let isle_dir = if let Ok(path) = std::env::var("ISLE_SOURCE_DIR") {
```
Comment (bjorn3) [inline cranelift/codegen/build.rs:66]: Shouldn't this use `cargo::rerun-if-env-changed`?
