### PR TITLE
Align functions according to their ISA's requirements

### LINKED ISSUE #4812: x64: Segfaulting rip-relative load due to misalignment
Local bisection points to #4730 for this issue but that seems like it may also be just as likely to expose a preexisting issue. Reproducing this is somewhat nontrivial and `wasm-tools shrink` was pretty unsuccessful on this test case.

[Using this input test case](https://github.com/bytecodealliance/wasmtime/files/9449320/foo.wasm.gz) on an x86_64 machine this crash can be reproduced with:

```
$ cargo run -q \
  run foo.wasm \
  --wasm-features all \
  --enable-cranelift-nan-canonicalization \
  --wasm-timeout 20 \
  -g
zsh: segmentation fault  cargo run -q run $HOME/foo.wasm --wasm-features all  --wasm-timeout 20     -g
```

Note that this reproduction is quite specific to layout of code and the various options enabled here are all required with the input wasm above.

cc @elliottt

### PR DESCRIPTION
**Pull request by elliottt**
Add a `function_alignment` function to the `TargetIsa` trait, and use it to align functions when generating objects. This fixes a bug on x86_64 where rip-relative loads to sse registers could cause a segfault, as functions weren't always guaranteed to be aligned to 16-byte addresses.

Fixes #4812

### CODE REVIEW

File: crates/cranelift/src/obj.rs [hunk 1]
```diff
@@ -95,7 +95,9 @@ impl<'a> ModuleTextBuilder<'a> {
         func: &'a CompiledFunction,
     ) -> (SymbolId, Range<u64>) {
         let body_len = func.body.len() as u64;
-        let off = self.text.append(labeled, &func.body, None);
+        let off = self
+            .text
+            .append(labeled, &func.body, Some(self.isa.function_alignment()));
```
Comment (alexcrichton) [inline crates/cranelift/src/obj.rs:100]: I think this may have actually been the only place that `None` was passed in, so with this changing would it be possible to switch the alignment parameter to `u32` instead of `Option<u32>`?

File: cranelift/codegen/src/isa/x64/mod.rs [hunk 2]
```diff
@@ -157,6 +157,10 @@ impl TargetIsa for X64Backend {
     fn text_section_builder(&self, num_funcs: u32) -> Box<dyn TextSectionBuilder> {
         Box::new(MachTextSectionBuilder::<inst::Inst>::new(num_funcs))
     }
+
+    fn function_alignment(&self) -> u32 {
+        16
```
Comment (alexcrichton) [inline cranelift/codegen/src/isa/x64/mod.rs:162]: Could you leave a comment here for why this is 16? (reading this in isolation I'd naively expect it to be 1)

**Review by alexcrichton — APPROVED** [review]

File: cranelift/codegen/src/isa/mod.rs [hunk 3]
```diff
@@ -277,6 +277,9 @@ pub trait TargetIsa: fmt::Display + Send + Sync {
     /// will be "labeled" or might have calls between them, typically the number
     /// of defined functions in the object file.
     fn text_section_builder(&self, num_labeled_funcs: u32) -> Box<dyn TextSectionBuilder>;
+
+    /// The function alignment required by this ISA.
+    fn function_alignment(&self) -> u32;
```
Comment (bjorn3) [inline cranelift/codegen/src/isa/mod.rs:282]: Can you also use this method in cranelift-object and cranelift-jit?

**Comment by jameysharp** [comment]
Nice, that's surprisingly painless.

Is 16-byte alignment always best? Could we get the maximum alignment of anything in the vcode constant pool instead, and if so, is that extra complexity worth-while?

I suspect we don't care about wasting up to 15 extra bytes in the text section per function, and I know there are sometimes performance advantages to aligning x86 labels to 16-byte boundaries. So I imagine just picking a constant 16-byte alignment is not only good enough, but occasionally helpful. But I'm still curious if there are effects we care about.

File: cranelift/codegen/src/isa/aarch64/mod.rs [hunk 4]
```diff
@@ -178,6 +178,10 @@ impl TargetIsa for AArch64Backend {
     fn map_regalloc_reg_to_dwarf(&self, reg: Reg) -> Result<u16, systemv::RegisterMappingError> {
         inst::unwind::systemv::map_reg(reg).map(|reg| reg.0)
     }
+
+    fn function_alignment(&self) -> u32 {
+        4
```
Comment (cfallin) [inline cranelift/codegen/src/isa/aarch64/mod.rs:183]: I'm wondering if this is enough?

Specifically, couldn't we hit the same bug on aarch64, where:
- We have a constant that needs to be 16-byte-aligned (else fault);
- We 16-align it in the function body;
- But the function is only 4-aligned, and has a starting offset != 0 mod 16.

So I think we need to either set `function_alignment` to the highest alignment statically that we know we use, or compute it dynamically based on the alignments actually present in the constant pool, on every architecture; otherwise we don't satisfy the alignment constraints.

File: cranelift/codegen/src/isa/x64/mod.rs (hunk 2 above)
Comment (elliottt) [reply cranelift/codegen/src/isa/x64/mod.rs:164]: Great point, added!

File: cranelift/codegen/src/isa/mod.rs (hunk 3 above)
Comment (elliottt) [reply cranelift/codegen/src/isa/mod.rs:282]: cranelift-object already has support for specifying function alignment as the `function_alignment` field on `ObjectBuilder`, is that sufficient?

cranelift-jit takes an argument that implements `TargetIsa` already, do we need to modify it to ensure that it's emitting aligned function bodies?

**Comment by elliottt** [comment]
> Nice, that's surprisingly painless.
> 
> Is 16-byte alignment always best? Could we get the maximum alignment of anything in the vcode constant pool instead, and if so, is that extra complexity worth-while?
> 
> I suspect we don't care about wasting up to 15 extra bytes in the text section per function, and I know there are sometimes performance advantages to aligning x86 labels to 16-byte boundaries. So I imagine just picking a constant 16-byte alignment is not only good enough, but occasionally helpful. But I'm still curious if there are effects we care about.

That's what I thought about doing initially, but @alexcrichton pointed out that llvm always aligns functions to 16-byte boundaries, so it seemed easier to do that and potentially waste some bytes.

File: cranelift/codegen/src/isa/aarch64/mod.rs (hunk 4 above)
Comment (elliottt) [reply cranelift/codegen/src/isa/aarch64/mod.rs:183]: That's a good point. I'm going to include the minimum alignment requirement in the output when compiling the function, and then take the max of that and the isa function_alignment when emitting instructions.

File: cranelift/codegen/src/machinst/vcode.rs [hunk 5]
```diff
@@ -219,6 +219,9 @@ pub struct EmitResult<I: VCodeInst> {
 
     /// Stack frame size.
     pub frame_size: u32,
+
+    /// The alignment requirement for pc-relative loads.
+    pub constant_alignment: u32,
```
Comment (cfallin) [inline cranelift/codegen/src/machinst/vcode.rs:224]: Can we call this just `alignment`? From a consumer point of view, the `EmitResult` represents a blob of machine code that has to be placed somewhere, with an alignment specified here; the fact that this alignment requirement comes from our constant pool in this instance is sort of an incidental detail (and there could be other reasons later).

**Review by cfallin — APPROVED** [review]
Thanks! This makes more sense to me; LGTM!

File: cranelift/codegen/src/isa/mod.rs (hunk 3 above)
Comment (elliottt) [reply cranelift/codegen/src/isa/mod.rs:282]: What do you think about removing the `function_alignment` field from `ObjectBuilder` and calling the `function_alignment()` function in `TargetIsa` instead? Also it looks like we'll need to slightly adapt the `Module` trait to pass through the individual function alignment requirements so that we can pick the largest one when emitting machine code. I've made that change on this branch, but held off on removing `function_alignment` from `ObjectBuilder`.

Looking through cranelift-jit, it seems like it always 16-byte aligns functions, so there might not be any work needed there.

**Comment by elliottt** [comment]
Before we merge this:
* @bjorn3 how do the changes to `cranelift-object` and `cranelift-jit` look?
* @uweigand is the default function alignment of 4 bytes for s390x correct?

**Comment by bjorn3** [comment]
For the jit all references to EXECUTABLE_DATA_ALIGNMENT should use this new method. For object there is a reference at https://github.com/bytecodealliance/wasmtime/blob/186c7c3b89c0e172ff39c0126ca71bf9e995dc8c/cranelift/object/src/backend.rs#L351 and equivalent for `define_function`. It needs another `std::cmp::min` wrapper.

**Comment by uweigand** [comment]
> Before we merge this:
>     * @uweigand is the default function alignment of 4 bytes for s390x correct?

The minimum alignment required for *correctness* is just 2 bytes, and this should already come from `isa.symbol_alignment()` as @bjorn3 points out.   That said, having a default alignment of 4 bytes seems reasonable for performance reasons.  (Maybe even higher, but we should do performance measurements first to make sure it's an overall win.  So 4 is good for now.)

File: cranelift/codegen/src/isa/aarch64/mod.rs (hunk 4 above)
Comment (akirilov-arm) [reply cranelift/codegen/src/isa/aarch64/mod.rs:184]: I don't think that this is much of a problem because the only instructions I can think of off the top of my head that have strict alignment requirements are the atomic instructions (or SP-relative operations, but they are not applicable in this case), and it sounds a bit unusual to apply them to literals in the instruction stream. Yes, it is possible to enable alignment checking for almost all relevant instructions, but I am not aware of any platform that does that, and in fact unaligned accesses by default is pretty much an aspect of the ABI at this point.

However, stricter function alignment is in fact recommended for performance reasons, i.e. to maximize fetch bandwidth. The recommendation for some of Arm's recent processors is 32 bytes.

Comment (elliottt) [reply cranelift/codegen/src/isa/aarch64/mod.rs:184]: @akirilov-arm is it worth changing this to `32` here, or should we leave that for another PR?

Comment (akirilov-arm) [reply cranelift/codegen/src/isa/aarch64/mod.rs:184]: Doing it in this PR is fine, but you should add a comment that the value has been chosen for performance reasons; otherwise the correctness requirement is 4 bytes, as in your current code.

Comment (elliottt) [reply cranelift/codegen/src/isa/aarch64/mod.rs]: I changed this to `32` and added a comment, thanks!

**Comment by bjorn3** [comment]
> For follow-on work, would it be reasonable to remove the function_alignment field of the ObjectBuilder in cranelift-object?

I do think so. All it seems to be used for is lucet to set function alignment to 16 bytes, which is exactly what this PR did.
