### PR TITLE
Cranelift AArch64: Fix the VanyTrue implementation for 64-bit elements

### LINKED ISSUE #3305: Cranelift: `vany_true` for `b64x2` produces an illegal instruction on `aarch64`
Hey!

Looks like `vany_true` is producing a wrong instruction for `b64x2`. It works for `b8x16`, `b16x8` and `b32x4`.

### `.clif` Test Case

```
function %vany_true_b64x2() -> b1 {
block0:
    v0 = vconst.b64x2 [false false]
    v1 = vany_true v0
    return v1
}
; run: %vany_true_b64x2() == false
```

### Steps to Reproduce

`clif-util test ./the-above.clif`

### Expected Results

The test to pass

### Actual Results

Qemu crashes with an illegal instruction

```
     Running `qemu-aarch64 -L /usr/aarch64-linux-gnu -E LD_LIBRARY_PATH=/usr/aarch64-linux-gnu/lib /mnt/c/Users/Afonso/CLionProjects/wasmtime/target/aarch64-unknown-linux-gnu/debug/clif-util test ./filetests/filetests/runtes
ts/simd-vanytrue.clif`
skipped ./filetests/filetests/runtests/simd-vanytrue.clif: host can't run X86_64 programs
skipped ./filetests/filetests/runtests/simd-vanytrue.clif: host can't run X86_64 programs
skipped ./filetests/filetests/runtests/simd-vanytrue.clif: host can't run X86_64 programs
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
Illegal instruction
```

### Versions and Environment

Cranelift version or commit: main
Operating system: linux
Architecture: aarch64

### Extra Info

Disassembly:
```
PS C:\Users\Afonso\CLionProjects\wasmtime\cranelift> cargo run -- compile -D --target aarch64 .\filetests\filetests\runtests\simd-vanytrue.clif
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
     Running `C:\Users\Afonso\CLionProjects\wasmtime\target\debug\clif-util.exe compile -D --target aarch64 .\filetests\filetests\runtests\simd-vanytrue.clif`
.byte 0, 228, 0, 79, 0, 164, 224, 110, 0, 60, 8, 78, 31, 0, 0, 241, 224, 7, 159, 154, 192, 3, 95, 214

Disassembly of 24 bytes:
   0:   00 e4 00 4f             movi    v0.16b, #0
   4:   00 a4 e0 6e             .byte   0x00, 0xa4, 0xe0, 0x6e
   8:   00 3c 08 4e             mov     x0, v0.d[0]
   c:   1f 00 00 f1             cmp     x0, #0
  10:   e0 07 9f 9a             cset    x0, ne
  14:   c0 03 5f d6             ret
```

A test suite with `vany_true` tests is introduced as part of #3304

### PR DESCRIPTION
**Pull request by akirilov-arm**
Fixes #3305.

### CODE REVIEW

**Comment by akirilov-arm** [comment]
It seems like there is a test failure when using the legacy x86-64 backend; I will disable the test in that case, similarly to what has been done in other pull requests.

File: cranelift/codegen/src/isa/aarch64/lower_inst.rs [hunk 1]
```diff
@@ -2397,7 +2397,12 @@ pub(crate) fn lower_insn_to_regs<C: LowerCtx<I = Inst>>(
             // cmp xm, #0
             // cset xm, ne
 
-            let size = VectorSize::from_ty(ctx.input_ty(insn, 0));
+            let s = VectorSize::from_ty(src_ty);
+            let size = if s == VectorSize::Size64x2 {
+                VectorSize::Size32x4
```
Comment (cfallin) [inline cranelift/codegen/src/isa/aarch64/lower_inst.rs:2402]: I'm possibly misunderstanding, but doesn't this only work for the "any" case, not the "all" case, since in the latter case half the lanes will be new artificial zeroes (possibly, if the upper bits of the i64 lanes are zeroes)?

Comment (akirilov-arm) [reply cranelift/codegen/src/isa/aarch64/lower_inst.rs:2402]: Yes, you are absolutely right, but there is a separate arm for `VallTrue` with 64-bit elements on line 2343.

Comment (cfallin) [reply cranelift/codegen/src/isa/aarch64/lower_inst.rs:2402]: Ah, I missed that, thank you! Could you add a comment referring to the case above and noting that `VallTrue` with 64x2 doesn't land here?

**Review by cfallin — APPROVED** [review]
Thanks!

**Review by cfallin — APPROVED** [review]
