### PR TITLE
Fix a possible overflow due to use of fionread in poll_oneoff on Unix.

### LINKED ISSUE #578: fionread, used in poll_oneoff on Unix, may overflow for large files
`ioctl_tty(2)` says that `fionread` accepts an `int*`, which may overflow for large files.
Incidentally, the correct size will be returned if we pass a pointer to `int64_t`, but this something we probably shouldn't rely on. 

We probably should use a different syscall (`fstat`?) to query file size for regular files instead of `fionread`. Relevant discussion occurs in #552.
See this example C code which exhibits this behavior.

```
#include <stdio.h>
#include <stdlib.h>
#include <sys/ioctl.h>
#include <stdint.h>

int main(int argc, char** argv) {
	if (argc != 2) {
		fprintf(stderr, "Usage: %s [file path]\n", argv[0]);
		exit(1);
	}
	FILE* file = fopen(argv[1], "r");
	if (file == NULL) {
		perror("opening file");
		exit(1);
	}
	int fd = fileno(file);
	int avail = 0;
	//int64_t avail = 0;
	int ret = ioctl(fd, FIONREAD, &avail);
	if (ret == -1) {
		perror("ioctl");
		exit(1);
	}

	printf("Bytes available: %d\n", avail);
	//printf("Bytes available: %ld\n", avail);
	return 0;
}
```

### PR DESCRIPTION
**Pull request by marmistrz**
Closes #578.

### CODE REVIEW

File: crates/wasi-common/src/sys/unix/hostcalls_impl/misc.rs [hunk 1]
```diff
@@ -126,9 +126,21 @@ fn poll_oneoff_handle_fd_event<'a>(
...
+    use crate::fdentry::Descriptor;
     use std::{convert::TryInto, os::unix::prelude::AsRawFd};
     use yanix::{file::fionread, poll::PollFlags};
 
+    fn query_nbytes(fd: &Descriptor) -> Result<usize> {
+        // fionread may overflow for large files, so use another way for regular files.
+        if let Descriptor::OsHandle(os_handle) = fd {
+            let meta = os_handle.metadata()?;
+            if meta.file_type().is_file() {
+                return meta.len().try_into().map_err(Into::into);
```
Comment (sunfishcode) [inline crates/wasi-common/src/sys/unix/hostcalls_impl/misc.rs]: `query_nbytes`, and `fionread` too while we're here, should return `u64`, so that they work consistently on 32-bit hosts with large files.

This code returns the size of the file, however if the application has already started reading, the current file position should be subtracted from the file size.

Using the file size assumes that all the file data is immediately available, which is unfortunate. However, that is what Unix traditionally does, so it seems reasonable to do it here too, but it would be good to add a comment noting this assumption.

Comment (marmistrz) [reply crates/wasi-common/src/sys/unix/hostcalls_impl/misc.rs]: > `query_nbytes`, and `fionread` too while we're here, should return `u64`, so that they work consistently on 32-bit hosts with large files.

That's true for `query_nbytes` but `fionread` should probably return `u32`, because it's return value is inherently 32-bit. 

> This code returns the size of the file, however if the application has already started reading, the current file position should be subtracted from the file size.

Good catch! Thanks.

I address your feedback.
