### PR TITLE
Components: ignore type exports (for now).

### LINKED ISSUE #4415: Output of `wit-component` doesn't work in Wasmtime due to named type exports
Loading in a `Component` hits [this `unimplemented!()` statement](https://github.com/bytecodealliance/wasmtime/blob/7000b0a4cff1798b8e2fc5316b1be29b9fee2415/crates/environ/src/component/translate.rs#L737) when the component was generated with `wit-bindgen` and `wit-component`. [According to @alexcrichton](https://github.com/bytecodealliance/wasmtime/issues/4308#issuecomment-1177753030) this is a bug.  

### Test Case

I've created [a repo](https://github.com/tsoutsman/wit-type-import-bug). To recreate the example run `./run.sh`.

### Expected Results

The component loads.

### Actual Results

Panic.
```
thread 'main' panicked at 'not implemented: component type export', /home/klim/.cargo/git/checkouts/wasmtime-41807828cb3a7a7e/a8ce7f1/crates/environ/src/component/translate.rs:743:17
```

### Versions and Environment

Wasmtime version or commit: Latest git commit

Operating system: Fedora Linux

Architecture: x86-64

### Notes

Maybe it'd be better to open this issue in the `wit-bindgen` repo.

### PR DESCRIPTION
**Pull request by peterhuene**
This PR updates component translation to ignore type exports for now.

Components generated with `wit-component` contain type exports to give names to
types used within the component's functions based on the component's wit
definition.

The intention is to allow bindings to be generated with meaningful names
directly from a component. In the future, type exports (and imports) may be
used for more than this purpose to support things like resource types.

This PR effectively ignores type exports when translating the component as
they are not useful to executing a component at this time.

Closes #4415.

### CODE REVIEW

File: tests/all/component_model/instance.rs [hunk 1]
```diff
@@ -55,3 +55,20 @@ fn instance_exports() -> Result<()> {
...
+
+#[test]
+fn instantiate_with_type_exports() -> Result<()> {
+    // For now, this just tests that we can instantiate a component with type exports
+    let engine = super::engine();
+    let component = r#"
+        (component
+            (type string)
+            (export "" (type 0))
+        )
```
Comment (alexcrichton) [inline tests/all/component_model/instance.rs:67]: I think this can also be added to something in `tests/misc_testsuite/component-model` if you'd prefer

**Review by alexcrichton — APPROVED** [review]
Looks good to me, thanks! Could you file an issue with the `component-model` tag to come back to this? (and update the `TODO` to point to the issue)

File: tests/all/component_model/instance.rs (hunk 1 above)
Comment (peterhuene) [reply tests/all/component_model/instance.rs:67]: I'll move it there, thanks!

Comment (peterhuene) [reply tests/all/component_model/instance.rs:67]: Are we running `misc_testsuite` with `component-model` feature flag in CI? A quick perusal of `main.yml` seems like we're only running the `component_model` test with `cargo test --test all --features component-model component_model`.

Comment (peterhuene) [reply tests/all/component_model/instance.rs]: Never mind, that does indeed run both sets as expected.
