### PR TITLE
Restore running precompiled modules with the CLI

### LINKED ISSUE #3338: Fail to run AOT cwasm module which is compiled by  the `wasmtime compile` command
## Description

I want to run a simple AOT style cwasm module which is compiled by the `wasmtime compile` command. So I use the examples in the documentation: [Creating hello-world.wasm](https://docs.wasmtime.dev/tutorial-create-hello-world.html)

I compile the `hello-world` rust project to wasm32-wasi target and run it with wasmtime successfully:
```bash
root@node1: /home/xxx/wasm-by-example/hello-world# cargo build --target wasm32-wasi
   Compiling hello-world v0.1.0 (/home/xxx/wasm-by-example/hello-world)
    Finished dev [unoptimized + debuginfo] target(s) in 0.56s

root@node1:/home/xxx/wasm-by-example/hello-world# wasmtime run target/wasm32-wasi/debug/hello-world.wasm
Hello, world!
```

However, I failed to run the `hello-world` AOT format wasm module compiled by  `wasmtime compile` command, the output is:
```bash
root@node1:/home/xxx/wasm-by-example/hello-world# wasmtime compile target/wasm32-wasi/debug/hello-world.wasm

root@node1:/home/xxx/wasm-by-example/hello-world# ls 
Cargo.lock  Cargo.toml  hello-world.cwasm  src  target

root@node1:/home/xxx/wasm-by-example/hello-world# wasmtime run hello-world.cwasm
Error: failed to run main module `hello-world.cwasm`

Caused by:
    failed to parse `hello-world.cwasm`: input bytes aren't valid utf-8
```

## Environment Info

wasmtime version:
```bash
root@node1:/home/xxx/wasm-by-example/hello-world# wasmtime --version
wasmtime 0.29.0
```

OS Info:
```bash
root@node1:/home/xxx/wasm-by-example/hello-world# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

root@node1:/home/xxx/wasm-by-example/hello-world# uname -r
4.15.0-154-generic
```

### PR DESCRIPTION
**Pull request by alexcrichton**
This was accidentally broken when `Module::deserialize` was split out of
`Module::new` long ago, so this adds the detection in the CLI to call
the appropriate method to load the module.

Closes #3338

### CODE REVIEW

File: src/commands/run.rs [hunk 1]
```diff
@@ -360,6 +360,25 @@ impl RunCommand {
...
+            .with_context(|| format!("failed to read path: {}", path.display()))?;
+
+        // Part of the CLI is that we can load precompiled wasm modules output
+        // by `wasmtime compile`. This is the raw output of `module.serialize()`
+        // which for now is an ELF image, so we detect whether this is an ELF
+        // file and if so try to deserialize a module from that.
+        //
+        // This technically makes this whole implementation unsafe because it's
+        // not safe to feed arbitrary bytes into `deserialize`, but that's part
+        // of the CLI interface, so it's just how this is designed.
```
Comment (pchickey) [inline src/commands/run.rs:375]: The versioning check does give us a small amount of additional safety, since that has to pass before we bincode::deserialize. Maybe worth mentioning?

**Review by pchickey — APPROVED** [review]

File: src/commands/run.rs [hunk 2]
```diff
@@ -360,6 +360,25 @@ impl RunCommand {
 
         Ok(())
     }
+
+    fn load_module(&self, engine: &Engine, path: &Path) -> Result<Module> {
+        let contents = std::fs::read(path)
```
Comment (peterhuene) [inline src/commands/run.rs:365]: Thoughts on peeking at the file and using `Module::deserialize_file` if ELF?

**Review by peterhuene — APPROVED** [review]
I'm 👍, although I think there could be a case made where `wasmtime run` shouldn't run serialized modules given the unsafety of it.

I wonder if perhaps we add an option to `wasmtime run` that enables checking for ELF and deserializing?  For example, `wasmtime run --allow-compiled foo.cwasm` (🚲 shed on option name tbd).

File: src/commands/run.rs (hunk 1 above)
Comment (alexcrichton) [reply src/commands/run.rs:375]: Yeah the main thing we're worried about with `Module::deserialize` is that it's not safe to pass user-defined input into it because it's easy to construct an ELF file which executes arbitrary things but passes our deserialization. I do think, though, that we have enough checks in place to catch accidental usage without segfaulting.

**Comment by alexcrichton** [comment]
Yeah I think I like the idea of a flag to opt-in to this. I'll implement that!

**Review by peterhuene — APPROVED** [review]
