### PR TITLE
Fix optimization rules for narrow types: wrap i8 results to 8 bits.

### LINKED ISSUE #5405: Cranelift: Fuzz failure with egraphs on AArch64
👋 Hey,

The fuzzer found this error overnight on AArch64. It passes on x86.

### `.clif` Test Case

```
test interpret
test run
set opt_level=speed_and_size
set use_egraphs=true
target aarch64

function %a(i64) -> i8 system_v {
block0(v0: i64):
    v6 = iconst.i8 51
    v17 = imul v6, v6  ; v6 = 51, v6 = 51
    v18 = icmp eq v17, v17
    v52 = imul v18, v18
    return v52
}

; run: %a(129) == 1
```

### Steps to Reproduce

* `clif-util ./the-above.clif`

### Expected Results

The test to pass

### Actual Results

```
afonso@DESKTOP-VSTS4BC:~/git/wasmtime/cranelift$ cargo run --target aarch64-unknown-linux-gnu -- test ./lmao.clif 
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `qemu-aarch64 -L /usr/aarch64-linux-gnu -E LD_LIBRARY_PATH=/usr/aarch64-linux-gnu/lib /home/afonso/git/wasmtime/target/aarch64-unknown-linux-gnu/debug/clif-util test ./lmao.clif`
 ERROR cranelift_filetests::concurrent > FAIL: run
FAIL ./lmao.clif: run

Caused by:
    Failed test: run: %a(129) == 1, actual: 0
1 tests
Error: 1 failure
```

### Versions and Environment

Cranelift version or commit: main
Operating system: linux
Architecture: aarch64

cc: @cfallin

### PR DESCRIPTION
**Pull request by cfallin**
This fixes #5405.

In the egraph mid-end's optimization rules, we were rewriting e.g. imuls of two iconsts to an iconst of the result, but without masking off the high bits (beyond the result type's width). This was producing iconsts with set high bits beyond their types' width, which is not legal.

In addition, this PR adds some optimizations to the algebraic rules to recognize e.g. `x == x` (and all other integer comparison operators) and resolve to 1 or 0 as appropriate.

### CODE REVIEW

**Review by jameysharp — COMMENTED** [review]
Other than the one comment, this looks right to me!

**Comment by cfallin** [comment]
> > This was producing iconsts with set high bits beyond their types' width, which is not legal.
> 
> I thought backends were supposed to mask it. I believe cg_clif sometimes sign extends immediates.

Hmm, it seems we discussed this and filed #3059 a while ago, and haven't done any thinking about it since. I suspect that we aren't doing such masking everywhere we need to be, and requiring rules everywhere to do the masking (e.g., const-folding an `icmp eq` would require comparing only the relevant bits) seems cumbersome. I'd rather we have an invariant that values stay in range.

For now I guess we can keep the status quo, but we should think about this some more (on that issue probably)!

File: cranelift/codegen/src/isle_prelude.rs [hunk 1]
```diff
@@ -509,6 +509,12 @@ macro_rules! isle_common_prelude_methods {
             Imm64::new(x as i64)
         }
 
+        #[inline]
+        fn imm64_masked(&mut self, ty: Type, x: u64) -> Imm64 {
+            debug_assert!(ty.bits() <= 64);
+            Imm64::new((x & ((1u64 << ty.bits()) - 1)) as i64)
```
[the remark this answers is not in the document]
Comment (cfallin) [reply cranelift/codegen/src/isle_prelude.rs:515]: Ah, yes, sorry for missing that! I prefer the version without conditionals (the first expression you gave) so I've gone with that.

File: cranelift/codegen/src/isle_prelude.rs [hunk 2]
```diff
@@ -512,7 +512,15 @@ macro_rules! isle_common_prelude_methods {
         #[inline]
         fn imm64_masked(&mut self, ty: Type, x: u64) -> Imm64 {
             debug_assert!(ty.bits() <= 64);
-            Imm64::new((x & ((1u64 << ty.bits()) - 1)) as i64)
+            if ty.bits() == 64 {
+                Imm64::new(x as i64)
+            } else {
```
Comment (jameysharp) [inline cranelift/codegen/src/isle_prelude.rs:517]: I don't understand pulling `ty.bits() == 64` out as a special case if you're using the right-shift version below. `u64::MAX >> 0` should be a correct mask for this case.

Comment (cfallin) [reply cranelift/codegen/src/isle_prelude.rs]: Argh, yeah, I wrote it the conditionalized way first and then decided I liked the right-shift variant better, but only updated locally and didn't actually delete the conditional. I think I've found the rest of my brain now; sorry about that...

**Review by jameysharp — APPROVED** [review]
LGTM!

**Comment by jameysharp** [comment]
BTW I'm curious if the new optimization rules have any impact on any benchmarks. Do these patterns show up in any CLIF we're generating from wasm, or do our current benchmarks compile to the same sequence of instructions either way? Not terribly important but if this is a significant win for some reason, that'd be nice to know.

**Comment by cfallin** [comment]
That's a good question, re: the `icmp` folding; I didn't do tests on this. Honestly I'd be somewhat surprised if they did though, given that the benchmarks are optimized `.wasm`s and the sorts of redundancies that show up in the translated CLIF are not usually things that const-folding applies to.

**Comment by cfallin** [comment]
And, to follow up, a quick smoketest with `bz2` shows no runtime impact with the additional `icmp` folding roles.
