### PR TITLE
fix `Pollable` impl for `OutgoingDatagramStream`

### LINKED ISSUE #12612: [wasi-sockets] Fresh UDP sockets occasionally return `ErrorCode::WouldBlock` on first send
I'm (still) working to add WASIp2 support to `mio` and have noticed that several of the UDP tests _usually_ pass but sometimes fail.  When they fail, it's always due to the host returning `error-code::would-block` from `outgoing-datagram-stream.send` (which `wasi-libc` translates to returning `EWOULDBLOCK` from `send(2)`).  This can happen even if the socket was just created, has not previously been used to send anything, and for which `outgoing-datagram-stream.check-send` has returned a non-zero number.  It can also happen when `poll.poll` has just returned a write-ready event for the `pollable` representing the `outgoing-datagram-stream`.

I've simplified the test case somewhat here:

```rust
// udp.rs
use std::{error::Error, io::ErrorKind, net::UdpSocket};

fn main() -> Result<(), Box<dyn Error>> {
    for _ in 0..50 {
        let socket1 = UdpSocket::bind("127.0.0.1:0")?;
        socket1.set_nonblocking(true)?;
        let socket2 = UdpSocket::bind("127.0.0.1:0")?;
        socket2.set_nonblocking(true)?;

        let address1 = socket1.local_addr()?;
        let address2 = socket2.local_addr()?;

        socket1.connect(address2)?;
        socket2.connect(address1)?;

        let data = b"foobar";
        socket1.send(data)?;

        let mut buffer = [0u8; 20];
        match socket2.recv(&mut buffer) {
            Ok(n) => {
                assert_eq!(data, &buffer[..n]);
            }
            Err(error) => {
                assert!(matches!(error.kind(), ErrorKind::WouldBlock));
            }
        }
    }

    println!("success!");

    Ok(())
}
```

If you run e.g. `rustc --target=wasm32-wasip2 udp.rs && while wasmtime run -Sudp,inherit-network udp.wasm; do :; done`, sooner or later you'll see `Error: Os { code: 6, kind: WouldBlock, message: "Resource temporarily unavailable" }`.  However, if you run e.g. `rustc udp.rs && while ./udp; do :; done` on Linux, it will succeed indefinitely.

When I dug into this, I found that `wasmtime-wasi` uses `tokio::net::UdpSocket::try_send[_to]` to send datagrams, which eventually consults [this function](https://github.com/tokio-rs/tokio/blob/d83921bc5181010be72704d1fe8fb9b6f10cb7e8/tokio/src/runtime/io/scheduled_io.rs#L290-L298) from [here](https://github.com/tokio-rs/tokio/blob/master/tokio/src/runtime/io/registration.rs#L188) to determine whether to even bother trying to send.  Indeed, when I add debug logging to that function and patch Wasmtime to use it, I see that the "not ready" case corresponds to when the host returns `would-block` to the guest, which indicates that `tokio` is applying backpressure rather than the OS.

I imagine that in most real-world code, returning spurious `would-block` errors occasionally wouldn't be a problem; the application can just poll and try again.  However, it makes the `mio` tests flaky, so I'd like to brainstorm solutions here.

One rather heavy-handed approach could be to bypass Tokio for sending and receiving datagrams, using `tokio::net::UdpSocket::{into,from}_std` to temporarily convert between the Tokio version and the `std` version.  I imagine that could have other implications, though.

### PR DESCRIPTION
**Pull request by dicej**
Previously, `OutgoingDatagramStream` used its `send_state` field to determine whether the socket was ready for writing without necessarily polling the `tokio::net::UdpSocket`.  The underlying assumption was that a freshly-bound socket would be immediately ready for writing, but that's not true for `tokio`. `tokio` assumes a socket is not ready for _anything_ by default and relies on e.g. `epoll` to tell it otherwise.

In practice, this meant the `Pollable::ready` impl for `OutgoingDatagramStream` would resolve immediately for a fresh socket, leaving the guest to race with `tokio`'s use of `epoll`.  Usually, `tokio` won and all was well, but occasionally it lost and the `OutgoingDatagramStream::send` call would return `Ok(0)` (meaning "would block") leaving the guest confused since it was just told that the socket was ready for writing.

This commit removes `SendState` entirely, relying exclusively on `tokio::net::UdpSocket::ready` for the `Pollable` and `check_send` implementations.  As a side effect, we no longer attempt to prevent the guest from sending more datagrams than `check_send` indicated since the number returned by `check_send` is only a guess anyway, and `tokio` will push back if it needs to.  For `p3`, the whole `check_send`/`send` pattern is gone, so we won't need to concern ourselves with it going forward.

Fixes #12612

### CODE REVIEW

**Comment by dicej** [comment]
cc @badeend in case you're interested

File: crates/wasi/src/p2/host/udp.rs [hunk 1]
```diff
@@ -354,8 +341,7 @@ impl udp::HostOutgoingDatagramStream for WasiSocketsCtxView<'_> {
                     return Ok(count);
                 }
                 Err(e) if matches!(e.downcast_ref(), Some(ErrorCode::WouldBlock)) => {
-                    stream.send_state = SendState::Waiting;
-                    return Ok(count);
+                    return Ok(0);
```
Comment (alexcrichton) [inline crates/wasi/src/p2/host/udp.rs:345]: Could this additionally `debug_assert!` that `count == 0`?

**Comment by alexcrichton** [comment]
Also, if you're up for it, I think it'd be good to test this on p3 too (semantically at least)

**Comment by badeend** [comment]
>  As a side effect, we no longer attempt to prevent the guest from sending more datagrams than check_send indicated since the number returned by check_send is only a guess anyway

@dicej This violates the [P2 spec](https://github.com/WebAssembly/WASI/blob/41d0de898ec7568e032129156a3bc567d7ebea5d/proposals/sockets/wit/udp.wit#L256C1-L257C111):

> Each call to `send` must be permitted by a preceding `check-send`. Implementations must trap if either `check-send` was not called or `datagrams` contains more items than `check-send` permitted.

Can the check be reintroduced?

**Comment by dicej** [comment]
> @dicej This violates the [P2 spec](https://github.com/WebAssembly/WASI/blob/41d0de898ec7568e032129156a3bc567d7ebea5d/proposals/sockets/wit/udp.wit#L256C1-L257C111):
> 
> > Each call to `send` must be permitted by a preceding `check-send`. Implementations must trap if either `check-send` was not called or `datagrams` contains more items than `check-send` permitted.
> 
> Can the check be reintroduced?

🤦 Yes, I'll do that on Monday.  Thanks for catching that.
