### PR TITLE
doc: fix StackSlot reference to FunctionBuilder

### LINKED ISSUE #5838: documentation refers to nonexistent function
From:

https://docs.rs/cranelift-codegen/latest/cranelift_codegen/ir/entities/struct.StackSlot.html

"StackSlots can be created with [FunctionBuilder::create_stackslot](https://docs.rs/cranelift-frontend/*/cranelift_frontend/struct.FunctionBuilder.html#method.create_stack_slot)."

There isn't such a function AFAICT. Perhaps it should be `create_sized_stack_slot`? I'm new to cranelift.

### PR DESCRIPTION
**Pull request by chrisdickinson**
`FunctionBuilder::create_stackslot` was renamed `create_sized_stack_slot`, this updates the link in the `StackBuilder` docstring.

Fixes #5838.

### CODE REVIEW

File: cranelift/codegen/src/ir/entities.rs [hunk 1]
```diff
@@ -106,7 +106,7 @@ entity_impl!(Inst, "inst");
 /// [call stack](https://en.wikipedia.org/wiki/Call_stack).
 ///
 /// `StackSlot`s can be created with
-/// [`FunctionBuilder::create_stackslot`](https://docs.rs/cranelift-frontend/*/cranelift_frontend/struct.FunctionBuilder.html#method.create_stack_slot).
+/// [`FunctionBuilder::create_sized_stack_slot`](https://docs.rs/cranelift-frontend/*/cranelift_frontend/struct.FunctionBuilder.html#method.create_sized_stack_slot).
```
Comment (cfallin) [inline cranelift/codegen/src/ir/entities.rs:109]: Can we mention `create_dynamic_stack_slot` here too? (Both this and the sized variant are peers -- both are valid ways to create stackslots, for different sorts of types.)

Comment (chrisdickinson) [reply cranelift/codegen/src/ir/entities.rs]: Sure! Thanks for the heads up. I've re-pushed the commit with the requested changes.

**Review by cfallin — APPROVED** [review]
Thanks!
