### PR TITLE
Resolve libcall relocations for older CPUs

### LINKED ISSUE #5563: Cranelift: cannot generate relocation against libcall FloorF64, when has_sse41=false
### `.wat` Test Case

```
(module
  (type (;0;) (func (param f64) (result f64)))
  (func $f (type 0) (param f64) (result f64)
    local.get 0
    f64.floor))
```

### Steps to Reproduce

* `wasmtime run --wasm-features=-simd --cranelift-set has_sse41=false testcase.wat`

### Expected Results

I would expect wasmtime / cranelift to be able to compile this code on a machine with has_sse41=false.  (In particular, this shows up in a QEMU VM.)

### Actual Results

I get an error:

```
thread 'main' panicked at 'not implemented: cannot generate relocation against libcall FloorF64', crates/cranelift/src/obj.rs:155:21
```

### Versions and Environment

Cranelift version or commit: 4.0.0

Operating system: Linux 6.1.3

Architecture: x86_64; the problem shows up in a QEMU VM where has_sse41=false, but can also be observed outside of a QEMU VM by explicitly passing `has_sse41=false` like above.

### PR DESCRIPTION
**Pull request by alexcrichton**
Long ago Wasmtime used to have logic for resolving relocations post-compilation for libcalls which I ended up removing during refactorings last year. As #5563 points out, however, it's possible to get Wasmtime to panic by disabling SSE features which forces Cranelift to use libcalls for some floating-point operations instead. Note that this also requires disabling SIMD because SIMD support has a baseline of SSE 4.2.

This commit pulls back the old implementations of various libcalls and reimplements logic necessary to have them work on CPUs without SSE 4.2

Closes #5563

### CODE REVIEW

**Comment by alexcrichton** [comment]
I primarily tested this through:

```
ALLOWED_ENGINES=wasmi ALLOWED_MODULES=single-inst cargo +nightly fuzz run -s none differential --no-default-features
```

to find all instructions that need libcall lowerings. Cranelift still has more libcalls but it seems that we don't end up relying on them, so I've left various panics in place to notify us if libcalls pop up and they're not handled. Otherwise the fuzzing has run for awhile now and hasn't found more instructions so this is likely at least a good set to start with.

File: crates/runtime/src/libcalls.rs [hunk 1]
```diff
@@ -492,3 +492,83 @@ unsafe fn out_of_gas(vmctx: *mut VMContext) -> Result<()> {
...
+    }
+
+    pub extern "C" fn truncf64(f: f64) -> f64 {
+        f.trunc()
+    }
+
+    const TOINT_32: f32 = 1.0 / f32::EPSILON;
+    const TOINT_64: f64 = 1.0 / f64::EPSILON;
+
+    pub extern "C" fn nearestf32(x: f32) -> f32 {
```
Comment (jameysharp) [inline crates/runtime/src/libcalls.rs:533]: It'd be nice if there was a good way to share these implementations of `round_ties_even` with the ones in `cranelift/codegen/src/ir/immediates.rs`. None come to my mind off-hand since the runtime can be built in a configuration without the compiler, but it'd be nice.

The existing version there doesn't have the "Check for NaNs" section that this version does. I haven't thought hard enough about this to understand what that's for, but maybe you could add a comment linking to some reference for why this is the right implementation?

The existing version does have a link to rust-lang/rust#96710 which I think is worth copying here.

**Review by jameysharp — APPROVED** [review]
I like that this looks like it has no runtime cost except when it's actually needed. I have a couple questions but overall this looks like the right plan to me!

File: crates/fuzzing/src/generators/codegen_settings.rs [hunk 2]
```diff
@@ -32,6 +33,46 @@ impl CodegenSettings {
...
+
+            for (name, val) in flags {
+                match name.as_str() {
+                    "has_sse3" => *val = sse3.to_string(),
+                    "has_ssse3" => *val = ssse3.to_string(),
+                    "has_sse41" => *val = sse4_1.to_string(),
+                    "has_sse42" => *val = sse4_2.to_string(),
+                    _ => {}
+                }
+            }
```
[the remark this answers is not in the document]
Comment (alexcrichton) [reply crates/fuzzing/src/generators/codegen_settings.rs:72]: > Is it okay to turn some off without turning off later ones?

While I'm not 100% certain myself I believe that this question is up to Cranelift mostly. I believe Cranelift is mostly structured around "if this feature is active emit this instr" while it doesn't make sense to disable sse3 but leave sse4.1 enabled I don't think it will break anything since it would be a sort of "chaos mode" for cranelift stressing it.

If this becomes a problem for Cranelift, however, we can tweak the fuzz input to respect what the actual CPU feature hierarchy is.

File: crates/runtime/src/libcalls.rs (hunk 1 above)
Comment (alexcrichton) [reply crates/runtime/src/libcalls.rs:535]: These libcalls were removed in https://github.com/bytecodealliance/wasmtime/pull/4470 and I copied their source from just before that commit. 

Apparently `nearest` has a slightly storied history:

* https://github.com/bytecodealliance/wasmtime/pull/2219 fixed it for NaN cases 
* https://github.com/bytecodealliance/wasmtime/pull/2171 made the implementation more efficient based on musl
* https://github.com/bytecodealliance/wasmtime/pull/34 was the original implementation

I ran `cargo run wast ./tests/spec_testsuite/f32.wast --cranelift-set has_sse41=false --wasm-features=-simd` and commented out the "Check for NaNs" block and the tests failed, so the block is definitely load-bearing. That may mean that Cranelift's implementation needs to be updated to account for NaN's perhaps? (I don't really understand the actual underlying code here I'm just copying bytes)
