### PR TITLE
Fix a case of using the wrong stack map during gcs

### LINKED ISSUE #2386: Runtime panics with 'every on-stack externref inside a Wasm frame should have an entry in the VMExternRefActivationsTable'
I recently run into a flaky issue running a WASM app using Externrefs under Wasmtime.
Sadly, I can't share any code related to it. Either way it's a lot of code and I'm looking more at pointers how I could debug this further by myself.

**Sometimes** (8 out of 10 runs) the app would panic with the following error:

```
thread '<unnamed>' panicked at 'every on-stack externref inside a Wasm frame should have an entry in the VMExternRefActivationsTable', wasmtime/crates/runtime/src/externref.rs:1070:21
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/bkolobara/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:505:12
   1: wasmtime_runtime::externref::gc::{{closure}}
             at ./wasmtime/crates/runtime/src/externref.rs:1070:21
   2: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /Users/bkolobara/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:269:13
   3: backtrace::backtrace::libunwind::trace::trace_fn
             at /Users/bkolobara/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.50/src/backtrace/libunwind.rs:107:26
   4: __Unwind_Backtrace
   5: backtrace::backtrace::libunwind::trace
             at /Users/bkolobara/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.50/src/backtrace/libunwind.rs:95:5
   6: backtrace::backtrace::trace_unsynchronized
             at /Users/bkolobara/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.50/src/backtrace/mod.rs:66:5
   7: backtrace::backtrace::trace
             at /Users/bkolobara/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.50/src/backtrace/mod.rs:53:14
   8: wasmtime_runtime::externref::gc
             at ./wasmtime/crates/runtime/src/externref.rs:1054:5
   9: wasmtime_runtime::externref::VMExternRefActivationsTable::gc_and_insert_slow
             at ./wasmtime/crates/runtime/src/externref.rs:585:9
  10: wasmtime_runtime::externref::VMExternRefActivationsTable::insert_with_gc
             at ./wasmtime/crates/runtime/src/externref.rs:575:13
  11: <core::option::Option<wasmtime::ref::ExternRef> as wasmtime::func::WasmTy>::into_abi_for_arg
             at ./wasmtime/crates/wasmtime/src/func.rs:1238:17
  12: <T as wasmtime::func::WasmRet>::into_abi_for_ret
             at ./wasmtime/crates/wasmtime/src/func.rs:1350:9
  13: <F as wasmtime::func::IntoFunc<(wasmtime::func::Caller,A1,A2,A3),R>>::into_func::wasm_to_host_shim
             at ./wasmtime/crates/wasmtime/src/func.rs:1624:29
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <F as wasmtime::func::IntoFunc<(wasmtime::func::Caller,),R>>::into_func::host_trampoline
             at ./wasmtime/crates/wasmtime/src/func.rs:1657:31
  23: wasmtime::func::Func::call::{{closure}}
             at ./wasmtime/crates/wasmtime/src/func.rs:620:17
  24: wasmtime_runtime::traphandlers::catch_traps::call_closure
             at ./wasmtime/crates/runtime/src/traphandlers.rs:397:18
  25: RegisterSetjmp
             at ./wasmtime/crates/runtime/src/helpers.c:12:3
  26: wasmtime_runtime::traphandlers::catch_traps::{{closure}}
             at ./wasmtime/crates/runtime/src/traphandlers.rs:386:9
  27: wasmtime_runtime::traphandlers::CallThreadState::with::{{closure}}
             at ./wasmtime/crates/runtime/src/traphandlers.rs:442:38
  28: wasmtime_runtime::traphandlers::tls::set::{{closure}}
             at ./wasmtime/crates/runtime/src/traphandlers.rs:682:13
  29: std::thread::local::LocalKey<T>::try_with
             at /Users/bkolobara/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  30: std::thread::local::LocalKey<T>::with
             at /Users/bkolobara/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  31: wasmtime_runtime::traphandlers::tls::set
             at ./wasmtime/crates/runtime/src/traphandlers.rs:674:9
  32: wasmtime_runtime::traphandlers::CallThreadState::with
             at ./wasmtime/crates/runtime/src/traphandlers.rs:442:19
  33: wasmtime_runtime::traphandlers::catch_traps
             at ./wasmtime/crates/runtime/src/traphandlers.rs:385:12
  34: wasmtime::func::invoke_wasm_and_catch_traps
             at ./wasmtime/crates/wasmtime/src/func.rs:829:9
  35: wasmtime::func::Func::call
             at ./wasmtime/crates/wasmtime/src/func.rs:619:13
  36: lunatic_vm::process::Process::spawn::{{closure}}
             at ./src/process/mod.rs:160:25
....
```

The code path taken by the app should always be the same and first of all I can't figure out why it only fails sometimes. Any pointers would be appreciated.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit fixes an issue where when looking up the stack map for a pc
within a function we might end up reading the *previous* function's
stack maps. This then later caused asserts to trip because we started
interpreting random data as a `VMExternRef` when it wasn't. The fix was
to add `None` markers for "this range has no stack map" in the function
ranges map.

Closes #2386

### CODE REVIEW

File: crates/runtime/src/externref.rs [hunk 1]
```diff
@@ -804,11 +805,20 @@ impl StackMapRegistry {
...
+            if pc_to_stack_map.len() > 0 {
+                pc_to_stack_map.push((range.start, None));
+            }
+
             for info in infos {
                 assert!((info.code_offset as usize) < len);
                 pc_to_stack_map.push((
                     range.start + (info.code_offset as usize),
-                    Rc::new(info.stack_map.clone()),
+                    Some(Rc::new(info.stack_map.clone())),
```
Comment (fitzgen) [inline crates/runtime/src/externref.rs:821]: If `info.code_offset` is `0` then we could have duplicate entries (one `None` for the start of the function and one `Some` for this info).

I don't *think* this should ever happen though, so perhaps we can just assert that `info.code_offset > 0`?

The alternative is checking ahead of time whether the first `info.code_offset` is `0` (because they should be sorted iirc) and only adding the `None` entry if the first `info.code_offset` is not `0`.

**Review by fitzgen — APPROVED** [review]
Nice digging!

r=me modulo dealing with the inline comment below

File: crates/runtime/src/externref.rs (hunk 1 above)
Comment (alexcrichton) [reply crates/runtime/src/externref.rs]: Oh nice catch, I refactored a bit which I think will handle this correctly, mind double-checking?

I also went ahead and did a small tweak where consecutive `None` entries are now coalesced.

File: crates/runtime/src/externref.rs [hunk 2]
```diff
@@ -797,19 +798,36 @@ impl StackMapRegistry {
...
+            // starts with no stack map so when our binary search later on finds
+            // a pc between the start of the function and the function's first
+            // stack map it doesn't think the previous stack map is our stack
+            // map.
+            //
+            // We skip this if the previous entry pushed was also a `None`
+            // marker, in which case the starting pc already has no stack map.
+            // This is also skipped if the first `code_offset` is zero since
+            // what we'll push applies for the first pc anyway.
+            if !last_is_none_marker && (infos.is_empty() || infos[0].code_offset > 0) {
```
Comment (fitzgen) [inline crates/runtime/src/externref.rs:819]: Could make this a tiny bit less wordy (although perhaps some would argue less readable) like this:

```suggestion
            if !last_is_none_marker && (infos.get(0).map_or(true, |i| i.code_offset > 0) {
```

I would probably use `map_or` personally but it doesn't really matter either way.

**Review by fitzgen — APPROVED** [review]
LGTM!

File: crates/runtime/src/externref.rs (hunk 2 above)
Comment (fitzgen) [reply crates/runtime/src/externref.rs:819]: Oh I guess this isn't actually even less wordy... nevermind!
