### PR TITLE
[wasi-common]: add armv7 support to wasi-common

### LINKED ISSUE #1219: yanix v0.12.0 (/tmp/wasmtime/crates/wasi-common/yanix) fails to compile on armv7-unknown-linux-gnueabihf
git clone the repo, cd wasmtime/crates/wasi-common/yanix and execute cargo build fails with this beauty: 

```
crates/wasi-common/yanix $ cargo build
    Updating crates.io index
  Downloaded cfg-if v0.1.10
  Downloaded thiserror v1.0.11
  Downloaded libc v0.2.67
  Downloaded log v0.4.8
  Downloaded bitflags v1.2.1
  Downloaded thiserror-impl v1.0.11
  Downloaded proc-macro2 v1.0.8
  Downloaded quote v1.0.2
  Downloaded unicode-xid v0.2.0
  Downloaded syn v1.0.15
   Compiling proc-macro2 v1.0.8
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.15
   Compiling bitflags v1.2.1
   Compiling libc v0.2.67
   Compiling log v0.4.8
   Compiling cfg-if v0.1.10
   Compiling quote v1.0.2
   Compiling thiserror-impl v1.0.11
   Compiling thiserror v1.0.11
   Compiling yanix v0.12.0 (/home/tim/wasmtime/crates/wasi-common/yanix)
error[E0308]: try expression alternatives have incompatible types
   --> crates/wasi-common/yanix/src/file.rs:247:23
    |
247 |     let offset: i64 = Errno::from_result(libc::lseek(fd, 0, libc::SEEK_CUR))?;
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                       |
    |                       expected `i64`, found `i32`
    |                       help: you can convert an `i32` to `i64`: `Errno::from_result(libc::lseek(fd, 0, libc::SEEK_CUR))?.into()`

error[E0277]: the trait bound `i32: std::convert::From<i64>` is not satisfied
  --> crates/wasi-common/yanix/src/sys/linux/mod.rs:10:17
   |
10 |         Ok(Self(loc))
   |                 ^^^ the trait `std::convert::From<i64>` is not implemented for `i32`
   |
   = help: the following implementations were found:
             <i32 as std::convert::From<bool>>
             <i32 as std::convert::From<i16>>
             <i32 as std::convert::From<i8>>
             <i32 as std::convert::From<std::num::NonZeroI32>>
           and 2 others
   = note: required because of the requirements on the impl of `std::convert::Into<i32>` for `i64`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `yanix`.

```

aarch64 seems fine. 

rustc is v1.41.1 with llvm-9

### PR DESCRIPTION
**Pull request by kubkon**
This commit enables `target_pointer_width = 32` compatibility for `wasi-common` (and by transitivity, any crate found inside, e.g., `yanix`). I've also added a simplistic (bare minimum) check to our CI to ensure that `wasi-common` cross-compiles to `armv7-unknown-gnueabihf` fine. While here, I've done the same for `wasm32-unknown-emscripten`.

To avoid code duplication, I've added a custom ext trait `FileTimeExt` which implements seconds and nanoseconds accessors for with different impls for different pointer widths. I'm not sure whether that's the cleanest approach but definitely seemed like it at the time. Lemme know what you reckon!

Fixes #1219 

cc @stefson hopefully this fixes it for you :-)

### CODE REVIEW

File: crates/wasi-common/yanix/src/sys/linux/filetime.rs [hunk 1]
```diff
@@ -6,8 +6,15 @@ use std::fs::File;
...
-pub(crate) const UTIME_OMIT: i64 = 1_073_741_822;
+cfg_if::cfg_if! {
+    if #[cfg(target_pointer_width = "64")] {
+        pub(crate) const UTIME_NOW: i64 = 1_073_741_823;
+        pub(crate) const UTIME_OMIT: i64 = 1_073_741_822;
+    } else {
+        pub(crate) const UTIME_NOW: i32 = 1_073_741_823;
+        pub(crate) const UTIME_OMIT: i32 = 1_073_741_822;
+    }
+}
```
Comment (sunfishcode) [inline crates/wasi-common/yanix/src/sys/linux/filetime.rs]: We should use `libc::c_long` here. Or even better, can we use `libc::UTIME_NOW` and `libc::UTIME_OMIT` instead of defining our own copies?

Comment (kubkon) [reply crates/wasi-common/yanix/src/sys/linux/filetime.rs]: That's a good point actually. As far as I can remember, the main reason why we'd define them ourselves was to support older `libc` crates where those constants were incorrectly defined for some targets (netbsd and macos are the awkward ones among others). Given that they are now fixed in `libc`, I'm happy to reuse their definitions instead :+1:

File: crates/wasi-common/yanix/src/filetime.rs [hunk 2]
```diff
@@ -10,40 +10,55 @@ use std::io::Result;
...
+            Ok(sec) => sec,
+            Err(_) => {
+                log::debug!("filetime_to_timespec failed converting seconds to required width");
+                return Err(Error::from_raw_os_error(libc::EOVERFLOW));
+            }
+        };
+        Ok(sec)
+    }
+    #[cfg(target_pointer_width = "32")]
+    fn nanoseconds_checked(&self) -> Result<i32> {
```
[the remark this answers is not in the document]
Comment (kubkon) [reply crates/wasi-common/yanix/src/filetime.rs]: Good catch, thanks!

File: crates/wasi-common/yanix/src/filetime.rs [hunk 3]
```diff
@@ -10,40 +10,55 @@ use std::io::Result;
...
+    #[cfg(target_pointer_width = "64")]
+    fn nanoseconds_checked(&self) -> Result<i64>;
+}
+
+impl FileTimeExt for filetime::FileTime {
+    #[cfg(target_pointer_width = "32")]
+    fn seconds_checked(&self) -> Result<i32> {
+        use std::convert::TryInto;
+        use std::io::Error;
+        // 32bit OS expects `tv_sec` field to be `i32`.
```
[the remark this answers is not in the document]
Comment (kubkon) [reply crates/wasi-common/yanix/src/filetime.rs]: Excellent!

File: .github/workflows/main.yml [hunk 4]
```diff
@@ -120,18 +120,30 @@ jobs:
...
+  armv7:
+    name: armv7
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v1
+      with:
+        submodules: true
+    - uses: ./.github/actions/install-rust
+    - run: rustup target add armv7-unknown-linux-gnueabihf
+    - run: cargo check --target armv7-unknown-linux-gnueabihf -p wasi-common
```
Comment (alexcrichton) [inline .github/workflows/main.yml]: Since this likely executes pretty quickly I don't think we necessarily need to have two whole builders for this, could these be collapsed perhaps into a single "check all the targets" builder?

File: crates/wasi-common/yanix/src/sys/linux/mod.rs [hunk 5]
```diff
@@ -8,8 +8,23 @@ use crate::dir::SeekLoc;
 use std::io::Result;
 
 impl SeekLoc {
+    #[cfg(target_pointer_width = "64")]
     pub unsafe fn from_raw(loc: i64) -> Result<Self> {
         let loc = loc.into();
         Ok(Self(loc))
     }
+    #[cfg(target_pointer_width = "32")]
```
Comment (alexcrichton) [inline crates/wasi-common/yanix/src/sys/linux/mod.rs]: Is the `#[cfg]` here necessary? 

I'd love to have as few `#[cfg]` as necessary and it seems like we'd want this logic on all platforms?

File: crates/wasi-common/yanix/src/filetime.rs [hunk 6]
```diff
@@ -10,40 +10,39 @@ use std::io::Result;
...
+    #[cfg(target_pointer_width = "32")]
+    fn nanoseconds_checked(&self) -> Result<i32> {
+        use std::convert::TryInto;
+        // According to [filetime] docs, since the nanoseconds value is always less than 1 billion,
+        // any value should be convertible to `i32`, hence we can `unwrap` outright.
+        //
+        // [filetime]: https://docs.rs/filetime/0.2.8/filetime/struct.FileTime.html#method.nanoseconds
+        Ok(self.nanoseconds().try_into().unwrap())
+    }
+    #[cfg(target_pointer_width = "64")]
```
Comment (alexcrichton) [inline crates/wasi-common/yanix/src/filetime.rs]: Could we avoid having this `#[cfg]`? It seems like it'd be best to just always have the `try_into().unwrap()`, and that I think means we could also remove  the `_checked` from the name, right?

File: crates/wasi-common/yanix/src/filetime.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (sunfishcode) [reply crates/wasi-common/yanix/src/filetime.rs]: We can take this even further: `tv_nsec` is always a `libc::c_long`, so we can return that for both 32-bit and 64-bit platforms and avoid the `target_pointer_width` checks, and since the check always succeeds, we can just return the value instead of a `Result`.

File: crates/wasi-common/yanix/src/filetime.rs (hunk 6 above)
Comment (kubkon) [reply crates/wasi-common/yanix/src/filetime.rs]: Agreed! You beat me to it actually! I was just reworking this bit as it seems silly to have `unwrap` wrapped in `Result` :-D

File: crates/wasi-common/yanix/src/sys/linux/mod.rs (hunk 5 above)
Comment (kubkon) [reply crates/wasi-common/yanix/src/sys/linux/mod.rs]: Agreed about `#[cfg]`s.

Hmm, do you reckon we could collapse both `from_raw` versions into one with `try_into`?

File: crates/wasi-common/yanix/src/sys/linux/mod.rs [hunk 7]
```diff
@@ -8,8 +8,23 @@ use crate::dir::SeekLoc;
...
+        // range of the values. They're just supposed to pass back in the values that we
+        // give them. And any value we give them will be convertable back to `long`,
+        // because that's the type the OS gives them to us in. So return an `EINVAL`.
+        use std::convert::TryInto;
+        use std::io::Error;
+        let loc = loc
+            .try_into()
+            .map_err(|_| Error::from_raw_os_error(libc::EINVAL))?;
+        Ok(Self(loc))
+    }
```
Comment (sunfishcode) [inline crates/wasi-common/yanix/src/sys/linux/mod.rs]: And now that I think about it, we can do a similar thing here -- just have one version for both 32-bit and 64-bit platforms, which returns a `Result<libc::c_long>`, and we can rely on the compiler to optimize away the `map_err` in the case where `c_long` is 64-bit.

File: crates/wasi-common/yanix/src/sys/linux/mod.rs (hunk 5 above)
Comment (alexcrichton) [reply crates/wasi-common/yanix/src/sys/linux/mod.rs]: Ah yeah @sunfishcode [put it well here](https://github.com/bytecodealliance/wasmtime/pull/1269#discussion_r390414227)
