### PR TITLE
Fix a debug assert with `wasm_backtrace(false)`

### LINKED ISSUE #5577: Imported functions fail debug assert when returning errors with wasm_backtrace(false)
### Test Case

```rust
use anyhow::{anyhow, Result};
use wasmtime::*;

struct MyState {
}

fn main() -> Result<()> {
    let mut c = Config::default();

    c.wasm_backtrace(false);

    let engine = Engine::new(&c)?;
    let module = Module::from_file(&engine, "examples/hello.wat")?;

    let mut store = Store::new(
        &engine,
        MyState {},
    );

    let hello_func = Func::wrap(&mut store, |_: Caller<'_, MyState>| {
        Err::<(), anyhow::Error>(anyhow!("bad error"))
    });

    let imports = [hello_func.into()];
    let instance = Instance::new(&mut store, &module, &imports)?;

    let run = instance.get_typed_func::<(), ()>(&mut store, "run")?;

    run.call(&mut store, ())?;

    Ok(())
}
```

### Steps to Reproduce

* Run `run --package wasmtime-cli --example repro`, see the output in "Actual Results"
* Run `run --package wasmtime-cli --release --example repro`, see the output in "Expected Results"
* set `wasm_backtrace(true)`, `run --package wasmtime-cli --example repro`, see the output in "Expected Results" with some more trace

### Expected Results

Output like
```
     Running `target/release/examples/hello`
Error: bad error

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
   2: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,),R>>::into_func::wasm_to_host_shim
   3: <unknown>
   4: wasmtime_runtime::traphandlers::catch_traps::call_closure
   5: wasmtime_setjmp
   6: wasmtime_runtime::traphandlers::<impl wasmtime_runtime::traphandlers::call_thread_state::CallThreadState>::with
   7: wasmtime_runtime::traphandlers::catch_traps
   8: wasmtime::func::invoke_wasm_and_catch_traps
   9: wasmtime::func::typed::TypedFunc<Params,Results>::call
```

### Actual Results

```
     Running `target/debug/examples/hello`
thread 'main' panicked at 'assertion failed: needs_backtrace == backtrace.is_some()', crates/wasmtime/src/trap.rs:101:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/core/src/panicking.rs:114:5
   3: wasmtime::trap::from_runtime_box
             at ./crates/wasmtime/src/trap.rs:101:13
   4: wasmtime::func::invoke_wasm_and_catch_traps::{{closure}}
             at ./crates/wasmtime/src/func.rs:1314:28
   5: core::result::Result<T,E>::map_err
             at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/core/src/result.rs:861:27
   6: wasmtime::func::invoke_wasm_and_catch_traps
             at ./crates/wasmtime/src/func.rs:1314:9
   7: wasmtime::func::typed::TypedFunc<Params,Results>::call_raw
             at ./crates/wasmtime/src/func/typed.rs:177:22
   8: wasmtime::func::typed::TypedFunc<Params,Results>::call
             at ./crates/wasmtime/src/func/typed.rs:88:18
   9: hello::main
             at ./examples/hello.rs:34:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/core/src/ops/function.rs:507:5
```

### Versions and Environment

Wasmtime version or commit:
* e4dc9c79443259e40f3e93b9c7815b0645ebd5c4 (main/dev head at the time of opening this issue)
* As far as I can tell this became an issue after the fixes for https://github.com/bytecodealliance/wasmtime/issues/5037 were implemented (so since v0.3.0)

Operating system: Arch Linux

Architecture: amd64

### Extra Info

I realize that config::wasm_backtrace is deprecated, however today there is no way (?) to tell wasmtime to not re-capture backtraces when returning errors from imported functions.

Not being able to tell wasmtime to not capture backtraces on error leads to behavior similar to https://github.com/bytecodealliance/wasmtime/issues/5037.
* The (admittedly rather extreme) testcase runs a module which will:
  * Recursively call a function ~380 calls deep in wasm, making the wasm stack quite big
  * Then it will call an imported function, which will in turn create a new instance of the recursive module, up to 1000-recucsive module calls
  * Resulting in a call-stack of 300~400k elements (this requires 64MiB native stack)
  * When starting to bail-out, recording that massive backtrace is actually not that slow, takes maybe a few hundred ms.
  * The issue is that currently the backtrace is recorded 1000 times, making the bail-out time in this test case ~13 minutes.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit fixes an issue where when backtraces were disabled but a host function returned an error it would trigger a debug assertion within Wasmtime. The fix here is to update the condition of the debug assertion and add a test doing this behavior to ensure it works in the future.

I've also further taken the liberty in this commit to remove the deprecation notice for `Config::wasm_backtrace`. We don't really have a strong reason for removing this functionality at this time and users have multiple times now reported issues with performance that seem worthwhile to keep the option. The latest issue, #5577, has a use case where it appears the quadratic behavior is back in a way that Wasmtime won't be able to detect. Namely with lots of wasm interleaved with host on the stack if the original error isn't threaded through the entire time then each host error will trigger a new backtrace since it doesn't see a prior backtrace in the error being returned.

While this could otherwise be fixed with only capturing one contiguous backtrace perhaps this seems reasonable enough to leave the `wasm_backtrace` config option for now.

Closes #5577

### CODE REVIEW

File: crates/wasmtime/src/trap.rs [hunk 1]
```diff
@@ -98,7 +98,9 @@ pub(crate) fn from_runtime_box(
             error,
             needs_backtrace,
         } => {
-            debug_assert!(needs_backtrace == backtrace.is_some());
+            debug_assert!(
+                needs_backtrace == backtrace.is_some() || !store.engine().config().wasm_backtrace
+            );
```
Comment (fitzgen) [inline crates/wasmtime/src/trap.rs:103]: Shouldn't we just set `needs_backtrace = false` when the store has backtraces disabled, rather than having two places we need to check for consistency here?

**Review by fitzgen — APPROVED** [review]
r=me with one suggestion, but if it is hard to do because we don't have a store when creating the `wasmtime_runtime::TrapReason::User`, then nevermind

File: crates/wasmtime/src/trap.rs (hunk 1 above)
Comment (alexcrichton) [reply crates/wasmtime/src/trap.rs:103]: I agree yeah it would be good but it's not trivial at least for now. Some refactoring could probably fix this but it doesn't seem too worth it at this time so I'm going to go ahead and merge and leave this for a future rainy day
