### PR TITLE
fix: accurate leaf detection

### LINKED ISSUE #11573: Cranelift's `Function::is_leaf` deduction is inaccurate
Currently `is_leaf` affects whether frame pointers are used at the ABI layer. The  [implementation of this function](https://github.com/bytecodealliance/wasmtime/blob/0744262f79e235b172331f5ba1a2c43b5aedcbfb/cranelift/codegen/src/ir/function.rs#L325), however, just checks if there's no signatures or tls variables. This is inaccurate for a few reasons:

1. A signature might be present to return the address of a function, not necessarily to call the signature.
2. A function may have no signatures or TLS variables but still invoke a libcall.

We'll probably want to scan the VCode for calls to determine if something is a leaf or not.

### PR DESCRIPTION
**Pull request by pnodet**
## Problem

  The previous leaf function detection in `FunctionStencil::is_leaf()` was overly conservative. It would incorrectly mark functions as non-leaf if they:
  - Had any function signatures defined (even if unused)
  - Referenced any TLS global values (even without calling)

  ## Solution

  This PR implements accurate leaf function detection by analyzing the actual generated machine code during the VCode register allocation phase. The new approach:

  1. **Adds `is_call()` method to `MachInst` trait** - Each architecture implementation now identifies its call instructions (including indirect calls and tail calls)

  2. **Detects calls during register allocation** - The `compute_clobbers()` method in VCode now tracks whether any actual call instructions exist

  3. **Removes the conservative `is_leaf()` method** - The old method that made assumptions based on IR-level information is replaced

Fixes #11573

### CODE REVIEW

File: cranelift/codegen/src/ir/function.rs [hunk 1]
```diff
@@ -320,8 +320,18 @@ impl FunctionStencil {
...
+    /// in the IR. It may return false negatives in several cases:
+    /// - A signature might be present only to get a function's address (not to call it)  
+    /// - The function might invoke libcalls even without explicit signatures
+    ///
+    /// The definitive answer is determined after lowering to VCode by scanning for actual
+    /// call instructions. The VCode-based detection updates the ABI layer's is_leaf flag
+    /// for accurate frame pointer and stack check decisions.
+    ///
+    /// This is not to be confused with a "leaf function" in Windows terminology.
     pub fn is_leaf(&self) -> bool {
```
Comment (bjorn3) [inline cranelift/codegen/src/ir/function.rs]: Does this function even still need to exist?

File: cranelift/codegen/src/machinst/vcode.rs [hunk 2]
```diff
@@ -622,6 +622,17 @@ impl<I: VCodeInst> VCodeBuilder<I> {
...
 impl<I: VCodeInst> VCode<I> {
+    /// Check if this function contains any call instructions.
+    /// This scans the VCode to determine if the function is truly a leaf function.
+    pub fn has_calls(&self) -> bool {
+        for inst in &self.insts {
+            if inst.is_call() {
+                return true;
+            }
+        }
+        false
```
Comment (bjorn3) [inline cranelift/codegen/src/machinst/vcode.rs]: `self.insts.iter().any(|inst| inst.is_call())`?

Comment (pnodet) [reply cranelift/codegen/src/machinst/vcode.rs]: Indeed, looks cleaner, will change.

File: cranelift/codegen/src/ir/function.rs (hunk 1 above)
Comment (pnodet) [reply cranelift/codegen/src/ir/function.rs]: I'll let @alexcrichton weigh in on this

Comment (cfallin) [reply cranelift/codegen/src/ir/function.rs]: (I'm not Alex, but I noted this issue originally and suggested that he file #11573 [here](https://github.com/bytecodealliance/wasmtime/pull/11570#discussion_r2310845668))

IMHO: we should remove this method -- firstly, we don't need it internally, and secondly, it's nearly impossible to use it for anything useful externally because of the caveats we have found. An API that looks "almost useful" but provides misleading or inaccurate results with both false positives *and* false negatives is a footgun that shouldn't exist.

File: cranelift/codegen/src/machinst/compile.rs [hunk 3]
```diff
@@ -95,3 +99,137 @@ pub fn compile<B: LowerBackend + TargetIsa>(
 
     Ok((vcode, regalloc_result))
 }
+
+#[cfg(test)]
+mod tests {
```
Comment (cfallin) [inline cranelift/codegen/src/machinst/compile.rs]: Thanks for adding these tests, but (i) they all appear to be testing `is_leaf`, which we want to remove, per above; (ii) they don't actually test the ABI behavior, which is visible only in the emitted code.

Could you add some compile filetests instead, showing disassemblies with and without frame-pointer setup? In particular I'd expect the case where I commented and asked for #11573 to be filed to revert back to no-frame-pointer.

File: cranelift/codegen/src/machinst/compile.rs [hunk 4]
```diff
@@ -49,6 +49,10 @@ pub fn compile<B: LowerBackend + TargetIsa>(
     log::debug!("Number of lowered vcode blocks: {}", vcode.num_blocks());
     trace!("vcode from lowering: \n{:?}", vcode);
 
+    // Update is_leaf based on actual VCode analysis
+    let is_leaf = !vcode.has_calls();
+    vcode.abi.set_is_leaf(is_leaf);
```
Comment (cfallin) [inline cranelift/codegen/src/machinst/compile.rs]: Rather than use a mutable setter pattern with action-at-a-distance plumbing, let's compute the property directly from the ABI code. We already make a pass to find clobbers and so we should be able to detect this at the same time.

File: cranelift/codegen/src/machinst/vcode.rs [hunk 5]
```diff
@@ -622,6 +622,12 @@ impl<I: VCodeInst> VCodeBuilder<I> {
 const NO_INST_OFFSET: CodeOffset = u32::MAX;
 
 impl<I: VCodeInst> VCode<I> {
+    /// Check if this function contains any call instructions.
+    /// This scans the VCode to determine if the function is truly a leaf function.
+    pub fn has_calls(&self) -> bool {
+        self.insts.iter().any(|inst| inst.is_call())
+    }
```
Comment (cfallin) [inline cranelift/codegen/src/machinst/vcode.rs]: A few things:
- We want to compute this during the clobber scan in ABI code, so let's not do a separate scan;
- Providing an accessor method like this is (IMHO) slightly un-idiomatic, in that it hides a potentially expensive scan behind something that looks like a simple feature/flag test;
- If we do add a helper, (tiny minor nit but) putting it right at the top of the VCode methods, before `fn new`, is probably not the place to do it to make the file read nicely.

**Review by cfallin — COMMENTED** [review]
Thanks for working on this! Leaving a few thoughts below:

**Comment by pnodet** [comment]
Thanks for the suggestions @cfallin
If it's okay with you all I'll wait for a decision on wether `is_leaf` should be removed or improved before implementing more changes

**Comment by cfallin** [comment]
> If it's okay with you all I'll wait for a decision on wether is_leaf should be removed or improved before implementing more changes

As noted in my code review, please remove it, thanks!

(In more detail: I am a core reviewer on Cranelift too and originally asked for the issue to be filed, so I'm happy to take the review; there isn't any other "decision" process, but you're welcome to raise any other concerns or, in the limit, take it to the Cranelift weekly meeting)

File: cranelift/codegen/src/isa/aarch64/inst/mod.rs [hunk 6]
```diff
@@ -1080,6 +1080,16 @@ impl MachInst for Inst {
         }
     }
 
+    fn is_call(&self) -> bool {
+        match self {
+            Inst::Call { .. }
+            | Inst::CallInd { .. }
+            | Inst::ReturnCall { .. }
+            | Inst::ReturnCallInd { .. } => true,
```
Comment (bjorn3) [inline cranelift/codegen/src/isa/aarch64/inst/mod.rs]: Do we actually need to set up a stack frame if the only call we would do is a tail call? Fair chance the tail call handling doesn't currently handle not having a stack frame, so this doesn't have to be changed in this PR. Just noting a potential optimization opportunity.

File: cranelift/codegen/src/machinst/vcode.rs [hunk 7]
```diff
@@ -720,6 +725,8 @@ impl<I: VCodeInst> VCode<I> {
             }
         }
 
+        self.abi.set_is_leaf(!has_calls);
```
Comment (bjorn3) [inline cranelift/codegen/src/machinst/vcode.rs]: How hard would it be to return this value instead of mutating the `Callee`?

Comment (pnodet) [reply cranelift/codegen/src/machinst/vcode.rs]: @bjorn3 I don't think this would be too much of a hassle, I could see something like

```diff
-  let clobbers = self.compute_clobbers(regalloc);
-  self.abi.compute_frame_layout(&self.sigs, regalloc.num_spillslots, clobbers);

+  let (clobbers, is_leaf) = self.compute_clobbers(regalloc);
+  self.abi.set_is_leaf(is_leaf);
+  self.abi.compute_frame_layout(&self.sigs, regalloc.num_spillslots, clobbers);
```

File: cranelift/filetests/filetests/isa/riscv64/tls-elf.clif [hunk 8]
```diff
@@ -64,34 +64,19 @@ block0(v0: i64):
 }
 
 ; VCode:
-;   addi sp,sp,-16
-;   sd ra,8(sp)
-;   sd fp,0(sp)
-;   mv fp,sp
 ; block0:
 ;   elf_tls_get_addr a0,userextname0
```
Comment (bjorn3) [inline cranelift/filetests/filetests/isa/riscv64/tls-elf.clif]: This needs to be considered a call instruction too. As should the `blr x3 ; reloc_external Aarch64TlsDescCall u1:0 0` on arm64 and if it doesn't already happen whichever instruction is used for `__tls_get_addr` calls in the `tls_value` lowering on other platforms.

File: cranelift/codegen/src/isa/aarch64/inst/mod.rs (hunk 6 above)
Comment (pnodet) [reply cranelift/codegen/src/isa/aarch64/inst/mod.rs]: @bjorn3 We could have  the vcode analysis distinguish 
  - Leaf: No calls at all
  - Tail-call-only: Only tail calls
  - Non-leaf: Has regular calls (with or without tail calls)

Something like 

```rust
 fn call_type(&self) -> CallType {
      match self {
          Inst::Call { .. }
          | Inst::CallInd { .. } => CallType::Regular,
          
          Inst::ReturnCall { .. }
          | Inst::ReturnCallInd { .. } => CallType::TailOnly,
          
          _ => CallType::None,
      }
  }
```

so that tail call only functions skip prologue and epilogue?

File: cranelift/codegen/src/machinst/vcode.rs (hunk 7 above)
Comment (bjorn3) [reply cranelift/codegen/src/machinst/vcode.rs]: I meant removing `set_is_leaf` and the `is_leaf` field of `Callee` entirely and instead passing `is_leaf` around to functions that need it. I don't know how much of a hassle that would be.

File: cranelift/filetests/filetests/isa/riscv64/tls-elf.clif (hunk 8 above)
Comment (pnodet) [reply cranelift/filetests/filetests/isa/riscv64/tls-elf.clif]: I'm wondering if in 

https://github.com/bytecodealliance/wasmtime/blob/10d2cbc59d35b14c3027a8542f636c591b2ec96b/cranelift/codegen/src/isa/x64/abi.rs#L937

Should we have something like

```diff
-          let setup_area_size = 16; // RBP, return address
+          let setup_area_size = is_leaf {
+              0
+          } else {
+              16 // RBP, return address
+          };
```

Comment (pnodet) [reply cranelift/filetests/filetests/isa/riscv64/tls-elf.clif]: And also checking flags.preserve_frame_pointers

Comment (bjorn3) [reply cranelift/filetests/filetests/isa/riscv64/tls-elf.clif]: You mean for tail calls? I think those are best left to a separate PR.

File: cranelift/codegen/src/machinst/vcode.rs (hunk 7 above)
Comment (pnodet) [reply cranelift/codegen/src/machinst/vcode.rs]: I made another pass on this

File: cranelift/codegen/src/isa/x64/inst/mod.rs [hunk 9]
```diff
@@ -1281,6 +1281,19 @@ impl MachInst for Inst {
...
 
+    fn is_call(&self) -> bool {
+        match self {
+            Inst::CallKnown { .. }
+            | Inst::CallUnknown { .. }
+            | Inst::ReturnCallKnown { .. }
+            | Inst::ReturnCallUnknown { .. }
+            | Inst::ElfTlsGetAddr { .. }
+            | Inst::MachOTlsGetAddr { .. }
+            | Inst::CoffTlsGetAddr { .. } => true,
```
Comment (bjorn3) [inline cranelift/codegen/src/isa/x64/inst/mod.rs]:
```suggestion
            | Inst::MachOTlsGetAddr { .. } => true,
```

PE/COFF unlike other object file formats directly emits a `%fs` relative access rather than by emitting a call that may later be relaxed by the linker.

**Comment by pnodet** [comment]
@cfallin I've updated this PR thanks to the given insights and to reflect the changes discussed above, would mind giving it another look?

File: cranelift/codegen/src/machinst/vcode.rs [hunk 10]
```diff
@@ -673,8 +673,9 @@ impl<I: VCodeInst> VCode<I> {
         self.insts.len()
     }
 
-    fn compute_clobbers(&self, regalloc: &regalloc2::Output) -> Vec<Writable<RealReg>> {
+    fn compute_clobbers(&self, regalloc: &regalloc2::Output) -> (Vec<Writable<RealReg>>, bool) {
```
Comment (cfallin) [inline cranelift/codegen/src/machinst/vcode.rs]: Let's call this `compute_clobbers_and_leaf` for clarity, now that it returns both.

File: cranelift/codegen/src/machinst/vcode.rs [hunk 11]
```diff
@@ -694,6 +695,11 @@ impl<I: VCodeInst> VCode<I> {
                 }
             }
 
+            // Check if this instruction is a call - if so, function is not a leaf
```
Comment (cfallin) [inline cranelift/codegen/src/machinst/vcode.rs]: Tiny nit, but our style is usually to end comments with a `.`.

File: cranelift/filetests/filetests/isa/x64/leaf_function_detection.clif [hunk 12]
```diff
@@ -0,0 +1,223 @@
+;; Test leaf function detection across different function types.
+;; This test verifies that the is_leaf detection works correctly for:
+;; - True leaf functions (no calls)
+;; - Non-leaf functions (with calls, call_indirect)
```
Comment (cfallin) [inline cranelift/filetests/filetests/isa/x64/leaf_function_detection.clif:4]: Can we update the header comment here to note that we're including the test for completeness with respect to other ISAs, but that x64 does not yet implement the leaf-function optimization, so frame setup is still present below?

**Review by cfallin — APPROVED** [review]
Thanks for the updates! Looks generally good now. Just a few small nits below; happy to merge once those are changed.

File: cranelift/filetests/filetests/isa/riscv64/tls-elf.clif (hunk 8 above)
Comment (cfallin) [reply cranelift/filetests/filetests/isa/riscv64/tls-elf.clif]: x64 actually doesn't implement the leaf-function optimization at all (it is a bit different than the other ISAs because the call still pushes the return address; that created some complications that I'm forgetting at the moment; in any case, indeed, that is territory for a separate PR).

File: cranelift/codegen/src/isa/aarch64/inst/mod.rs (hunk 6 above)
Comment (cfallin) [reply cranelift/codegen/src/isa/aarch64/inst/mod.rs]: Let's leave tail call support for a separate PR as well -- it would be nice to have, but the tail-call implementation itself is quite finicky and specific to our frame layout, and would need updating as well; in other words, it's not just a matter of omitting the prologue.

**Comment by pnodet** [comment]
Thanks for the review. I made the changes you pointed out. I'll let you merge at your own convenience!

**Review by cfallin — APPROVED** [review]
Thanks!

**Comment by cfallin** [comment]
@pnodet it looks like this needs some test expectation updates (use the "bless" environment variable to do this then commit the deltas in a separate commit) -- happy to merge once CI is green.

**Comment by pnodet** [comment]
@cfallin Indeed, this was from newly added tests and I hadn't rebased the main branch since

**Comment by cfallin** [comment]
@pnodet there is a failure when testing this PR on the merge queue because `main` now has new filetests whose outputs shift with this PR. Could you merge (not rebase) `main` and then in a separate commit, update filetest outputs?

**Comment by pnodet** [comment]
@cfallin @bjorn3 Thanks!
