### PR TITLE
Don't generate DWARF sections when no functions were compiled.

### LINKED ISSUE #887: Assertion failure generating debuginfo on a module with no functions
Given this wasm file:

```wat
(module (memory 1))
```

This panics with:

```
$ wasmtime -g ./foo.wat
thread 'main' panicked at 'assertion failed: `(left > right)`
  left: `0`,
 right: `0`', crates/debug/src/lib.rs:72:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

cc @yurydelendik

### PR DESCRIPTION
**Pull request by yurydelendik**
Fixes #887 

* Allow modules with no memory to generate a DWARF information
* Don't generate DWARF sections when no functions were compiled

### CODE REVIEW

File: crates/debug/src/transform/expression.rs [hunk 1]
```diff
@@ -7,14 +7,28 @@ use wasmtime_environ::entity::EntityRef;
...
+    pub memory_offset: ModuleMemoryOffset,
     pub stack_slots: &'a StackSlots,
 }
 
+impl<'a> FunctionFrameInfo<'a> {
+    fn vmctx_memory_offset(&self) -> Option<i64> {
+        match self.memory_offset {
+            ModuleMemoryOffset::Defined(x) => Some(x as i64),
+            ModuleMemoryOffset::Imported(_) => {
+                // TODO implement memory offset for imported memory
```
Comment (fitzgen) [inline crates/debug/src/transform/expression.rs]: File an issue so this doesn't get forgotten?

Comment (yurydelendik) [reply crates/debug/src/transform/expression.rs]: https://github.com/bytecodealliance/wasmtime/issues/896
