### PR TITLE
Fix missing modification of jump table in licm

### LINKED ISSUE #1080: assertion failed: !self.opcode().is_branch() during licm
Compile

```rust
// run-pass

// aux-build:xcrate-reachable.rs

#![feature(generator_trait)]

extern crate xcrate_reachable as foo;

use std::ops::Generator;
use std::pin::Pin;

fn main() {
    Pin::new(&mut foo::foo()).resume();
}
```

using rustc_codegen_cranelift with `opt_level=best` and you get:

```
---- [run-pass] run-pass/generator/xcrate-reachable.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit code: 101
command: "/home/bjorn/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc" "/home/bjorn/Documenten/rustc_codegen_cranelift/rust/src/test/run-pass/generator/xcrate-reachable.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-o" "/home/bjorn/Documenten/rustc_codegen_cranelift/rust/build/x86_64-unknown-linux-gnu/test/run-pass/generator/xcrate-reachable/a" "-Crpath" "-O" "-Zunstable-options" "-Zcodegen-backend=/home/bjorn/Documenten/rustc_codegen_cranelift/rust/../target/debug/librustc_codegen_cranelift.so" "--sysroot" "/home/bjorn/Documenten/rustc_codegen_cranelift/rust/../build_sysroot/sysroot" "-Cpanic=abort" "-Lnative=/home/bjorn/Documenten/rustc_codegen_cranelift/rust/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/bjorn/Documenten/rustc_codegen_cranelift/rust/build/x86_64-unknown-linux-gnu/test/run-pass/generator/xcrate-reachable/auxiliary"
stdout:
------------------------------------------
Instance { def: Item(DefId(9/1:10 ~ xcrate_reachable[8787]::foo[0]::{{closure}}[0])), substs: [(), u32, {()}] } _ZN16xcrate_reachable3foo28_$u7b$$u7b$closure$u7d$$u7d$17he526fe6105ca50ffE

------------------------------------------
stderr:
------------------------------------------
thread 'rustc' panicked at 'assertion failed: !self.opcode().is_branch()', /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-codegen/src/ir/instructions.rs:255:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::begin_panic
             at /rustc/474e7a6486758ea6fc761893b1a49cd9076fb0ab/src/libstd/panicking.rs:408
   7: cranelift_codegen::licm::do_licm
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-codegen/src/ir/instructions.rs:255
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-codegen/src/licm.rs:140
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-codegen/src/licm.rs:89
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-codegen/src/licm.rs:41
   8: cranelift_codegen::context::Context::compile
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-codegen/src/context.rs:286
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-codegen/src/context.rs:136
   9: cranelift_module::module::Module<B>::define_function
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-module/src/module.rs:517
  10: rustc_codegen_cranelift::base::trans_fn
             at src/base.rs:202
  11: rustc_codegen_cranelift::base::trans_mono_item
             at src/base.rs:46
  12: rustc_codegen_cranelift::codegen_mono_items::{{closure}}::{{closure}}
             at src/lib.rs:473
  13: rustc_codegen_cranelift::unimpl::try_unimpl::{{closure}}
             at src/unimpl.rs:28
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/474e7a6486758ea6fc761893b1a49cd9076fb0ab/src/libstd/panic.rs:309
  15: std::panicking::try::do_call
             at /rustc/474e7a6486758ea6fc761893b1a49cd9076fb0ab/src/libstd/panicking.rs:293
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  17: std::panicking::try
             at /rustc/474e7a6486758ea6fc761893b1a49cd9076fb0ab/src/libstd/panicking.rs:272
  18: std::panic::catch_unwind
             at /rustc/474e7a6486758ea6fc761893b1a49cd9076fb0ab/src/libstd/panic.rs:388
  19: rustc_codegen_cranelift::unimpl::try_unimpl
             at src/unimpl.rs:28
  20: rustc_codegen_cranelift::codegen_mono_items::{{closure}}
             at src/lib.rs:471
  21: rustc_codegen_cranelift::time
             at src/lib.rs:484
  22: rustc_codegen_cranelift::codegen_mono_items
             at src/lib.rs:469
  23: rustc_codegen_cranelift::codegen_cgus
             at src/lib.rs:456
  24: <rustc_codegen_cranelift::CraneliftCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
             at src/lib.rs:318
  25: rustc::util::common::time
  26: rustc_interface::passes::start_codegen
  27: rustc::ty::context::tls::enter_global
  28: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  29: rustc_interface::passes::create_global_ctxt::{{closure}}
  30: rustc_interface::passes::BoxedGlobalCtxt::enter
  31: rustc_interface::queries::Query<T>::compute
  32: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen
  33: rustc_interface::interface::run_compiler_in_existing_thread_pool
  34: std::thread::local::LocalKey<T>::with
  35: scoped_tls::ScopedKey<T>::set
  36: syntax::with_globals
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.35.0-nightly (474e7a648 2019-04-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z threads=1 -Z ui-testing -Z unstable-options -Z codegen-backend=/home/bjorn/Documenten/rustc_codegen_cranelift/rust/../target/debug/librustc_codegen_cranelift.so -C rpath -C panic=abort
```

### LINKED ISSUE #1648: Cranelift: assertion failed: !self.opcode().is_branch()
- What are the steps to reproduce the issue? Can you include a CLIF test case,
  ideally reduced with the `bugpoint` clif-util command?

```
(bash@joshua-ThinkPad-P51s) ~/.../rust/rcc ▶️ /bin/cat crash.c
void foo(void) {
  switch (1) {
    while(1)
      case 1:;
    case 0:;
  }
}
(bash@joshua-ThinkPad-P51s) ~/.../rust/rcc ▶️ cargo run crash.c --debug-asm
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `/home/joshua/.local/lib/cargo/target/debug/rcc crash.c --debug-asm`
function u0:0() system_v {
; function 0: foo

    jt0 = jump_table [block5, block6]

block0:
    v0 = iconst.i64 1
    ; dummy
    jump block1

block2:
    jump block4

block4:
    v1 = bconst.b1 true
    ; while ((1) != ((long)(0)))
    brz v1, block5
    jump block6

; case 1
block6:
    ; loop start
    jump block4

; case 0
block5:
    ; end switch
    jump block3

block1:
    jump block7

block7:
    br_table.i64 v0, block3, jt0

block3:
    return
}

The application panicked (crashed).
Message:  assertion failed: !self.opcode().is_branch()
Location: /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.63.0/src/ir/instructions.rs:254
```

- What do you expect to happen? What does actually happen? Does it panic, and
  if so, with which assertion?

I don't know why this code doesn't work. It all seems valid to me and the panic doesn't tell me which instruction isn't valid. The verifier reports no errors and the panic happens only when defining the function.

- Which Cranelift version / commit hash / branch are you using?

`cranelift 0.63.0`

- If relevant, can you include some extra information about your environment?
  (Rust version, operating system, architecture...)

target is `x86_64-unknown-linux-gnu`

### PR DESCRIPTION
**Pull request by Y-Nak**
Resolve #1648 and resolve #1080.
- [x] This has been discussed in issue #1648 and #1080
- [x] A short description of what this does, why it is needed;

1. Fix inconsistency between `branch_destination` and `branch_destination_mut` (Just adding `IndirectJump` case to `branch_destination_mut`).
2. Modify jump table entry if it points at loop header, and also modify destination if it points at loop header.

- [x] This PR contains test cases, if meaningful.

- [x] A reviewer from the core maintainer team has been assigned for this PR.
@iximeow Could you review this please?  I know you are aware of the issue, so please feel free to close this PR if you have started looking into.

### CODE REVIEW

File: cranelift/codegen/src/licm.rs [hunk 1]
```diff
@@ -87,7 +88,33 @@ fn create_pre_header(
...
+                // Change branch destination to preheader.
+                BranchInfo::SingleDest(..) => func.change_branch_destination(last_inst, pre_header),
+                BranchInfo::Table(table, maybe_dest) => {
+                    // Change each entry pointing at header to point at preheader.
+                    for entry in func.jump_tables[table].iter_mut() {
+                        if *entry == header {
+                            *entry = pre_header;
+                        }
+                    }
+                    // Change default destination if it pointts at loop header.
```
Comment (bjorn3) [inline cranelift/codegen/src/licm.rs:101]:
```suggestion
                    // Change default destination if it points at loop header.
```

Comment (Y-Nak) [reply cranelift/codegen/src/licm.rs:101]: Oh, thanks!

File: cranelift/filetests/filetests/licm/rewrite-jump-table.clif [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+function %rewrite_jump_table() {
+    jt0 = jump_table [block1, block2]
+
+                        block0:
+                            v0 = iconst.i64 1
+                            v1 = jump_table_base.i64 jt0
+                            v2 = jump_table_entry.i64 v0, v1, 4, jt0
+                            v3 = iadd v1, v2
+[RexOp1indirect_jmp#40ff]   indirect_jump_table_br v3, jt0
```
Comment (cfallin) [inline cranelift/filetests/filetests/licm/rewrite-jump-table.clif:12]: Can we remove the encodings here? They'll cause issues when we switch to the new backend by default and I don't think they're needed for the test.

File: cranelift/codegen/src/licm.rs [hunk 3]
```diff
@@ -87,7 +88,33 @@ fn create_pre_header(
     {
         // We only follow normal edges (not the back edges)
         if !domtree.dominates(header, last_inst, &func.layout) {
-            func.change_branch_destination(last_inst, pre_header);
+            match func.dfg.analyze_branch(last_inst) {
+                // Change branch destination to preheader.
+                BranchInfo::SingleDest(..) => func.change_branch_destination(last_inst, pre_header),
```
Comment (cfallin) [inline cranelift/codegen/src/licm.rs:93]: It seems we could fold this into a helper alongside `change_branch_destination` on `Function`, by defining a `rewrite_branch_destination(inst, old_target, new_target)` that replaces any `old_target` target in the instruction with `new_target`, doing the replacement on any target(s) that exist in the instruction. Thoughts? This would also remove the awkward match below.

**Review by cfallin — COMMENTED** [review]
Thanks very much for this! In principle LGTM; just a suggestion for a small refactor below to fold the improvement into the API.

File: cranelift/filetests/filetests/licm/rewrite-jump-table.clif (hunk 2 above)
Comment (Y-Nak) [reply cranelift/filetests/filetests/licm/rewrite-jump-table.clif:12]: We can remove the encodings iff the test runs with the new backend, otherwise `Verifier::verify_encodings` fails because  some `jump` insts with encodings is inserted here.
https://github.com/bytecodealliance/wasmtime/blob/2cec20aa57037ecdfaef46176f31fe8f6b33c2d8/cranelift/codegen/src/licm.rs#L94-L98
So, I'm inclined to remove all encodings from the test and change the target machine to `aarch64` from `x86-64`,  what do you think about it?

File: cranelift/codegen/src/licm.rs (hunk 3 above)
Comment (Y-Nak) [reply cranelift/codegen/src/licm.rs:93]: Exactly! Thanks for pointing out.
I'll add `Function::rewrite_branch_destination`.

File: cranelift/filetests/filetests/licm/rewrite-jump-table.clif (hunk 2 above)
Comment (cfallin) [reply cranelift/filetests/filetests/licm/rewrite-jump-table.clif:12]: Yes, that sounds good, thanks!

**Comment by cfallin** [comment]
@Y-Nak -- do you think you'll be updating this within the next day or two? I'm happy to adopt it and get it reviewed/merged otherwise! I don't mean to apply too much pressure, I just want to get it closed somewhat soon as it's a fuzzbug that may be blocking some further fuzzing coverage :-) Either way is fine, just let us know!

**Comment by Y-Nak** [comment]
@cfallin Oh, I'm sorry. I just finished fixing it now.

**Comment by Y-Nak** [comment]
## Changes
* Add `Function::rewrite_branch_destination` method.
* Remove the encodings from the test.

**Review by cfallin — APPROVED** [review]
This is great, thank you!
