### PR TITLE
Fix AArch64 ABI to respect half-caller-save, half-callee-save vec regs.

### LINKED ISSUE #2254: AArch64: conform to AArch64 calling convention's half-caller/half-callee-save vector register conventions.
It arose in #2228 that our current implementation of the standard (SysV / AAPCS) calling convention on AArch64 is not quite right. In the real calling convention, the lower 64-bit halves of some vector registers are callee-save, while the upper 64-bit halves are caller-save. We currently treat them as fully callee-save. This is correct (if conservative) w.r.t. clobber-saves in prologue/epilogue code, but is incorrect w.r.t. callsites.

The most correct fix is to support overlapping register classes in regalloc.rs (see bytecodealliance/regalloc.rs#98). However, in #2228, a simpler stopgap fix was proposed. This fix also requires a small modification to regalloc.rs, but simply to omit call instructions' defs/mods from the clobbered-register-set computation. If the caller and callee have the same ABI, then this is safe.

If the full fix in regalloc.rs is not an easy change (it appears it will not be, as aliasing registers will interact in a fundamental way with the core allocation data structures) then IMHO we should implement the stopgap fix for now, so that when we call into library or other code, we don't have subtle correctness issues with half-clobbered vector values.

cc @julian-seward1, @bnjbvr, @akirilov-arm

### PR DESCRIPTION
**Pull request by cfallin**
This PR updates the AArch64 ABI implementation so that it (i) properly
respects that v8-v15 inclusive have callee-save lower halves, and
caller-save upper halves, by conservatively approximating (to full
registers) in the appropriate directions when generating prologue
caller-saves and when informing the regalloc of clobbered regs across
callsites.

In order to prevent saving all of these vector registers in the prologue
of every non-leaf function due to the above approximation, this also
makes use of a new regalloc.rs feature to exclude call instructions'
writes from the clobber set returned by register allocation. This is
safe whenever the caller and callee have the same ABI (because anything
the callee could clobber, the caller is allowed to clobber as well
without saving it in the prologue).

Fixes #2254.

### CODE REVIEW

File: cranelift/codegen/src/isa/aarch64/inst/mod.rs [hunk 1]
```diff
@@ -2491,6 +2496,21 @@ impl MachInst for Inst {
...
+        // We exclude call instructions from the clobber-set when they are calls
+        // from caller to callee with the same ABI. Such calls cannot possibly
+        // force any new registers to be saved in the prologue, because anything
+        // that the callee clobbers, the caller is also allowed to clobber. This
+        // both saves work and enables us to more precisely follow the
+        // half-caller-save, half-callee-save SysV ABI for some vector
+        // registers.
+        match self {
+            &Inst::Call { ref info } => info.caller_callconv != info.callee_callconv,
+            &Inst::CallInd { ref info } => info.caller_callconv != info.callee_callconv,
```
Comment (bnjbvr) [inline cranelift/codegen/src/isa/aarch64/inst/mod.rs:2509]: uber-nit: can you join the two cases, please? `&Inst::Call { ref info } | &Inst::CallInd { ref info }`

File: cranelift/codegen/src/isa/aarch64/inst/mod.rs [hunk 2]
```diff
@@ -2491,6 +2496,21 @@ impl MachInst for Inst {
...
     }
 
+    fn is_included_in_clobbers(&self) -> bool {
+        // We exclude call instructions from the clobber-set when they are calls
+        // from caller to callee with the same ABI. Such calls cannot possibly
+        // force any new registers to be saved in the prologue, because anything
+        // that the callee clobbers, the caller is also allowed to clobber. This
+        // both saves work and enables us to more precisely follow the
+        // half-caller-save, half-callee-save SysV ABI for some vector
+        // registers.
```
Comment (bnjbvr) [inline cranelift/codegen/src/isa/aarch64/inst/mod.rs:2506]: Maybe worth adding a back reference to the other comment (that references this one) around callee-saved in call sites?

File: cranelift/codegen/src/isa/aarch64/inst/mod.rs [hunk 3]
```diff
@@ -2491,6 +2496,21 @@ impl MachInst for Inst {
         }
     }
 
+    fn is_included_in_clobbers(&self) -> bool {
+        // We exclude call instructions from the clobber-set when they are calls
+        // from caller to callee with the same ABI. Such calls cannot possibly
+        // force any new registers to be saved in the prologue, because anything
+        // that the callee clobbers, the caller is also allowed to clobber. This
```
Comment (bnjbvr) [inline cranelift/codegen/src/isa/aarch64/inst/mod.rs:2503]: This rule about caller- vs callee- saved is actually generic over the targets, so we could also apply it for x64, right?

File: cranelift/codegen/src/isa/aarch64/abi.rs [hunk 4]
```diff
@@ -808,8 +816,21 @@ fn is_caller_save_reg(call_conv: isa::CallConv, r: RealReg) -> bool {
...
-            // v0 - v7 inclusive and v16 - v31 inclusive are caller-saves.
-            r.get_hw_encoding() <= 7 || (r.get_hw_encoding() >= 16 && r.get_hw_encoding() <= 31)
+            // v0 - v7 inclusive and v16 - v31 inclusive are caller-saves. The
+            // upper 64 bits of v8 - v15 inclusive are also caller-saves.
+            // However, because we cannot currently represent partial registers
+            // to regalloc.rs, we indicate here that every vector register is
+            // caller-save. Because this function is used at *callsites*,
+            // approximating in this direction (save more than necessary) is
+            // conservative and thus safe.
+            //
```
Comment (julian-seward1) [inline cranelift/codegen/src/isa/aarch64/abi.rs:826]: This all is reasonable (and as we discussed and agreed), but it has the side effect that I am not entirely happy with the fact that the name of this function doesn't make clear that it now only pertains to call sites.  Would you be prepared to consider the following changes (or something modulo them, so as to increase clarity for the reader) ?

* change name of function to `is_reg_clobbered_by_a_call_instruction`

* change name of formal param from `call_conv` to `call_conv_of_callee`  (since it's kinda ambiguous at least from the name)

File: cranelift/codegen/src/isa/aarch64/inst/mod.rs [hunk 5]
```diff
@@ -2491,6 +2496,21 @@ impl MachInst for Inst {
         }
     }
 
+    fn is_included_in_clobbers(&self) -> bool {
```
Comment (julian-seward1) [inline cranelift/codegen/src/isa/aarch64/inst/mod.rs:2499]: Similar naming concern here.  Also, for good performance, this needs to be inlined, no?

**Review by julian-seward1 — COMMENTED** [review]
Functionally fine; but some concern about creeping ambiguity in naming.  Can we discuss revised names?

File: cranelift/codegen/src/isa/aarch64/inst/mod.rs (hunk 1 above)
Comment (cfallin) [reply cranelift/codegen/src/isa/aarch64/inst/mod.rs:2509]: Unfortunately they're different types (`CallInfo` vs. `CallIndInfo`) so we can't unify the patterns here :-/

File: cranelift/codegen/src/isa/aarch64/inst/mod.rs (hunk 2 above)
Comment (cfallin) [reply cranelift/codegen/src/isa/aarch64/inst/mod.rs:2506]: Done!

File: cranelift/codegen/src/isa/aarch64/inst/mod.rs (hunk 3 above)
Comment (cfallin) [reply cranelift/codegen/src/isa/aarch64/inst/mod.rs:2503]: Indeed it is, although we get less benefit (only the compile-time improvement, no generated-code change) because x64 doesn't have half-caller/half-callee saves. Since it adds overhead to `Inst::CallKnown`/`Inst::CallUnknown` (we don't out-of-line the fields yet) and there are issues with the size of `Inst`, I'm inclined not to go down this path, at least at first. Can certainly look at this in a subsequent PR though!

File: cranelift/codegen/src/isa/aarch64/inst/mod.rs (hunk 5 above)
Comment (cfallin) [reply cranelift/codegen/src/isa/aarch64/inst/mod.rs:2499]: Verified that inlining occurs; rustc seems to be doing the right thing here. (It's statically monomorphized so I expect it always would as long as someone does not inflate the body to some huge size...).

Comment (cfallin) [reply cranelift/codegen/src/isa/aarch64/inst/mod.rs:2499]: Re: naming: were you thinking something more specific to calls, as above, or something else?

I put a bit of thought into this and I'm not sure that I like including "call instruction", as the concept is more general. (In principle the `MachInst` layer doesn't even know about the concept of a call instruction.) The concept really is just "should we aggregate this instruction's effects into the summary of clobbered registers". Any other suggestions?

Or if we do decide that this is specific to calls, I think I'd prefer `is_call_instruction_with_ignored_clobbers()`. I could go with this; it just seems a bit non-orthogonal, is all.

File: cranelift/codegen/src/isa/aarch64/abi.rs (hunk 4 above)
Comment (cfallin) [reply cranelift/codegen/src/isa/aarch64/abi.rs:831]: Ah, I like this much better! The `ABIMachineSpec` now has `get_regs_clobbered_by_call()`, and aarch64 has `is_reg_saved_in_prologue()`, `get_regs_saved_in_prologue()`, and `is_reg_clobbered_by_call()`.

**Comment by cfallin** [comment]
Thanks! Updated based on comments. I definitely like the renaming in terms of explicit actions ("clobbered by call", "saved in prologue") in the ABI impls. The only open question is the naming of `is_included_in_clobbers()` in the `MachInst` interface; I'm curious if you have any other good names in mind. Open to whatever makes sense!

File: cranelift/codegen/src/isa/aarch64/inst/mod.rs (hunk 5 above)
Comment (julian-seward1) [reply cranelift/codegen/src/isa/aarch64/inst/mod.rs:2499]: Ah, leave it as it is then.  That the other names have been improved is good enough for me.  Thanks for doing that.

**Review by julian-seward1 — APPROVED** [review]

**Comment by akirilov-arm** [comment]
I also had a quick look at the changes and they are good, but now I have realized that there is a gap in the tests - there is nothing that covers the callee side. However, that is definitely a job for another PR, in particular one that is going to fix function prologues and epilogues, so that they deal only with the lower 64 bits of the SIMD & FP registers. At the very least we should have a function with a chain of operations such as `v1 = v0 + v0, v2 = v1 + v1, ..., f(v0, v1, v2, ...)` to force the compiler to use the callee-saved registers, possibly mixing data types (`f32`, `f64` and `i8x16`).

**Comment by cfallin** [comment]
@akirilov-arm good point; thanks! I just updated the PR to include a test (`prologue.clif`) that does exactly that, and checks that all of the callee-saves are saved (lower halves of v8-v15, covered by saving all of v8-v15 currently). Let me know if this covers what you had in mind.

**Comment by akirilov-arm** [comment]
@cfallin Yes, and it is simpler than what I had in mind, which is even better. I think that together with the other tests it will be a good exercise for an optimal with respect to the AAPCS64 implementation (trying to be a little bit forward-thinking here), and yet it demonstrates the current issues that are simpler, namely handling the full registers and the lack of paired loads and stores.
