### PR TITLE
Cranelift: avoid debug-mode panics due to wrapping shifts in constant propagation

### LINKED ISSUE #5690: Cranelift panics on a shift with overflow
Given:

```
;;Output of `std::fmt::Debug`:

;; Fuzzgen test case

test interpret
test run
set opt_level=speed
set enable_simd=true
set enable_safepoints=true
set unwind_info=false
set preserve_frame_pointers=true
set machine_code_cfg_info=true
set enable_table_access_spectre_mitigation=false
target aarch64
function %u1() -> i64 sext, f64, i8, i8 sext, i8 sext system_v {
block0:
    v0 = f64const 0x1.8373638ff3738p-124
    v1 = iconst.i8 53
    v2 = iconst.i64 0x4445_00ff_ffff_ffff
    v3 = iconst.i8 0
    v4 = iconst.i16 0
    v5 = iconst.i32 0
    v6 = iconst.i64 0
    v7 = uextend.i128 v6  ; v6 = 0
    v8 = ishl v2, v2  ; v2 = 0x4445_00ff_ffff_ffff, v2 = 0x4445_00ff_ffff_ffff
    v9 = rotr v1, v1  ; v1 = 53, v1 = 53
    nop
    return v8, v0, v9, v9, v9  ; v0 = 0x1.8373638ff3738p-124
}

; Note: the results in the below test cases are simply a placeholder and probably will be wrong

; run: %u1() == [-9223372036854775808, 0x1.8373638ff3738p-124, -87, -87, -87]
```

this yields:

```
$ cargo run -q test ../out.log
thread 'worker #0' panicked at 'attempt to shift left with overflow', cranelift/codegen/src/opts.rs:89:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ERROR cranelift_filetests::concurrent > FAIL: panicked in worker #0: attempt to shift left with overflow
FAIL ../out.log: panicked in worker #0: attempt to shift left with overflow
1 tests
Error: 1 failure
```

cc @fitzgen as this was found trying to reduce the fuzz test failure from https://github.com/bytecodealliance/wasmtime/issues/5689

### PR DESCRIPTION
**Pull request by fitzgen**
Fixes #5690

### CODE REVIEW

File: cranelift/codegen/src/isle_prelude.rs [hunk 1]
```diff
@@ -82,7 +82,9 @@ macro_rules! isle_common_prelude_methods {
 
         #[inline]
         fn u64_shl(&mut self, x: u64, y: u64) -> u64 {
-            x << y
+            let y = 0x00000000ffffffff & y;
+            let y = u32::try_from(y).unwrap();
+            x.wrapping_shl(y)
```
Comment (cfallin) [inline cranelift/codegen/src/isle_prelude.rs:87]: It seems a little awkward here to do effectively two masks (down to 32 bits for `y`, then to log2(64) == 6 bits in `wrapping_shl`), one hidden and one explicit, and have an unwrap-path that may or may not be branch-folded away. It might be a little clearer to just write `x << (y & 63)`, i.e. do the wrapping ourselves? To my eyes at least, it's much less stuff to parse and understand.

**Review by cfallin — COMMENTED** [review]
LGTM with or without below, but my preference for simple and uncomplicated code is going to show through briefly here :-)

**Review by cfallin — APPROVED** [review]
(forgot the r+)

File: cranelift/codegen/src/isle_prelude.rs (hunk 1 above)
Comment (cfallin) [reply cranelift/codegen/src/isle_prelude.rs:87]: (It's also strange and unfortunate that `wrapping_shl` only takes a `u32` amount on a `u64` self; I wonder why...)

Comment (bjorn3) [reply cranelift/codegen/src/isle_prelude.rs:87]: I believe it takes a u32 on all integer types.

**Comment by jameysharp** [comment]
This was more complicated than it looked; Nick and I are working on it.

File: cranelift/codegen/src/isle_prelude.rs [hunk 2]
```diff
@@ -81,27 +81,43 @@ macro_rules! isle_common_prelude_methods {
...
         #[inline]
-        fn u64_shl(&mut self, x: u64, y: u64) -> u64 {
-            x << y
+        fn imm64_shl(&mut self, ty: Type, x: Imm64, y: Imm64) -> Imm64 {
+            // Mask off any excess shift bits.
+            let shift_mask = (ty.bits() - 1) as u64;
+            let y = (y.bits() as u64) & shift_mask;
+
+            // Mask the result to `ty` bits.
+            let ty_mask = u64::MAX >> u32::checked_sub(64, ty.bits()).unwrap_or(0);
```
Comment (cfallin) [inline cranelift/codegen/src/isle_prelude.rs:90]: We have a `ty_mask` function in the ISLE prelude that I think we could delegate to here instead?

File: cranelift/codegen/src/isle_prelude.rs [hunk 3]
```diff
@@ -81,27 +81,43 @@ macro_rules! isle_common_prelude_methods {
...
+            Imm64::new((x.bits() << y) & ty_mask)
         }
 
         #[inline]
         fn imm64_ushr(&mut self, ty: Type, x: Imm64, y: Imm64) -> Imm64 {
-            let shift = u32::checked_sub(64, ty.bits()).unwrap_or(0);
-            let mask = u64::MAX >> shift;
-            let x = (x.bits() as u64) & mask;
-            let y = (y.bits() as u64) & mask;
+            let ty_mask = u64::MAX >> u32::checked_sub(64, ty.bits()).unwrap_or(0);
```
Comment (cfallin) [inline cranelift/codegen/src/isle_prelude.rs:97]: Likewise here, `self.ty_mask(ty)`

**Review by cfallin — APPROVED** [review]
This looks right to me; one suggestion to reuse another prelude function, but LGTM either way.
