### PR TITLE
aarch64: Fix lowering amounts for shifts

### LINKED ISSUE #3064: Cranelift: ishl with i128 shift amount panics on AArch64
### Steps to Reproduce

Try to compile an ishl instruction with an i128 rhs using the AArch64 backend.

### Expected Results

It compiles

### Actual Results

```
thread 'rustc' panicked at 'Multi-register value not expected', /home/runner/.cargo/git/checkouts/wasmtime-41807828cb3a7a7e/c71ad94/cranelift/codegen/src/isa/aarch64/lower.rs:297:10
stack backtrace:
[...]
   2: core::option::expect_failed
             at /rustc/6d820866a27b1949e237be79b9c8c0145fe728b7/library/core/src/option.rs:1243:5
   3: cranelift_codegen::isa::aarch64::lower_inst::lower_insn_to_regs
   4: cranelift_codegen::machinst::lower::Lower<I>::lower
   5: cranelift_codegen::machinst::compile::compile
   6: <cranelift_codegen::isa::aarch64::AArch64Backend as cranelift_codegen::machinst::MachBackend>::compile_function
```

### Versions and Environment

Cranelift version or commit: c71ad9490e7f3e19bbcae7e28bbe50f8a0b4a5d8

Operating system: N/A

Architecture: AArch64

### Extra Info

AArch64 counterpart to https://github.com/bytecodealliance/wasmtime/issues/2727

### PR DESCRIPTION
**Pull request by afonso360**
This PR addresses two issues:
* A panic when shifting any non i128 type by i128 amounts (#3064)
* Wrong results when lowering shifts with small types (i8, i16)

In these types when shifting for amounts larger than the size of the
type, we would not get the wrapping behaviour that we see on i32 and i64.
This is because in these larger types, the wrapping behaviour is automatically
implemented by using the appropriate instruction, however we do not
have i8 and i16 specific instructions, so we have to manually wrap
the shift amount with an AND instruction.

This issue is also found on x86_64 and s390x, and a separate issue will
be filed for those.

Closes #3064

### CODE REVIEW

File: cranelift/codegen/src/isa/aarch64/lower_inst.rs [hunk 1]
```diff
@@ -798,13 +798,48 @@ pub(crate) fn lower_insn_to_regs<C: LowerCtx<I = Inst>>(
         }
 
         Opcode::Ishl | Opcode::Ushr | Opcode::Sshr => {
+            fn lower_shift_amt<C: LowerCtx<I = Inst>>(
```
Comment (akirilov-arm) [inline cranelift/codegen/src/isa/aarch64/lower_inst.rs:801]: Could you extract this helper function to `lower.rs`?

File: cranelift/codegen/src/isa/aarch64/lower_inst.rs [hunk 2]
```diff
@@ -798,13 +798,48 @@ pub(crate) fn lower_insn_to_regs<C: LowerCtx<I = Inst>>(
...
+                    // equivalent to i8 << 0
+                    //
+                    // On i32 and i64 types this matches what the aarch64 spec does, but on smaller
+                    // types (i16, i8) we need to do this manually, so we wrap the shift amount
+                    // with an AND instruction
+                    (I16 | I8, _) => {
+                        // We can ignore the top half of the shift amount register if the type is I128
+                        let amt_reg = put_input_in_regs(ctx, amt_input).regs()[0];
+                        let mask = (ty_bits(dst_ty) - 1) as u64;
+                        let tmp = ctx.alloc_tmp(I32).only_reg().unwrap();
```
Comment (akirilov-arm) [inline cranelift/codegen/src/isa/aarch64/lower_inst.rs:820]: Another potential optimization here is to use the shift destination register instead of a temporary one.

**Review by akirilov-arm — CHANGES_REQUESTED** [review]

**Review by akirilov-arm — APPROVED** [review]

**Comment by afonso360** [comment]
Thanks for reviewing @akirilov-arm!

**Comment by akirilov-arm** [comment]
No problem; once the pull request passes the tests, it should be ready for merging.

**Comment by afonso360** [comment]
These look like spurious failures to me. It looks like crates.io is not having a great time right now. My other PR is also failing due to the same reason.

Retrying CI later may work out better

**Comment by akirilov-arm** [comment]
Yes, that's true - all active PRs are failing right now with the same cause, including one of mine and another one.
