### PR TITLE
x64 small integer fixes

### LINKED ISSUE #2121: machinst x64: bint.i8 not implemented for b1 inputs
```
target x86_64

function u0:0(i8) -> i8 system_v {
                                block0(v0: i8):
                                    v1 -> v0
@0001                               v2 = icmp_imm.i8 eq v1, 0
@0001                               v3 = bint.i8 v2
@0003                               return v3
}
```

```
thread 'rustc' panicked at 'internal error: entered unreachable code: unexpected extension kind from types::B1 to types::I8', /home/bjorn/.cargo/git/checkouts/wasmtime-41807828cb3a7a7e/8cfff26/cranelift/codegen/src/isa/x64/lower.rs:813:22
```

### PR DESCRIPTION
**Pull request by bjorn3**
I am not sure how to implement `sshr` and `ushr` for small integers.

Fixes #2121

### CODE REVIEW

**Comment by bnjbvr** [comment]
Great work! I'll take a look.

File: cranelift/codegen/src/isa/aarch64/lower_inst.rs [hunk 1]
```diff
@@ -49,6 +49,15 @@ pub(crate) fn lower_insn_to_regs<C: LowerCtx<I = Inst>>(
     match op {
         Opcode::Iconst | Opcode::Bconst | Opcode::Null => {
             let value = ctx.get_constant(insn).unwrap();
+            // Sign extend constant if necessary
+            let value = match ty.unwrap() {
+                I8 => (((value as i64) << 8) >> 8) as u64,
+                I16 => (((value as i64) << 16) >> 16) as u64,
+                I32 => (((value as i64) << 32) >> 32) as u64,
```
Comment (MaxGraey) [inline cranelift/codegen/src/isa/aarch64/lower_inst.rs:56]: Is it sign extention from small ints to `i64`, right? Perhaps I'm missing something, that it should look like this I guess:
```suggestion
                I8 => (((value as i64) << 56) >> 56) as u64,
                I16 => (((value as i64) << 48) >> 48) as u64,
                I32 => (((value as i64) << 32) >> 32) as u64,
```

Comment (bjorn3) [reply cranelift/codegen/src/isa/aarch64/lower_inst.rs:56]: Indeed. Good catch! Thanks!

File: cranelift/codegen/src/isa/x64/inst/mod.rs [hunk 2]
```diff
@@ -100,6 +100,9 @@ pub enum Inst {
         loc: SourceLoc,
     },
 
+    /// Do a sign-extend based on the sign of the value in al into ah: (cbw)
+    SignExtendAlAh,
```
Comment (bnjbvr) [inline cranelift/codegen/src/isa/x64/inst/mod.rs:104]: We should reuse the `SignExtendRaxRdx` instruction, because this new instruction you added and the former have the same semantics: sign-extend the "data" (originally on x86, `rax` is the "data" (Accumulator, hence A) register up to 32 bits, and when more is required, the `rdx` contains the rest of the Data (hence D in name)). Maybe rename `SignExtendRaxRdx` to `SignExtendData`, and make the size an `Option` to indicate al->ah? (or use 0 for al->ah sign-extension?) Or we could have a `SignExtendOpSize` enum that contains all the valid sizes for this instruction?

File: cranelift/codegen/src/isa/x64/lower.rs [hunk 3]
```diff
@@ -422,9 +422,18 @@ fn lower_insn_to_regs<C: LowerCtx<I = Inst>>(
...
+            let lhs = match dst_ty {
+                types::I8 | types::I16 => match op {
+                    Opcode::Ishl => input_to_reg(ctx, inputs[0]),
+                    Opcode::Ushr => extend_input_to_reg(ctx, inputs[0], ExtSpec::ZeroExtendTo32),
+                    Opcode::Sshr => extend_input_to_reg(ctx, inputs[0], ExtSpec::SignExtendTo32),
+                    Opcode::Rotl | Opcode::Rotr => unimplemented!("rotl/rotr.i8/i16"),
+                    _ => unreachable!(),
+                },
+                types::I32 | types::I64 => input_to_reg(ctx, inputs[0]),
+                _ => unreachable!("{}", dst_ty),
```
Comment (bnjbvr) [inline cranelift/codegen/src/isa/x64/lower.rs:443]: nit: can you please add a bit more details in the unreachable message: `"unhandled output type for shift/rotates: {}"`?

**Review by bnjbvr — APPROVED** [review]
lgtm, thanks (and sorry about the long review time)! Handling smaller operand sizes on machine instructions may likely create partial register stalls, so it would be interesting to experiment with doing what the old backend did (do a signed or zero extension up to 32 bits, and apply the operator, and reduce if needed).
Mostly cosmetic comments below, I'll make sure to quickly re-review and merge once this is addressed!

**Comment by bjorn3** [comment]
Rebased and fixed review comments.

**Comment by bjorn3** [comment]
Thanks!
