### PR TITLE
x64: implement vselect with variable blend instructions

### LINKED ISSUE #2754: x64: vselect not implemented
I was playing around with wasm simd support for Rust but ended up running into a panic in the old backend:

```wasm
(module
  (func (result v128)
    v128.const i64x2 0 0
    v128.const i64x2 0 0
    v128.const i64x2 -1 -1
    v128.bitselect
  )
)
```

when run with:

```
$ cargo run --features experimental_x64 -- run --enable-simd foo.wat
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/wasmtime run --enable-simd foo.wat`
thread 'main' panicked at 'not implemented: unimplemented lowering for opcode Vselect', cranelift/codegen/src/isa/x64/lower.rs:5745:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by abrown**
This change implements `vselect` using SSE4.1's `BLENDVPS`, `BLENDVPD`, and `PBLENDVB` to fix #2754. `vselect` is a lane-selecting instruction that is used by [simple_preopt.rs](https://github.com/bytecodealliance/wasmtime/blob/fa1faf5d224b9640eb33eed97e6a890da23afa33/cranelift/codegen/src/simple_preopt.rs#L947-L999) to lower `bitselect` to a single x86 instruction when the condition mask is known to be boolean (all 1s or 0s, e.g., from a conversion). This is better than `bitselect` in general, which lowers to 4-5 instructions. The old backend had the `vselect` lowering; this simply introduces it to the new backend.

### CODE REVIEW

File: cranelift/codegen/src/isa/x64/lower.rs [hunk 1]
```diff
@@ -1979,7 +1979,44 @@ fn lower_insn_to_regs<C: LowerCtx<I = Inst>>(
...
+                // all 0s. This lowering relies on that fact to use x86's
+                // variable blend instructions, which look at the _high_bit_ of
+                // the condition mask. All the bits of vector booleans will
+                // match (all 1s or all 0s), so we can just use the high bit.
+                assert!(condition_ty.lane_type().is_bool());
+
+                // Variable blend instructions expect the condition mask to be
+                // in XMM0.
+                let xmm0 = Writable::from_reg(regs::xmm0());
+                ctx.emit(Inst::gen_move(xmm0, condition, ty));
```
Comment (alexcrichton) [inline cranelift/codegen/src/isa/x64/lower.rs:2006]: How does regalloc know that xmm0 is live until the `xmm_rm_r` instruction below?

File: cranelift/codegen/src/isa/x64/lower.rs [hunk 2]
```diff
@@ -1979,7 +1979,44 @@ fn lower_insn_to_regs<C: LowerCtx<I = Inst>>(
...
+
+                // Match up the source and destination registers for regalloc.
+                ctx.emit(Inst::gen_move(dst, if_false, ty));
+
+                let opcode = match condition_ty {
+                    types::B64X2 => SseOpcode::Blendvpd,
```
Comment (alexcrichton) [inline cranelift/codegen/src/isa/x64/lower.rs:2012]: It looks like this requires SSE 4.1, but how does the code generator know if that's enabled or not? Should this assert that SSE 4.1 is enabled?

File: cranelift/codegen/src/isa/x64/lower.rs [hunk 3]
```diff
@@ -1979,7 +1979,44 @@ fn lower_insn_to_regs<C: LowerCtx<I = Inst>>(
...
+                    types::B32X4 => SseOpcode::Blendvps,
+                    types::B16X8 | types::B8X16 => SseOpcode::Pblendvb,
```
Comment (alexcrichton) [inline cranelift/codegen/src/isa/x64/lower.rs:2014]: I was curious after seeing two of these get mapped to the same instruction, while the above two types have different instructions. Reading the description, couldn't `pblendvb` be used for all 4 types instead of just these two smaller ones?

**Review by alexcrichton — COMMENTED** [review]
I've not really reviewed many cranelift backend PRs before, so I'm pretty unfamiliar with it. That being said I'm always curious to learn, and everything looks reasonable enough here, but I left some comments inline.

Could a test be added for the wasm behavior as well?

File: cranelift/codegen/src/isa/x64/lower.rs (hunk 1 above)
Comment (abrown) [reply cranelift/codegen/src/isa/x64/lower.rs:2006]: @cfallin can correct me if I get this wrong but every generated instruction tells regalloc how it is using each register using the [RegUsageMapper](https://docs.rs/regalloc/0.0.31/regalloc/trait.RegUsageMapper.html) trait. Well, maybe it is the [RegUsageCollector](https://docs.rs/regalloc/0.0.31/regalloc/struct.RegUsageCollector.html). In any case, regalloc should know that a move to that virtual register (hard-coded to XMM0) is a `def` and that that register should be left alone until it is `use`d.

File: cranelift/codegen/src/isa/x64/lower.rs (hunk 2 above)
Comment (abrown) [reply cranelift/codegen/src/isa/x64/lower.rs:2012]: We haven't been feature-checking SSE 4.1 instructions in the lowerings since this is a Wasm SIMD baseline (though IIRC Julian would have liked us to have several tiers of lowerings, e.g., SSE2 -> SSE 4.2 -> ...). Optional lowerings are feature-checked, e.g. the AVX512 instructions I used. But all of that applies only to the lowering phase. There's [another check](https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/codegen/src/isa/x64/inst/emit.rs#L118-L143) right before the instructions are actually emitted that will panic if the target does not support this instruction.

File: cranelift/codegen/src/isa/x64/lower.rs (hunk 1 above)
Comment (cfallin) [reply cranelift/codegen/src/isa/x64/lower.rs:2006]: Indeed, the regalloc.rs semantics are such that we compute live-ranges for both real regs and virtual regs; and a real reg is reserved for the extent of its virtual ranges. As long as we properly have xmm0 has a use below the move then everything works as expected!

Comment (alexcrichton) [reply cranelift/codegen/src/isa/x64/lower.rs:2006]: Yeah it makes sense to me that it's use/def based and this is a def of xmm0, but I wasn't able to find the use of xmm0 (I'm probably missing something though?) [This looks like the relevant block](https://github.com/bytecodealliance/wasmtime/blob/e676589b0c6e8228c421e18249d4635eb6c4bbe4/cranelift/codegen/src/isa/x64/inst/mod.rs#L1930-L1938) but it doesn't seem have anything xmm0-related there, though?

(I'd sort of expect a `match` on the opcode to add the use of xmm0 in some cases, like the ones used below)

File: cranelift/codegen/src/isa/x64/lower.rs (hunk 2 above)
Comment (alexcrichton) [reply cranelift/codegen/src/isa/x64/lower.rs:2012]: Ah ok, so that just means that this'll panic later on if sse4.1 is disabled, and the fix would be to update the lowering here? That sounds reasonable to me!

File: cranelift/codegen/src/isa/x64/lower.rs (hunk 3 above)
Comment (abrown) [reply cranelift/codegen/src/isa/x64/lower.rs:2014]: This is purely a preference thing like I've done previously on moves, e.g.: it adds a negligible overhead to compilation but it matches the original intent of the instruction more closely, which I feel helps during debugging and sometimes can help with latency/throughput. In this case, the latency/throughput differences are very minor (see IA Optimization Manual, appendix D; depending on the arch family, 1 in some cases and 2 in others).

File: cranelift/codegen/src/isa/x64/lower.rs (hunk 1 above)
Comment (abrown) [reply cranelift/codegen/src/isa/x64/lower.rs:2006]: Yup, actually you're right. In talking more to @cfallin I actually came to the same conclusion. Let me fix that.

Comment (alexcrichton) [reply cranelift/codegen/src/isa/x64/lower.rs:2056]: Out of curiosity, what's the failure mode for a situation like this? The register allocator sees a "def" of xmm0 but it never sees a use. Does that mean that the live range is considered infinite? Or is the live range immediately "dead" after the def?

(this seems like a worrying thing to me and easy to overlook, so curious if we could bolster up checks one way or another to prevent this from happening again)

File: cranelift/codegen/src/isa/x64/lower.rs (hunk 3 above)
Comment (alexcrichton) [reply cranelift/codegen/src/isa/x64/lower.rs:2064]: Ah ok makes sense! Presumably there's no dedicated instruction for 16-bit types?

Could you leave a comment for how `pblendvb` would be correct for all of these but more specialized versions are used for slight optimizations?

**Review by alexcrichton — APPROVED** [review]

File: cranelift/codegen/src/isa/x64/lower.rs (hunk 1 above)
Comment (abrown) [reply cranelift/codegen/src/isa/x64/lower.rs:2056]: @cfallin? 😁

File: cranelift/codegen/src/isa/x64/lower.rs (hunk 3 above)
Comment (abrown) [reply cranelift/codegen/src/isa/x64/lower.rs:2064]: Yup, no 16-bit, at least in SSE-land (`VPBLENDM*` exists up in AVX512). Yeah, I'll add the comment.

**Comment by abrown** [comment]
@alexcrichton, one last comment I forgot to address before this gets merged:

> Could a test be added for the wasm behavior as well?

Most of the Wasm side of things is tested using the Wasm SIMD spec tests. I think this type of thing is already covered somewhere in `simd_bitwise.wast` and/or `simd_boolean.wast`.

File: cranelift/codegen/src/isa/x64/lower.rs (hunk 1 above)
Comment (cfallin) [reply cranelift/codegen/src/isa/x64/lower.rs:2056]: Yeah, the failure mode isn't great: the real-reg liverange ends at the last mention (the def) and so the register is liable to be reused for something else, clobbering the value.

Always looking for ways to foolproof this; it's a bit tricky as the question is: what is the ground-truth we can check against? If we forget to mention a register-use in the metadata we provide to the allocator, the only other way of seeing that would be to disassemble the resulting machine code independently and check its register-mentions. We could certainly do that, perhaps as another oracle during fuzzing; but it's a big project (correlating the disassembly to the VCode especially with multiple-instruction lowerings would take some care).

Comment (alexcrichton) [reply cranelift/codegen/src/isa/x64/lower.rs:2056]: Oh nah I wouldn't want to go so all-out just yet. I would imagine something much more simple which is that if something is defined and never used, it's considered either live forever or invalid, causing a panic. In the "live forever" case we'd in theory one day ask why our code was so slow and fix this by limiting the live range, and in the latter case we'd catch the panic real fast and fix it.

I'm not sure if it's common, though, for values to be defined and never used. If that happens pretty normally then there's probably not much we can do about this other than being vigilant for now.

Comment (cfallin) [reply cranelift/codegen/src/isa/x64/lower.rs:2056]: Interesting thoughts in any case, thanks for the ideas here!

Keeping a real-reg liverange open forever would ensure safety here but could potentially have forward-progress implications: it's essentially a "leak" of one register, and if we reserve too many real regs in this way, then we could hit a point where we don't have enough registers to satisfy constraints and finish allocation. That's less bad than clobbering but still bad, and would be somewhat hard to debug.

In theory, dead defs *shouldn't* happen at the CLIF level, because we lower based on demand, though it's possible at the VCode level depending on the lowering pattern. There's also the issue that we use dead defs as a way to encode clobbers (at calls, for example), so we'd need a different category for those, but it could be doable.

We can think more about this -- I'll add the disallow-dead-defs idea to my running list of "things to look at next time I focus on fuzzing infra" :-)
