### PR TITLE
Cranelift: consider heap's guard pages when legalizing `heap_addr`

### LINKED ISSUE #5328: Compiling a 8 MB WASM file using Wasmtime dev build takes 20x as long as with Wasmtime 3.0.0
Hi!

I noticed that compiling an 8 MiB WASM module (produced by the experimental [WASI SDK for .NET](https://github.com/SteveSandersonMS/dotnet-wasi-sdk/)) when using Wasmtime from commit 28cf995fd3f9926a95036758c78390f54a0289ae (current **dev** release) takes much longer than when using Wasmtime 3.0.0 (tested on Windows 10 x64, Build 19044).

To reproduce:
- Download the WASM file as .Zip file here (note: rename the `.mov` file to `.zip` ; I renamed it to be able to upload it here): https://user-images.githubusercontent.com/13289184/203989968-4639d6d5-15c9-4e57-bf01-c2eccd756642.mov
- Download and extract `wasmtime-v3.0.0-x86_64-windows.zip`
- Run `wasmtime compile dotnet-codabix-wasm-build.wasm`
- Then try the same with the current **dev** release from commit 28cf995fd3f9926a95036758c78390f54a0289ae.

On my system, with Wasmtime **3.0.0** this takes about **0.7** seconds, but with the build from commit 28cf995fd3f9926a95036758c78390f54a0289ae it takes about **13.8** seconds, which is about 20 times as long.
Is this expected?

Bisecting shows that this starts to appear with commit fc62d4ad65892837a1e1af5a9d67c8b0d4310efe (#5231) - with a release build from this commit, I get the 13.8s time, but with the previous commit 33a192556e5f11ee95cffc7a90e74b78abc340c8, I get a time of about 0.7s.

### Versions and Environment

Wasmtime version or commit: Wasmtime v3.0.0 vs 28cf995fd3f9926a95036758c78390f54a0289ae
Operating system: Windows 10 Pro x64, Build 19044
Architecture: x64 (x86-64)

Thank you!

### PR DESCRIPTION
**Pull request by fitzgen**
Fixes #5328

FYI, I opted not to mess with or dedupe the similar logic in `cranelift-wasm` since that stuff is going to go away soon-ish when we remove `heap_addr` and collect all this logic into `heap_{load,store}`. Excited to get to a point where this logic isn't spread across crates and straddling interfaces.

### CODE REVIEW

**Comment by jameysharp** [comment]
FWIW, I looked this over and I think it makes sense, but I'd definitely prefer to have somebody else's review on it.

File: cranelift/codegen/src/legalizer/heap.rs [hunk 1]
```diff
@@ -172,23 +179,45 @@ fn static_addr(
...
+    // region, neither of which require emitting an explicit bounds check.
+    assert!(
+        bound.checked_add(guard_size).is_some(),
+        "heap's configuration doesn't fit in a 64-bit memory space"
+    );
     let mut spectre_oob_comparison = None;
     let index = cast_index_to_pointer_ty(index, index_ty, addr_ty, &mut pos);
-    if index_ty != ir::types::I32 || limit < 0xffff_ffff {
+    if index_ty == ir::types::I32
+        && bound + guard_size - offset_plus_size(offset, access_size) >= 0xffff_ffff
```
Comment (cfallin) [inline cranelift/codegen/src/legalizer/heap.rs:214]: Is it worth a comment here on the `>=` and the `0xffff_ffff` (i.e., the minus-one aspect)?

In particular I think it's right because
- We trap if `index > bound + guard_size - offset - access_size`
- If the RHS of that is *equal* to `0xffff_ffff`, index could be *equal* to it but not *greater* than it; so we cannot achieve `index > RHS`

I think it's a little unclear because above in the comment we have `index < 4GiB <= RHS` but here we are really relying on `index <= (4GiB - 1) <= RHS`, which is also valid (`<=` is also transitive). I guess aligning the two makes things clearer, at least for me...

**Review by cfallin — APPROVED** [review]
Looks correct to me. One note below on possibly expanding the explanation a bit.

**Review by alexcrichton — APPROVED** [review]
It looks like the prior PR accidentally enabled bounds checks by default in Wasmtime, so I'm sort of surprised we didn't catch that until now. Does sightglass show regressions here or improvements after this commit? If so it might be good to use sightglass on future changes to `heap_{addr,store,load}` to double-check the intended effect.

File: cranelift/codegen/src/legalizer/heap.rs (hunk 1 above)
Comment (fitzgen) [reply cranelift/codegen/src/legalizer/heap.rs:214]: Updated the comment above this to align more directly with the implementation.

**Comment by fitzgen** [comment]
> It looks like the prior PR accidentally enabled bounds checks by default in Wasmtime, so I'm sort of surprised we didn't catch that until now. Does sightglass show regressions here or improvements after this commit? If so it might be good to use sightglass on future changes to `heap_{addr,store,load}` to double-check the intended effect.

Yeah would be great if we had nightly sightglass benchmarks set up. I set up some smoke tests for `heap_addr` legalization with vs without sufficient guard pages to avoid bounds checks (should tide us over until `heap_addr` is gone).

Sightglass results for this PR:


```
execution :: instructions-retired :: benchmarks/spidermonkey/benchmark.wasm

  Δ = 3362887399.64 ± 42143.94 (confidence = 99%)

  with-guard-pages.so is 2.05x to 2.05x faster than main.so!

  [6566493438 6566656053.70 6567012773] main.so
  [3203651702 3203768654.06 3204149983] with-guard-pages.so

execution :: instructions-retired :: benchmarks/bz2/benchmark.wasm

  Δ = 253455489.92 ± 1.49 (confidence = 99%)

  with-guard-pages.so is 1.79x to 1.79x faster than main.so!

  [573123166 573123173.64 573123183] main.so
  [319667678 319667683.72 319667699] with-guard-pages.so

execution :: instructions-retired :: benchmarks/pulldown-cmark/benchmark.wasm

  Δ = 16418573.09 ± 99.14 (confidence = 99%)

  with-guard-pages.so is 1.62x to 1.62x faster than main.so!

  [42813022 42813207.84 42813926] main.so
  [26394395 26394634.75 26395352] with-guard-pages.so

compilation :: instructions-retired :: benchmarks/bz2/benchmark.wasm

  Δ = 321257.88 ± 54303.80 (confidence = 99%)

  with-guard-pages.so is 1.11x to 1.15x faster than main.so!

  [2784403 2856173.33 3298299] main.so
  [2460682 2534915.45 3047605] with-guard-pages.so

compilation :: instructions-retired :: benchmarks/spidermonkey/benchmark.wasm

  Δ = 25520928.63 ± 108236.81 (confidence = 99%)

  with-guard-pages.so is 1.12x to 1.12x faster than main.so!

  [232258160 232762746.46 233555099] main.so
  [206468796 207241817.83 207933331] with-guard-pages.so

compilation :: instructions-retired :: benchmarks/pulldown-cmark/benchmark.wasm

  Δ = 676224.25 ± 51124.52 (confidence = 99%)

  with-guard-pages.so is 1.07x to 1.08x faster than main.so!

  [9483066 9609230.75 10037142] main.so
  [8828280 8933006.50 9376518] with-guard-pages.so
```

**Comment by alexcrichton** [comment]
Nah I don't think it's worthwhile to add more than what's already here given that this is all intended to be short-lived anyway. It's good though that sightglass clearly detects this either way!
