### PR TITLE
gc_ops: Mutator update

### LINKED ISSUE #12665: Panic during mutation in gc_ops fuzzer
This is a public version of https://issues.oss-fuzz.com/issues/487437719 which is an oss-fuzz found bug. Unfortunately there's no reproduction test case for this, however. All we currently have is a Wasmtime revision (755979dd81eb79ff746fb4e63d4570513216e731) and a stack trace:

```
thread '<unnamed>' (4629) panicked at /src/wasmtime/crates/fuzzing/src/generators/gc_ops/mutator.rs:332:22:
	rec_groups not empty
	note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
	AddressSanitizer:DEADLYSIGNAL
	=================================================================
	==4629==ERROR: AddressSanitizer: ABRT on unknown address 0x053900001215 (pc 0x7f3f52a9000b bp 0x7ffe0c2cc450 sp 0x7ffe0c2cc200 T0)
	SCARINESS: 10 (signal)
	    #0 0x7f3f52a9000b in raise /build/glibc-B3wQXB/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:51:1
	    #1 0x7f3f52a6f858 in abort /build/glibc-B3wQXB/glibc-2.31/stdlib/abort.c:79:7
	    #2 0x5643af5d13c9 in std::sys::pal::unix::abort_internal /rustc/e96bb7e44fbcc23c1e6009e8d0ee8ab208668fb4/library/std/src/sys/pal/unix/mod.rs:305:14
	    #3 0x5643af5d1178 in std::process::abort /rustc/e96bb7e44fbcc23c1e6009e8d0ee8ab208668fb4/library/std/src/process.rs:2533:5
	    #4 0x5643af5cba74 in libfuzzer_sys::initialize::{closure#0} /rust/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/src/lib.rs:94:9
	    #5 0x5643b3d14571 in <alloc::boxed::Box<dyn for<'a, 'b> core::ops::function::Fn<(&'a std::panic::PanicHookInfo<'b>,), Output = ()> + core::marker::Send + core::marker::Sync> as core::ops::function::Fn<(&std::panic::PanicHookInfo,)>>::call /rustc/e96bb7e44fbcc23c1e6009e8d0ee8ab208668fb4/library/alloc/src/boxed.rs:2220:9
	    #6 0x5643b3d14571 in std::panicking::panic_with_hook /rustc/e96bb7e44fbcc23c1e6009e8d0ee8ab208668fb4/library/std/src/panicking.rs:833:13
	    #7 0x5643b3d01b87 in std::panicking::panic_handler::{closure#0} /rustc/e96bb7e44fbcc23c1e6009e8d0ee8ab208668fb4/library/std/src/panicking.rs:698:13
	    #8 0x5643b3cf6e98 in std::sys::backtrace::__rust_end_short_backtrace::<std::panicking::panic_handler::{closure#0}, !> /rustc/e96bb7e44fbcc23c1e6009e8d0ee8ab208668fb4/library/std/src/sys/backtrace.rs:182:18
	    #9 0x5643b3d029ec in __rustc::rust_begin_unwind /rustc/e96bb7e44fbcc23c1e6009e8d0ee8ab208668fb4/library/std/src/panicking.rs:689:5
	    #10 0x5643af5d23ab in core::panicking::panic_fmt /rustc/e96bb7e44fbcc23c1e6009e8d0ee8ab208668fb4/library/core/src/panicking.rs:80:14
	    #11 0x5643af5d2073 in core::panicking::panic_display::<&str> /rustc/e96bb7e44fbcc23c1e6009e8d0ee8ab208668fb4/library/core/src/panicking.rs:259:5
	    #12 0x5643af5d2073 in core::option::expect_failed /rustc/e96bb7e44fbcc23c1e6009e8d0ee8ab208668fb4/library/core/src/option.rs:2202:5
	    #13 0x5643af7b953e in <core::option::Option<wasmtime_fuzzing::generators::gc_ops::types::RecGroupId>>::expect /rustc/e96bb7e44fbcc23c1e6009e8d0ee8ab208668fb4/library/core/src/option.rs:971:21
	    #14 0x5643af7b953e in <wasmtime_fuzzing::generators::gc_ops::mutator::GcOpsMutator>::split_rec_group::{closure#0} [wasmtime/crates/fuzzing/src/generators/gc_ops/mutator.rs:332](https://github.com/bytecodealliance/wasmtime/blob/755979dd81eb79ff746fb4e63d4570513216e731/crates/fuzzing/src/generators/gc_ops/mutator.rs#L332):22
	    #15 0x5643af7b953e in <mutatis::Candidates>::mutation::<<wasmtime_fuzzing::generators::gc_ops::mutator::GcOpsMutator>::split_rec_group::{closure#0}> /rust/registry/src/index.crates.io-1949cf8c6b5b557f/mutatis-0.3.2/src/lib.rs:459:21
	    #16 0x5643af7b953e in <wasmtime_fuzzing::generators::gc_ops::mutator::GcOpsMutator>::split_rec_group [wasmtime/crates/fuzzing/src/generators/gc_ops/mutator.rs:322](https://github.com/bytecodealliance/wasmtime/blob/755979dd81eb79ff746fb4e63d4570513216e731/crates/fuzzing/src/generators/gc_ops/mutator.rs#L322):11
	    #17 0x5643af813e6d in <wasmtime_fuzzing::generators::gc_ops::mutator::GcOpsMutator as mutatis::Mutate<wasmtime_fuzzing::generators::gc_ops::ops::GcOps>>::mutate [wasmtime/crates/fuzzing/src/generators/gc_ops/mutator.rs:393](https://github.com/bytecodealliance/wasmtime/blob/755979dd81eb79ff746fb4e63d4570513216e731/crates/fuzzing/src/generators/gc_ops/mutator.rs#L393):14
	    #18 0x5643af6ad32d in <mutatis::mutators::core_impls::Tuple2<mutatis::mutators::core_impls::U64, wasmtime_fuzzing::generators::gc_ops::mutator::GcOpsMutator> as mutatis::Mutate<(u64, wasmtime_fuzzing::generators::gc_ops::ops::GcOps)>>::mutate /rust/registry/src/index.crates.io-1949cf8c6b5b557f/mutatis-0.3.2/src/mutators/core_impls.rs:534:33
	    #19 0x5643af6ad32d in <mutatis::Context>::mutate_with::<(u64, wasmtime_fuzzing::generators::gc_ops::ops::GcOps), mutatis::mutators::core_impls::Tuple2<mutatis::mutators::core_impls::U64, wasmtime_fuzzing::generators::gc_ops::mutator::GcOpsMutator>>::{closure#0} /rust/registry/src/index.crates.io-1949cf8c6b5b557f/mutatis-0.3.2/src/lib.rs:322:66
	    #20 0x5643af6914f5 in <mutatis::Context>::choose_and_apply_mutation::<(u64, wasmtime_fuzzing::generators::gc_ops::ops::GcOps), <mutatis::Context>::mutate_with<(u64, wasmtime_fuzzing::generators::gc_ops::ops::GcOps), mutatis::mutators::core_impls::Tuple2<mutatis::mutators::core_impls::U64, wasmtime_fuzzing::generators::gc_ops::mutator::GcOpsMutator>>::{closure#0}> /rust/registry/src/index.crates.io-1949cf8c6b5b557f/mutatis-0.3.2/src/lib.rs:361:15
	    #21 0x5643af6914f5 in <mutatis::Context>::mutate_with::<(u64, wasmtime_fuzzing::generators::gc_ops::ops::GcOps), mutatis::mutators::core_impls::Tuple2<mutatis::mutators::core_impls::U64, wasmtime_fuzzing::generators::gc_ops::mutator::GcOpsMutator>> /rust/registry/src/index.crates.io-1949cf8c6b5b557f/mutatis-0.3.2/src/lib.rs:322:14
	    #22 0x5643af6914f5 in <mutatis::Context>::mutate::<(u64, wasmtime_fuzzing::generators::gc_ops::ops::GcOps)> /rust/registry/src/index.crates.io-1949cf8c6b5b557f/mutatis-0.3.2/src/lib.rs:313:14
	    #23 0x5643af6914f5 in <mutatis::Session>::mutate::<(u64, wasmtime_fuzzing::generators::gc_ops::ops::GcOps)> /rust/registry/src/index.crates.io-1949cf8c6b5b557f/mutatis-0.3.2/src/lib.rs:145:22
	    #24 0x5643af6914f5 in gc_ops::rust_fuzzer_custom_mutator::custom_mutator [wasmtime/fuzz/fuzz_targets/gc_ops.rs:41](https://github.com/bytecodealliance/wasmtime/blob/755979dd81eb79ff746fb4e63d4570513216e731/fuzz/fuzz_targets/gc_ops.rs#L41):16
	    #25 0x5643af6914f5 in LLVMFuzzerCustomMutator /rust/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/src/lib.rs:558:28
	    #26 0x5643b3cbdf68 in MutateImpl /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMutate.cpp:550:22
	    #27 0x5643b3cbdf68 in fuzzer::MutationDispatcher::Mutate(unsigned char*, unsigned long, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMutate.cpp:532:10
	    #28 0x5643b3ca9c52 in fuzzer::Fuzzer::MutateAndTestOne() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:757:20
	    #29 0x5643b3caa865 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile>>&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:910:5
	    #30 0x5643b3c996e5 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:917:6
	    #31 0x5643b3cc4252 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
	    #32 0x7f3f52a71082 in __libc_start_main /build/glibc-B3wQXB/glibc-2.31/csu/libc-start.c:308:16
	    #33 0x5643af5d3d3d in _start
```

Given that this is during a mutation of a test case I think that explains why there's no test case here.

cc @fitzgen and @khagankhan, would the backtrace/panic message be enough to help debug this even without a test case?

### PR DESCRIPTION
**Pull request by khagankhan**
### Types representation
Changed rec group membership from a field on `SubType` to sets owned by
each rec group (`BTreeMap<RecGroupId, BTreeSet<TypeId>>`). Mutations are
now local set operations — move, split, merge, etc. no longer require
scanning all `type_defs` to find group members. I assume this will make
the mutations easier for subtypes.

### Mutator structure
- Extracted `TypesMutator` for all type/rec-group mutations, operating
  on `Types` directly.
- Enabled the `alloc` feature on `mutatis` and delegate `Vec<GcOp>`
  add/remove/mutate to the library's built-in vec mutator via `mutators::vec()`.

### Misc
- Use `u32::try_from().expect()` instead of `as usize` casts for limit
  checks.
- Also should fix #12665 

cc @fitzgen @eeide

### CODE REVIEW

File: crates/fuzzing/src/generators/gc_ops/mutator.rs [hunk 1]
```diff
@@ -134,278 +89,278 @@ impl GcOpsMutator {
...
+    fn mutate_with_limits(
+        &mut self,
+        c: &mut Candidates<'_>,
+        types: &mut Types,
+        limits: &GcOpsLimits,
+    ) -> mutatis::Result<()> {
+        // Fuzzing + raw byte mutation can decode/produce malformed `Types`.
+        // Repair invariants early so the rest of this mutator can rely on
+        // `unwrap()`/`expect()` being sound.
+        types.fixup(limits);
```
Comment (khagankhan) [inline crates/fuzzing/src/generators/gc_ops/mutator.rs]: I was getting panics on `unwraps/expects` that made no sense. The precondition seemed OK but the data itself was inconsistent. For example, the `rec` group's member set would claim a `TypeId` that did not exist in `type_defs` or vice versa.

I believe the reason is: `libFuzzer` sometimes skips our custom mutator and
flips random bits in the serialized bytes directly. This can produce
deserialized state where the two maps disagree. Then when libFuzzer picks
those corrupted bytes for a custom mutation round, our mutator sees the
inconsistent state and the expects/unwraps fire.

Adding `types.fixup()` seems to fix it after running ~an hour

**Comment by khagankhan** [comment]
@fitzgen I think #12577 should be made on top of this PR. After a potential merge I will close that one and make a new one on top of this with feedbacks being addressed. I guess it would be easier?

File: crates/fuzzing/src/generators/gc_ops/mutator.rs (hunk 1 above)
Comment (fitzgen) [reply crates/fuzzing/src/generators/gc_ops/mutator.rs]: Your diagnosis is correct, but we shouldn't just call `fixup` willy-nilly. We should instead commit to a discipline of either:

1. Make mutations robust to receiving "arbitrary" ASTs rather than relying on only the shape of ASTs that can be produced by our mutations (since we know that our fuzzing setup will just randomly mutate the serialized bytes at times).
2. Call `fixup` on the whole AST at the start of mutation, rather than doing spot-fixes, so we can rely on the AST being "valid" in all of our mutations across the whole code base.

We have thus far been doing (1), this change moves us towards (2) but in an ad-hoc way. What is nice about (1) is that performance will probably be better, since we won't be doing things like computing SCCs and all that to break cycles, or at minimum a whole pass over the AST. The downside is that we have to write the mutations somewhat defensively, and handle bad type id references and things like that. The pros/cons of (2) are the opposite.

Have you investigated making the mutations more defensive? I would prefer not to abandon performance too eagerly.

File: crates/fuzzing/src/generators/gc_ops/types.rs [hunk 2]
```diff
@@ -3,128 +3,177 @@
...
 
-        // Drop any types whose rec-group has been trimmed out.
-        self.type_defs
-            .retain(|_, ty| self.rec_groups.contains(&ty.rec_group));
+        // 2. Drop orphan type_defs (types not in any rec group's member set).
+        let mut all_members = std::collections::BTreeSet::new();
+        for members in self.rec_groups.values() {
+            all_members.extend(members.iter().copied());
+        }
+        self.type_defs.retain(|tid, _| all_members.contains(tid));
```
Comment (fitzgen) [inline crates/fuzzing/src/generators/gc_ops/types.rs]: Also I think we probably want to just create a new rec group for these orphan types here. And this should probably happen after trimming excess types. And then later on when we trim excess rec groups, we need to also trim their types as well.

File: crates/fuzzing/src/generators/gc_ops/types.rs [hunk 3]
```diff
@@ -3,128 +3,219 @@
...
+        }
+
+        debug_assert!(self.is_well_formed(limits));
+    }
+
+    /// Check if the types are well-formed and within configured limits, i.e.
+    /// rec/type counts are within limits,
+    /// every type belongs to exactly one rec group,
+    /// and every rec group member must exist in type_defs.
+    fn is_well_formed(&self, limits: &GcOpsLimits) -> bool {
```
Comment (khagankhan) [inline crates/fuzzing/src/generators/gc_ops/types.rs:183]: a small helper for assertion in `fixup`

File: crates/fuzzing/src/generators/gc_ops/types.rs [hunk 4]
```diff
@@ -3,128 +3,219 @@
...
+    /// Find which rec group a type belongs to, if any.
+    pub fn rec_group_of(&self, id: TypeId) -> Option<RecGroupId> {
+        self.rec_groups
+            .iter()
+            .find(|(_, members)| members.contains(&id))
+            .map(|(gid, _)| *gid)
+    }
+
+    /// Fix up the types to ensure they are within the limits.
     pub fn fixup(&mut self, limits: &GcOpsLimits) {
```
Comment (khagankhan) [inline crates/fuzzing/src/generators/gc_ops/types.rs:122]: Based on our discussion I try to "save" some types after trimming and libfuzzer mutations

File: crates/fuzzing/src/generators/gc_ops/mutator.rs [hunk 5]
```diff
@@ -1,411 +1,407 @@
...
         c.mutation(|ctx| {
-            let group_id = ctx
-                .rng()
-                .choose(&ops.types.rec_groups)
-                .copied()
-                .expect("rec_groups not empty");
-            let new_tid = ops.types.fresh_type_id(ctx.rng());
-            ops.types.insert_empty_struct(new_tid, group_id);
-            log::debug!("Added empty struct type {new_tid:?} to rec group {group_id:?}");
+            let Some(gid) = ctx.rng().choose(types.rec_groups.keys()).copied() else {
```
Comment (khagankhan) [inline crates/fuzzing/src/generators/gc_ops/mutator.rs:31]: no panics. If the deserialization results in a corrupted ops, just skip it and it will be later fixed in `to_wasm_binary`. This fixup is the "mutation". No need to call fixup in mutations now.

**Comment by khagankhan** [comment]
Thanks @fitzgen! Ready for the next round of reviews!
