### PR TITLE
Change `proc_exit` to unwind the stack rather than exiting the host process.

### LINKED ISSUE #783: wasmtime should have more options for debugging errors in early program startup
given an example that displays output on stdout - like a "hello world" application - `wasmtime --env` appears to drop stdout entirely.

```
><> cat src/main.rs 
fn main() {
    println!("hello world!");
}
><> cargo build --target wasm32-wasi
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
><> wasmtime ./target/wasm32-wasi/debug/wasm32-wasi-demo.wasm 
hello world!
><> wasmtime --env 'FOO=bar' ./target/wasm32-wasi/debug/wasm32-wasi-demo.wasm 
><>
```

Tested with both 0.8.0 and the development release available on the releases page. Both demonstrate the same issue.

### LINKED ISSUE #993: wasi_unstable!proc_exit new trap type to force return to entry function 'nicely'
I was thinking about support for multiple WASM instances in the same host process. But ran into a problem with functions like `wasi_unstable!proc_exit` which are meant to kill the process rather than returning to the main entry function. Killing the process would not be desired in this case. A general use-case would be if a fork() feature was added which make use of the same host process to spawn copies of the running WASM instance - but when terminating an instance - it should then not impact the remaining instances. I'm looking for just running 'fully' independent instances in the same process for now, though.

But to make it possible to run multiple WASM instances - we really need a way to force a return to the instance entry function caller - and ensure the native function stack - but NOT the WASM stack - gets cleaned up. So I think we need a way to create a special termination/not-catchable trap - that just triggers jumps to the next native function call on the stack - but skipping any WASM frames for clean up. The new trap type ensures that WASM cannot recover from the termination request.

This does involve WASM exception handling and WASM C-lib. But I'll start here to see if this would be viable to solve for wasmtime.

### PR DESCRIPTION
**Pull request by sunfishcode**
This allows programs which call `proc_exit` to coexist with other programs in the same host process. This also implements the semantics in https://github.com/WebAssembly/WASI/pull/235.

Fixes #783.
Fixes #993.

### CODE REVIEW

File: crates/wiggle/generate/src/funcs.rs [hunk 1]
```diff
@@ -12,6 +12,12 @@ pub fn define_func(
 ) -> TokenStream {
     let funcname = func.name.as_str();
 
+    // `proc_exit` is special; it's essentially an unwinding primitive,
+    // so we implement it in the runtime rather than in wasi-common.
+    if funcname == "proc_exit" {
+        return quote!();
+    }
```
Comment (pchickey) [inline crates/wiggle/generate/src/funcs.rs:19]: This would break Lucet, where we deal with `proc_exit` in a totally different manner. We install a panic handler at the wasm->host boundary that terminates the instance, and then just `panic!` in our proc_exit trait method.

If that doesn't work for wasmtime, can we figure out a way to deal with `noreturn` functions in wiggle that works for both runtimes?

File: crates/wasi-common/wig/src/wasi.rs [hunk 2]
```diff
@@ -291,6 +299,14 @@ pub fn define_struct_for_wiggle(args: TokenStream) -> TokenStream {
             linker_add.push(quote! {
                 linker.define(#module_name, #name, self.#name_ident.clone())?;
             });
+            // `proc_exit` is special; it's essentially an unwinding primitive,
+            // so we implement it in the runtime rather than in wasi-common.
+            if name == "proc_exit" {
+                ctor_externs.push(quote! {
+                    let #name_ident = wasmtime::Func::exit_func(store);
```
Comment (pchickey) [inline crates/wasi-common/wig/src/wasi.rs:306]: Even though we're not exposing the `wig` generated snapshot 0 code to users over in the lucet embedding, this would make us take a dep on `wasmtime` in `lucet_runtime`, which would not be good.

File: crates/api/src/func.rs [hunk 3]
```diff
@@ -474,6 +474,46 @@ impl Func {
         func.into_func(store)
     }
 
+    /// Creates a new `Func` for a function which performs a program exit,
+    /// unwinding the stack up the point where wasm was most recently entered.
+    pub fn exit_func(store: &Store) -> Func {
```
Comment (alexcrichton) [inline crates/api/src/func.rs:479]: I'm curious if we can find a bit of a cleaner API to export this?

It looks like host functions have been updated to return `Result<T>` rather than `Result<T, Trap>`, which means that any arbitrary error type can be returned. Could we perhaps special case when the error is `Exit` and propagate that through, removing the need for an extra constructor here?

File: crates/runtime/src/traphandlers.rs [hunk 4]
```diff
@@ -457,6 +466,13 @@ impl<'a> CallThreadState<'a> {
                     maybe_interrupted,
                 })
             }
+            UnwindReason::Exit { status } => {
+                if let Some(status) = NonZeroI32::new(status) {
+                    Err(Trap::Exit { status })
+                } else {
+                    Ok(())
```
Comment (alexcrichton) [inline crates/runtime/src/traphandlers.rs:473]: This feels like it's somewhat dangerous here to me, should this be a panic or should `status` already have the type `NonZeroI32`?

File: crates/runtime/src/traphandlers.rs [hunk 5]
```diff
@@ -783,3 +799,40 @@ fn setup_unix_sigaltstack() -> Result<(), Trap> {
...
+pub unsafe extern "C" fn wasi_proc_exit(
+    _vmctx: *mut VMContext,
+    _caller_vmctx: *mut VMContext,
+    status: i32,
+) -> ! {
+    // Check that the status is within WASI's range.
+    if status >= 0 && status < 126 {
+        tls::with(|info| info.unwrap().unwind_with(UnwindReason::Exit { status }))
+    } else {
+        raise_user_trap(InvalidWASIExitStatus {}.into())
```
Comment (alexcrichton) [inline crates/runtime/src/traphandlers.rs:823]: Given that we only really have "trusted" code calling this, could this be a panic or something more general? This seems a bit low-level to be dealing with WASI-specific codes and things.

File: crates/wiggle/generate/src/funcs.rs (hunk 1 above)
Comment (sunfishcode) [reply crates/wiggle/generate/src/funcs.rs:19]: I considered using panics here, but didn't because of the possibility of users embedding Wasmtime in programs built with `panic = "abort"`.

My main idea is that `proc_exit` doesn't access memory, take any strings, use any handles, etc., so it doesn't need any of the wig machinery. It can just be a plain `extern "C"` function somewhere, and different runtimes can still do different things in the implementation -- panic as Lucet does, or trigger a trap-like unwind as this PR does. And that way, it can trap without having to worry about unwinding through wig's Rust code.

File: crates/wasi-common/wig/src/wasi.rs (hunk 2 above)
Comment (sunfishcode) [reply crates/wasi-common/wig/src/wasi.rs:306]: This code already depends on `wasmtime::Func::wrap`; how does that work in Lucet?

Comment (pchickey) [reply crates/wasi-common/wig/src/wasi.rs:306]: I missed that in my first look, any dep inside `wasi-common` on `wasmtime` (or anything besides wig/wiggle) would be a showstopper for integration with Lucet. (I'm on vacation this week and will not be around much, just popped in from a lack of discipline)

Comment (sunfishcode) [reply crates/wasi-common/wig/src/wasi.rs:306]: @kubkon `define_struct` has the comment "This is a single-use macro intended to be used in the `wasmtime-wasi` crate.". Do you know if that's intended to be the case for `define_struct_for_wiggle`? `define_struct_for_wiggle` currently has Wasmtime-specific code in it, so if it's meant to be usable outside of Wasmtime, we'll need to figure out how to factor that out.

Comment (kubkon) [reply crates/wasi-common/wig/src/wasi.rs:306]: I’m pretty sure `wig` is fully internal to `Wasmtime`, and so is `define_struct_for_wiggle`. As far as I remember, `lucet` had their own set of magical macros, but @pchickey can correct me here if I’m wrong :-)

**Comment by sunfishcode** [comment]
Thanks for the feedback @pchickey and @alexcrichton! I've now reworked the patch here to avoid making any changes to wiggle, and to go back to `Result<T, Trap>` with extra info in `Trap` instead of `anyhow::Error`. Both of these turned out to enable several things to be much simpler as well.

File: crates/wasi-common/src/old/snapshot_0/hostcalls_impl/misc.rs [hunk 6]
```diff
@@ -342,10 +342,14 @@ pub(crate) struct FdEventData<'a> {
     pub(crate) userdata: wasi::__wasi_userdata_t,
 }
 
+// Not all implementations use this implementation.
+#[allow(dead_code)]
```
Comment (alexcrichton) [inline crates/wasi-common/src/old/snapshot_0/hostcalls_impl/misc.rs:346]: Should this perhaps just be deleted?

File: crates/api/src/trap.rs [hunk 7]
```diff
@@ -12,8 +12,27 @@ pub struct Trap {
     inner: Arc<TrapInner>,
 }
 
+/// State describing the occasion which evoked a trap.
+#[derive(Debug)]
+pub enum TrapReason {
+    /// An error message describing a trap.
+    Message(String),
```
Comment (alexcrichton) [inline crates/api/src/trap.rs:19]: Exposing an `enum` often makes pretty hard guarantees about representations which are tough to change. Could we  perhaps retain `fn message()` with a canned string for exit statuses, and then add an extra accessor returning `Option<i32>` for reading the exit code?

File: src/commands/run.rs [hunk 8]
```diff
@@ -142,13 +142,24 @@ impl RunCommand {
...
-                if e.is::<Trap>() {
+                // If the program exited because of a non-zero exit status, print
+                // a message and exit.
+                if let Some(trap) = e.downcast_ref::<Trap>() {
                     // Print the error message in the usual way.
                     eprintln!("Error: {:?}", e);
 
+                    if let TrapReason::I32Exit(status) = trap.reason() {
+                        // On Windows, exit status 3 indicates an abort (see below),
+                        // so just return 1 indicating a non-zero status.
```
Comment (alexcrichton) [inline src/commands/run.rs:153]: This seems a bit odd to me, why not expose exiting with all sorts of error codes on Windows?

Comment (alexcrichton) [reply src/commands/run.rs:153]: (or put another way I don't fully understand the comment as to why Windows is special here)

File: crates/wasi-common/src/old/snapshot_0/hostcalls_impl/misc.rs (hunk 6 above)
Comment (pchickey) [reply crates/wasi-common/src/old/snapshot_0/hostcalls_impl/misc.rs:346]: There's no dep on this code in Lucet, so if Wasmtime doesn't intend to use it, lets delete it.

File: crates/wasi-common/src/snapshots/wasi_snapshot_preview1.rs [hunk 9]
```diff
@@ -813,12 +813,15 @@ impl<'a> WasiSnapshotPreview1 for WasiCtx {
...
+    #[allow(dead_code)]
     // This is just a temporary to ignore the warning which becomes a hard error
     // in the CI. Once we figure out non-returns in `wiggle`, this should be gone.
     #[allow(unreachable_code)]
     fn proc_exit(&self, rval: types::Exitcode) -> std::result::Result<(), ()> {
-        // TODO: Rather than call std::process::exit here, we should trigger a
-        // stack unwind similar to a trap.
+        // Note that this is just a default implementation. Host environments
+        // will often override this `proc_exit` implementation and do other
+        // things other than exit the host process.
```
Comment (pchickey) [inline crates/wasi-common/src/snapshots/wasi_snapshot_preview1.rs:824]: If both wasmtime and lucet override this implementation, maybe we could instead replace it with `unimplemented!("runtimes are expected to override this implementation")`?

File: src/commands/run.rs (hunk 8 above)
Comment (sunfishcode) [reply src/commands/run.rs:153]: I don't have a strong sense of what Windows wants here; I just didn't want to overload exit status 3 as meaning both "program trapped" and "program explicitly exited with status 3".

Am I reading too much into the docs by assuming that using 3 for an abort is a meaningful convention?

File: crates/wasi-common/src/old/snapshot_0/hostcalls_impl/misc.rs (hunk 6 above)
Comment (sunfishcode) [reply crates/wasi-common/src/old/snapshot_0/hostcalls_impl/misc.rs]: Done.

File: crates/api/src/trap.rs (hunk 7 above)
Comment (sunfishcode) [reply crates/api/src/trap.rs:19]: Done

File: crates/wasi-common/src/snapshots/wasi_snapshot_preview1.rs (hunk 9 above)
Comment (sunfishcode) [reply crates/wasi-common/src/snapshots/wasi_snapshot_preview1.rs]: Done
