### PR TITLE
egraphs: fix accidental remat of call.

### LINKED ISSUE #5716: Cranelift: "register allocation: SSA(VReg(vreg = 145, class = Int), Inst(0))" in upcoming 0.93 when compiling with optimizations
### `.clif` Test Case

```
test compile
set opt_level=speed_and_size
target aarch64

function u0:33() system_v {
    ss0 = explicit_slot 32
    sig0 = (i64, i64, i64, i64, i64) -> i64, i64 system_v
    fn0 = colocated u0:0 sig0
    jt0 = jump_table [block36, block38]

block0:
    v80 = iconst.i32 0
    v91 = iconst.i64 0
    v92 = iconst.i64 0
    v96 = iconst.i64 0
    v235 = iconst.i64 0
    v236 = iconst.i64 0
    v237 = iconst.i64 0
    v238, v239 = call fn0(v236, v237, v91, v92, v235)  ; v236 = 0, v237 = 0, v91 = 0, v92 = 0, v235 = 0
    v97 = iadd v238, v96  ; v96 = 0
    br_table v80, block37, jt0  ; v80 = 0

block36:
    trap user0

block37:
    trap unreachable

block38:
    v98 = load.i8 notrap v97
    v99 = fcvt_from_uint.f64 v98
    stack_store v99, ss0
    trap user0
}
```

### Steps to Reproduce

* `clif-util test repro.clif`

### Expected Results

Compiles

### Actual Results

Regalloc checker error: `register allocation: SSA(VReg(vreg = 145, class = Int), Inst(0))`

### Versions and Environment

Cranelift version or commit: Cranelift 0.93 (43022c862a1d497f4b8c7c2fce47148775503add on the release-6.0.0 branch) which is not yet released.

Operating system: Linux

Architecture: AArch64

### PR DESCRIPTION
**Pull request by cfallin**
In the provided test case in #5716, the result of a call was then added to 0. We have a rewrite rule that sets the remat-bit on any add of a value and a constant, because these frequently appear (e.g. from address offset calculations) and this can frequently reduce register pressure (one long-lived base vs. many long-lived base+offset values). Separately, we have an algebraic rule that `x+0` rewrites to `x`.

The result of this was that we had an eclass with the remat bit set on the add, but the add was also union'd into the call. We pick the latter during extraction, because it's cheaper not to do the add at all; but we still get the remat bit, and try to remat a call (!), which blows up later.

This PR fixes the logic to look up the "best value" for a value (i.e., whatever extraction determined), and look up the remat bit on *that* node, not the canonical node.

(Why did the canonical node become the iadd and not the call? Because the former had a lower value-number, as an accident of IR construction; we don't impose any requirements on the input CLIF's value-number ordering, and I don't think this breaks any of the important acyclic properties, even though there is technically a dependence from a lower-numbered to a higher-numbered node. In essence one can think of them as having "virtual numbers" in any true topologically-sorted order, and the only place the actual integer indices matter should be in choosing the "canonical ID", which is just used for dedup'ing, modulo this bug.)

Fixes #5716.

### CODE REVIEW

**Comment by cfallin** [comment]
Once merged I'll backport this to the 6.0 release branch as well.

File: cranelift/codegen/src/egraph/elaborate.rs [hunk 1]
```diff
@@ -278,6 +278,14 @@ impl<'a> Elaborator<'a> {
...
+                    // Get the best option; we use `value` (latest
+                    // value) here so we have a full view of the
+                    // eclass.
+                    trace!("looking up best value for {}", value);
+                    let (_, best_value) = self.value_to_best_value[value];
+                    debug_assert_ne!(best_value, Value::reserved_value());
+                    trace!("elaborate: value {} -> best {}", value, best_value);
+
                     let remat = if let Some(elab_val) =
                         self.value_to_elaborated_value.get(&canonical_value)
```
Comment (jameysharp) [inline cranelift/codegen/src/egraph/elaborate.rs:290]: Should this lookup also switch to `best_value` instead of `canonical_value`? What about the later uses of `canonical_value`? Perhaps `canonical_value` should just be dead as soon as we've looked up `best_value`, maybe enforced by shadowing it?

Comment (cfallin) [reply cranelift/codegen/src/egraph/elaborate.rs:290]: This actually needs to be the canonical-value, to avoid unnecessary codegen!

The reason is that we record the elaborated values in the map with canonical-ID as key, and we want to dedup as much as possible here. Otherwise if we refer to a value with different IDs that point to different parts of the eclass, we'll have unnecessary misses and recomputations.

However it's good that you asked because I went over the whole function and saw that below, another `canonical_value` should be `best_value`, when we look up remat in the other case!

**Review by jameysharp — APPROVED** [review]
Well, I'm convinced. :grin:
