### PR TITLE
cranelift-jit: Implement RISC-V Call relocation

### LINKED ISSUE #5832: cranelift-jit: Panic when calling colocated function in riscv64
👋 Hey,

Fuzzgen found this when I tried to run #5765 on a RISC-V machine.

### `.clif` Test Case

```
test run
target riscv64gc

function %b() {
block0:
    return
}

function %a(i16) -> i16 {
    sig0 = () system_v
    fn0 = colocated %b sig0

block0(v0: i16):
    call fn0()
    return v0
}

; run: %a(1) == 1
```

### Steps to Reproduce

* `clif-util test ./the-above.clif`

### Expected Results

The test to pass

### Actual Results

```
     Running `qemu-riscv64 -L /usr/riscv64-linux-gnu -E LD_LIBRARY_PATH=/usr/riscv64-linux-gnu/lib /home/afonso/git/wasmtime/target/riscv64gc-unknown-linux-gnu/debug/clif-util test ./lmao.clif`
thread 'worker #1' panicked at 'not implemented', cranelift/jit/src/compiled_blob.rs:105:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ERROR cranelift_filetests::concurrent > FAIL: panicked in worker #1: not implemented
FAIL ./lmao.clif: panicked in worker #1: not implemented
1 tests
Error: 1 failure
```

### Versions and Environment

Cranelift version or commit: main

Operating system: Linux

Architecture: riscv64

### Extra Info

The testcase passes if we drop the `colocated` flag.

Looks like we are missing handling for the RISC-V Call relocation in the JIT.

### PR DESCRIPTION
**Pull request by afonso360**
👋 Hey,

This PR implements handling for the R_RISCV_CALL relocation in the JIT.

I'm going to let the fuzzer run overnight on this.

Fixes #5832

Edit: Fuzzer ran overnight and didn't find anything related to calls.

### CODE REVIEW

File: cranelift/jit/src/compiled_blob.rs [hunk 1]
```diff
@@ -3,6 +3,16 @@ use cranelift_module::ModuleExtName;
 use cranelift_module::ModuleReloc;
 use std::convert::TryFrom;
 
+/// Reads a 32bit instruction at `iptr`, and writes it again after
+/// being altered by `modifier`
+fn modify_inst32(iptr: *mut u32, modifier: impl FnOnce(u32) -> u32) {
```
Comment (bjorn3) [inline cranelift/jit/src/compiled_blob.rs:8]: This function should be unsafe.

**Review by jameysharp — APPROVED** [review]
I think this is correct, as best I can tell.

I got a little concerned about endianness, but I guess you can't sensibly use cranelift-jit for cross-compiling, so it's probably fine?

**Comment by afonso360** [comment]
I don't think the other relocation handlers worry about that either so I guess its probably okay.
